New single scenario
ONSdigital/census-rm-acceptance-tests-2021 pull request #10
Opened 2019-02-07 15:15 UTC by LukeLoze1

2019-02-07 15:16 UTC, hbrace approved these changes

2019-02-08 07:38 UTC, rjweeks requested changes

2019-02-08 07:38 UTC, rjweeks commented on utilities/collection_exercise_utilities.py
> -    logger.debug("Successfully created collection exercise", exercise_ref=exercise_ref)
We still want the logging.

2019-02-08 07:38 UTC, rjweeks commented on utilities/collection_exercise_utilities.py
> +        "exerciseRef": '1',
Why have you hard coded exerciseRef and userDescription? These should be parameters.

2019-02-08 07:38 UTC, rjweeks commented on utilities/collection_exercise_utilities.py
> +    assert response.status_code == 201
Use response.raise_for_status not asserts in this utility code.

2019-02-08 07:38 UTC, rjweeks commented on utilities/survey_utilities.py
> +    assert response.status_code == 201
I don't think we should use asserts in Utility code. Use response.raise_for_status

2019-02-08 07:59 UTC, LukeLoze1 commented on utilities/collection_exercise_utilities.py
> +        "exerciseRef": '1',
The idea is to get something working for the 1st simple test.  If we want to parameterize it further for later tests then that's good

2019-02-08 08:08 UTC, LukeLoze1 commented on utilities/collection_exercise_utilities.py
> -    logger.debug("Successfully created collection exercise", exercise_ref=exercise_ref)
done

2019-02-08 09:10 UTC, hbrace commented on utilities/collection_exercise_utilities.py
> +    assert response.status_code == 201
Should be response.raise_for_status()? Asserts in the test steps?

2019-02-08 09:10 UTC, hbrace commented on utilities/survey_utilities.py
> +    assert response.status_code == 201
response.raise_for_status()?

2019-02-08 11:17 UTC, LukeLoze1 commented on utilities/collection_exercise_utilities.py
> +    assert response.status_code == 201
done

2019-02-08 12:53 UTC, rjweeks approved these changes

2019-02-08 12:54 UTC, merged

2019-02-12 13:16 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automated testing](https://trello.com/c/PUT3GUaJ/438-automated-testing)