Refactored existing Questionnaire linked test to cover new functionality
ONSdigital/census-rm-acceptance-tests-2021 pull request #105
Opened 2019-08-15 11:36 UTC by AdeHarrison

# How to test?
as part of [attached pr](url)

# Links
[Trello](https://trello.com/c/HaHa9jE7/826-rmc-142-implement-questionnaire-linked-event-13)

# Screenshots (if appropriate):

2019-08-15 11:41 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-142 Implement Questionnaire Linked Event (13)](https://trello.com/c/HaHa9jE7/826-rmc-142-implement-questionnaire-linked-event-13)

2019-08-15 14:20 UTC, NickGrantONS commented on acceptance_tests/features/steps/unaddressed.py
> +    start_listening_to_rabbit_queue(Config.RABBITMQ_RH_OUTBOUND_CASE_QUEUE_TEST,
why does this get called a sercond time?

2019-08-19 06:12 UTC, AdamHawtin requested changes

2019-08-19 06:12 UTC, AdamHawtin commented on acceptance_tests/features/unaddressed.feature
> +    And a CaseUpdated message is emitted to RH and Action Scheduler
Test should check for the UAC Updated message with the new link being sent.

2019-08-19 07:41 UTC, AdeHarrison commented on acceptance_tests/features/steps/unaddressed.py
> +    start_listening_to_rabbit_queue(Config.RABBITMQ_RH_OUTBOUND_CASE_QUEUE_TEST,
to skip over receipt case updated message

2019-08-19 10:02 UTC, AdeHarrison commented on acceptance_tests/features/unaddressed.feature
> +    And a CaseUpdated message is emitted to RH and Action Scheduler
done

2019-08-19 12:42 UTC, AdamHawtin commented on acceptance_tests/features/unaddressed.feature
> +    And a CaseUpdated message is emitted to RH and Action Scheduler
I can't see it checking for the UAC Updated event anywhere? I definitely think that should be tested for, it's an critical part of this feature that RH etc are notified of the link.

2019-08-19 13:14 UTC, rjweeks commented on acceptance_tests/features/steps/unaddressed.py
> -    context.linked_case = context.case_created_events[1]['payload']['collectionCase']
This is sending a message but not checking a linked message is received? Function name should be changed.

2019-08-20 06:56 UTC, closed without merging