980 event logging
ONSdigital/census-rm-acceptance-tests-2021 pull request #107
Opened 2019-08-16 15:44 UTC by LukeLoze1

# Motivation and Context
As part of https://trello.com/c/9drX7XPj/980-logging-the-wrong-things-in-the-case-events-table the current event logging was fixed.  This was a little clean up adding some additional and refactoring other tests for better code re-use

# What has changed
Better (hopefully) event logging testing

# How to test?
tests should run and pass with everything else on master

# Links

# Screenshots (if appropriate):

2019-08-19 07:58 UTC, NickGrantX approved these changes
Looks good

2019-08-19 13:32 UTC, AdamHawtin requested changes

2019-08-19 13:32 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment_request.py
> +    context.case_for_events_check = {'id': context.uac_created_events[0]['payload']['uac']['caseId']}
Not sure why this is wrapped in a dictionary like this? I'm not keen on building and naming things for the purposes of other steps that this step shouldn't need to know about. It makes it much harder to track down where things are being set.

2019-08-19 13:32 UTC, AdamHawtin commented on acceptance_tests/features/steps/refusal.py
> +    context.case_for_events_check = {'id': context.uac_created_events[0]['payload']['uac']['caseId']}
Not sure why this is wrapped in a dictionary like this? I'm not keen on building and naming things for the purposes of other steps that this step shouldn't need to know about. It makes it much harder to track down where things are being set.

2019-08-19 13:32 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +    assert context.case_for_events_check[case_field] == bool(expected_field_value)
```python 
bool("False") == True
```
Strings are only false-y if they're empty so this step would break if `expected_field_value` was "False".

2019-08-20 08:42 UTC, LukeLoze1 commented on acceptance_tests/features/steps/refusal.py
> +    context.case_for_events_check = {'id': context.uac_created_events[0]['payload']['uac']['caseId']}
Pycharm recommended the dictionary thing
There's a potential spaghetti code issue inherent in using the context object as it's essentially setting global variables for the test duration.  However in this case where values are set dynamically it's extremely useful and can allow for cleaner code and code re-use.  Seems the lesser of 2 evils to me.

2019-08-20 08:50 UTC, LukeLoze1 commented on acceptance_tests/features/steps/fulfilment_request.py
> +    context.case_for_events_check = {'id': context.uac_created_events[0]['payload']['uac']['caseId']}
Pycharm recommended the dictionary thing, happy to see a nicer way of setting it
There's a potential spaghetti code issue inherent in using the context object as it's essentially setting global variables for the test duration. However in this case where values are set dynamically it's extremely useful and can allow for cleaner code and code re-use. Seems the lesser of 2 evils to me.  We use it all over the ATs, I'm struggling to think of the use of context object if you don't use it like this

2019-08-20 13:45 UTC, AdamHawtin requested changes
A few comments, also I'm a bit unsure about this approach. I like making the code behind the scenarios reusable, I think that's a great improvement but I'm not fond of how the fulfilment request feature, for example, tests now also tests for `SAMPLE_LOADED` events. That's making them more brittle as if we ever add another event to the normal case flow, every single scenario would now have to updated to match. I like generalising the code behind but I think the steps should still be allowed to use specific wording and only look for one specific event.

2019-08-20 13:45 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_look_up.py
> +@then("events logged for case are {event_type_list}")
```suggestion
@then(" the events logged for the case are {event_type_list}")
```

2019-08-20 13:45 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment_request.py
> +    context.case_for_events_check = {'id': context.uac_created_events[0]['payload']['uac']['caseId']}
I wouldn't argue against using the context for passing data around, but I'd rather not build variable names or data structures in one step specifically for other, unrelated steps to use as it's coupling things together and makes it much more difficult to track things down, especially as the code changes. Maybe just naming it something like `first_case` or `selected_case`, then it's up to each step how they use it. It just sits wrong with me naming it `case_for_events_check` here when this step has nothing to do with event checking and is actually using it to post a fulfilment request for the case.

About the dictionary, you're using this same attribute name to store a full case JSON response dictionary later. Here's it's only getting the ID so it should probably just store it as a string

2019-08-20 13:45 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_look_up.py
> +@then("events logged for case are {event_type_list}")
```suggestion
@then("the events logged for the case are {event_type_list}")
```

2019-08-21 06:16 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_look_up.py
> +@then("the events logged for the case are {event_type_list}")
The features need updating to match.

2019-08-22 08:14 UTC, LukeLoze1 commented on acceptance_tests/features/steps/case_look_up.py
> +@then("events logged for case are {event_type_list}")
I've made some changes, I'm happy for you to perhaps tweak/alter at a later time to accommodate this requirement

2019-08-22 11:45 UTC, AdamHawtin requested changes
Happy with it now, just a left over commented out line

2019-08-22 11:45 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment_request.py
> +    # time.sleep(2)
Delete commented out line

2019-08-22 11:51 UTC, AdamHawtin requested changes

2019-08-22 11:51 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment_request.feature
> +    And the fulfilment request case has these events logged [SAMPLE_LOADED,FULFILMENT_REQUESTED,RM_UAC_CREATED]
The other step which checks for the event log hasn't been removed

2019-08-22 11:51 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment_request.py
> +    # time.sleep(2)
In fact, these feature are now intermittently failing for me, the sleep might still be necessary.

2019-08-22 12:10 UTC, AdamHawtin approved these changes

2019-08-22 12:44 UTC, merged