Rmc 211 a individual uac request logging
ONSdigital/census-rm-acceptance-tests-2021 pull request #109
Opened 2019-08-20 13:41 UTC by LukeLoze1

# Motivation and Context
Checks for individual response requests 

# What has changed
New fulfillment request test, tests also check for correct template id and that child case has been created 

# How to test?
With the related case processor repo installed run 'make test'

# Links
https://trello.com/c/xem9Ksud/878-rmc-211a-handle-request-for-individual-uac-8

# Screenshots (if appropriate):

2019-08-20 14:43 UTC, liamtoozer commented on acceptance_tests/features/steps/fulfilment_request.py
> +                        "address": "abc road"
Appreciate address isn't being sent across in messages, but looks like the format would be this:
```
"payload" : {
    "fulfilmentRequest" : {
      "fulfilmentCode": "XXXXXX-XXXXXX",
      "caseId" : "bbd55984-0dbf-4499-bfa7-0aa4228700e9",
      "address": {},
      "contact": {
                   "telNo":"+447890000000"
                 }
    }
```

2019-08-20 14:43 UTC, liamtoozer commented on acceptance_tests/features/steps/fulfilment_request.py
> +def _get_parent_case_arid(context):
`_get_parent_case_estabarid` instead?

2019-08-20 14:44 UTC, liamtoozer commented on resources/sample_files/sample_input_england_census_spec.csv
> +DDR190314000000195676,DDR190314000000113740,10008677190,HH,Household,U,RD06,,Flat 52 Francombe House,Commercial Road,,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E06000023
Would the `ESTAB_ARID` fields would need to be unique instead if we're checking the parent/child link with that?

2019-08-20 14:44 UTC, liamtoozer approved these changes
Minor comments but the ATs all pass for me 👍

2019-08-20 14:52 UTC, LukeLoze1 commented on acceptance_tests/features/steps/fulfilment_request.py
> +                        "address": "abc road"
If it's not there at the moment, I think we don't need to put it there

2019-08-21 08:28 UTC, NickGrantX approved these changes
Nice improvements.

2019-08-21 10:17 UTC, davidmort requested changes

2019-08-21 10:17 UTC, davidmort commented on acceptance_tests/features/steps/fulfilment_request.py
> +                        "address": "abc road"
i agree with @liamtoozer here, if we're going to have the address in the in test message then that message needs to be the correct shape otherwise it's misleading

2019-08-21 10:34 UTC, LukeLoze1 commented on acceptance_tests/features/steps/fulfilment_request.py
> +                        "address": "abc road"
Ok, misunderstanding by me. It's now fixed to look like the event dictionary that has a blank address field in it.

2019-08-21 13:01 UTC, davidmort approved these changes

2019-08-21 13:12 UTC, merged