Add test for pqrs receipting
ONSdigital/census-rm-acceptance-tests-2021 pull request #110
Opened 2019-08-20 13:57 UTC by gavinleeedwards

## Motivation and Context
We need to process receipts from PQRS and QM so that we no longer chase cases who have responded with a paper questionnaire.

## What has changed
- Added new tests for handling offline receipts

## How to test?
Run the acceptance tests against the branches on the Trello ticket

## Links
https://trello.com/c/conn8do9
https://github.com/ONSdigital/census-rm-pubsub/pull/32
https://github.com/ONSdigital/census-rm-terraform/pull/79
https://github.com/ONSdigital/census-rm-docker-dev/pull/28
https://github.com/ONSdigital/census-rm-kubernetes/pull/100

2019-08-20 14:32 UTC, gavinleeedwards commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-152 Handle Paper Questionnaire Receipts (13)](https://trello.com/c/conn8do9/724-rmc-152-handle-paper-questionnaire-receipts-13)

2019-08-21 07:13 UTC, AdamHawtin requested changes

2019-08-21 07:13 UTC, AdamHawtin commented on config.py
> +    OFFLINE_RECEIPT_TOPIC_ID = os.getenv('OFFLINE_RECEIPT_TOPIC_ID', 'offline-receipting-topic')
```suggestion
    OFFLINE_RECEIPT_TOPIC_ID = os.getenv('OFFLINE_RECEIPT_TOPIC_ID', 'offline-receipt-topic')
```
Is what the docker dev branch creates.

2019-08-27 12:13 UTC, ryangrundy7 reviewed
Having your tests pass locally but some unaddressed tests are failing. I think merging master should fix it so i'll wait to approve it

2019-08-28 09:46 UTC, ryangrundy7 requested changes
Some steps are wrong, guessing from the merge commit

2019-08-28 09:46 UTC, ryangrundy7 commented on acceptance_tests/features/receipt.feature
> +    And a ActionCancelled event is sent to field work management
Lines 28 and 29 should be this instead:
```
And an ActionCancelled event is sent to field work management    
And the events logged for the receipted case are [RESPONSE_RECEIVED,SAMPLE_LOADED]
```

2019-08-28 09:46 UTC, ryangrundy7 commented on acceptance_tests/features/receipt.feature
> +    And a ActionCancelled event is sent to field work management
Lines 19 and 20 should be this instead:
```
And an ActionCancelled event is sent to field work management    
And the events logged for the receipted case are [RESPONSE_RECEIVED,SAMPLE_LOADED]
```

2019-08-28 13:03 UTC, ryangrundy7 approved these changes

2019-08-28 13:18 UTC, AdamHawtin approved these changes

2019-08-28 13:34 UTC, merged