Created new test for scheduled reminder questionnaires
ONSdigital/census-rm-acceptance-tests-2021 pull request #116
Opened 2019-08-27 15:50 UTC by ryangrundy7

# Motivation and Context
Added test for scheduled reminder questionnaires

# What has changed
- Added new print file reminder questionnaire test
# How to test?
- Run acceptance tests with branches on [Action scheduler ](https://github.com/ONSdigital/census-rm-action-scheduler/pull/32)and [print-file service](https://github.com/ONSdigital/census-rm-print-file-service/pull/13)

# Links
[Trello](https://trello.com/c/4GUC0HS0/)

2019-08-27 15:54 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-157 Schedule, generate and distribute reminder PQs (5)](https://trello.com/c/4GUC0HS0/723-rmc-157-schedule-generate-and-distribute-reminder-pqs-5)

2019-08-27 15:55 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_events.py
> +            tc.fail(msg='Could not find sample unit')
👍

2019-08-27 16:00 UTC, AdamHawtin requested changes
All passing locally, just a minor code comment.

2019-08-27 16:00 UTC, AdamHawtin commented on acceptance_tests/utilities/print_file_helper.py
> +def _create_expected_reminder_questionnaire_csv_line(case, prefix):
I think this is duplicating the existing `_create_expected_questionnaire_csv_line`

2019-08-27 16:00 UTC, AdamHawtin commented on acceptance_tests/features/print_file.feature
> +    Given sample file "<sample file>" is loaded successfully
👍 Nice to have a single step for successful sample load/case distribution.

2019-08-28 07:51 UTC, ryangrundy7 commented on acceptance_tests/utilities/print_file_helper.py
> +def _create_expected_reminder_questionnaire_csv_line(case, prefix):
Done

2019-08-28 09:25 UTC, hbrace approved these changes

2019-08-28 11:17 UTC, AdamHawtin approved these changes

2019-08-28 12:35 UTC, merged