Individual questionnaire linked
ONSdigital/census-rm-acceptance-tests-2021 pull request #119
Opened 2019-09-02 08:32 UTC by AdeHarrison

# Motivation and Context

# What has changed
Acceptance test added to check individual paper questionnaire request.
Improved "Questionnaire linked to unaddressed" test

# How to test?
[as per](url)

# Links
[Trello](https://trello.com/c/6mZA6Ynw/1040-rmc-142-part-2-handle-individual-pq-linked-event-8)

# Screenshots (if appropriate):

2019-09-02 08:34 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-142 (part 2) Handle Individual PQ Linked Event (8)](https://trello.com/c/6mZA6Ynw/1040-rmc-142-part-2-handle-individual-pq-linked-event-8)

2019-09-02 10:33 UTC, gavinleeedwards approved these changes
All tests pass against the same branch in case-processor.

2019-09-03 08:59 UTC, LukeLoze1 requested changes
some requested changes to remove some sleeps

2019-09-03 08:59 UTC, LukeLoze1 commented on acceptance_tests/features/steps/unaddressed.py
> +    time.sleep(5)  # Give case processor a chance to process the Questionnaire Linked event
I think we're trying to move away from using sleeps like this and have replaced them with retries
@retry(stop_max_attempt_number=10, wait_fixed=1000)

In this case I think the step would call another function with a retry on it

2019-09-03 08:59 UTC, LukeLoze1 commented on acceptance_tests/features/steps/unaddressed.py
> +    time.sleep(5)  # Give case processor a chance to process the Questionnaire Linked event
suggestion for this area:  (code lifted from fulfilment.py) . function also called check_case_events, which here and there is a bit generic.  

@then("a Questionnaire Linked event is logged")
def check_questionaire_linked_logging(context):
    check_question_linked_event_is_logged(context)


@retry(stop_max_attempt_number=10, wait_fixed=1000)
def check_question_linked_event_is_logged(context):
    response = requests.get(f'{caseapi_url}{context.linked_case_id}', params={'caseEvents': True})
    assert 200 <= response.status_code <= 299, 'Get cases API call failed'
    cases = response.json()
    assert any(case_event['description'] == 'Questionnaire Linked' for case_event in cases['caseEvents'])

2019-09-03 08:59 UTC, LukeLoze1 commented on acceptance_tests/features/steps/unaddressed.py
> +    time.sleep(5)  # Give case processor a chance to process the Questionnaire Linked event
retry rather than sleep

2019-09-04 06:53 UTC, AdeHarrison commented on acceptance_tests/features/steps/unaddressed.py
> +    time.sleep(5)  # Give case processor a chance to process the Questionnaire Linked event
done

2019-09-04 06:53 UTC, AdeHarrison commented on acceptance_tests/features/steps/unaddressed.py
> +    time.sleep(5)  # Give case processor a chance to process the Questionnaire Linked event
done

2019-09-04 07:28 UTC, liamtoozer commented on acceptance_tests/features/unaddressed.feature
> +    When an unaddressed message of questionnaire type 21 is sent
Some of these When/Thens might need to be re-jigged to 'And' instead

2019-09-04 08:04 UTC, liamtoozer commented on acceptance_tests/features/unaddressed.feature
> +    Given sample file "sample_for_questionnaire_linked.csv" is loaded
@AdamHawtin [mentioned in another PR](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/121#discussion_r320592769) that these first 2 steps can be rewritten as 1 instead, using an existing step

2019-09-05 11:40 UTC, LukeLoze1 approved these changes
LGTM

2019-09-05 11:41 UTC, liamtoozer commented on acceptance_tests/features/unaddressed.feature
> +    When an unaddressed message of questionnaire type 21 is sent
Sorted in [this commit](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/119/commits/a41158041a97cd30c910b713a559d2354af0ec91)

2019-09-05 11:41 UTC, liamtoozer commented on acceptance_tests/features/unaddressed.feature
> +    Given sample file "sample_for_questionnaire_linked.csv" is loaded
Sorted in [this commit](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/119/commits/a41158041a97cd30c910b713a559d2354af0ec91)

2019-09-05 11:42 UTC, liamtoozer approved these changes
LGTM 👍

2019-09-05 12:15 UTC, merged