create mandatory events for collection exercise
ONSdigital/census-rm-acceptance-tests-2021 pull request #12
Opened 2019-02-08 13:33 UTC by hbrace

Adds collection exercise mandatory events.
Current dates are just temporary

2019-02-08 13:34 UTC, rjweeks approved these changes

2019-02-08 14:43 UTC, LukeLoze1 requested changes

2019-02-08 14:43 UTC, LukeLoze1 commented on acceptance_tests/features/steps/setup_steps.py
> +        assert status == 201
use 'requests.codes.created' instead of 201

2019-02-08 14:43 UTC, LukeLoze1 commented on utilities/collection_exercise_utilities.py
> +    if response.status_code == 201:
requests.codes.created instead of 201

2019-02-08 14:43 UTC, LukeLoze1 commented on utilities/collection_exercise_utilities.py
> +        if response.status_code == 201:
requests.codes.created instead of 201

2019-02-11 09:24 UTC, LukeLoze1 approved these changes

2019-02-11 09:27 UTC, merged

2019-02-12 13:15 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automated testing](https://trello.com/c/PUT3GUaJ/438-automated-testing)