Rmc 211 individual response mappings
ONSdigital/census-rm-acceptance-tests-2021 pull request #120
Opened 2019-09-02 13:28 UTC by LukeLoze1

# Motivation and Context
Fix HI Case not be recorded correctly and check print files are created when requested

# What has changed
Tests now check for individual print response codes produce print files

# How to test?
Run this test branch with the other branches from the ticket

# Links
https://trello.com/c/KrSKaCSj/1008-rmc-211b-implement-individual-pq-requested-event-5

2019-09-03 08:33 UTC, hbrace requested changes

2019-09-03 08:33 UTC, hbrace commented on acceptance_tests/features/steps/fulfilment_request.py
> +def step_impl(context):
Should this function have a proper name?

2019-09-03 09:02 UTC, LukeLoze1 commented on acceptance_tests/features/steps/fulfilment_request.py
> +def step_impl(context):
yes, and perhaps actually check the case

2019-09-03 12:09 UTC, hbrace approved these changes
Paired on this but happy with it

2019-09-03 12:22 UTC, liamtoozer commented on acceptance_tests/features/steps/fulfilment_request.py
> +@step('an individual print fulfilment request "{fulfilment_code}" is received by RM')
Could maybe move the fulfilment message sending into its own single function now as we're sending the same thing?

Either that, or could maybe move this `@step` to the `create_uac_fulfilment_message` function instead since it's doing something similar? Would just need to rename the function to something more meaningful then.

2019-09-03 13:00 UTC, liamtoozer commented on acceptance_tests/features/steps/fulfilment_request.py
> +@step("a new Case Created is emitted")
Could we use the step for `a new child case is emitted to RH and Action Scheduler` here instead if we're checking the HI case is create?

2019-09-03 13:17 UTC, liamtoozer commented on acceptance_tests/features/steps/fulfilment_request.py
> +    individual_case = requests.get(f'{get_cases_url}{individual_case_id}').json()
Quick question - should we be searching by the `context.individual_case_id` in the earlier step instead of what's coming from this message?

2019-09-03 13:21 UTC, liamtoozer commented on acceptance_tests/features/fulfilment_request.feature
> +    And the fulfilment request event is logged
Is there a reason we're not reusing `And the individual case has these events logged [RM_UAC_CREATED]` for the last step?

2019-09-03 14:45 UTC, LukeLoze1 commented on acceptance_tests/features/steps/fulfilment_request.py
> +@step("a new Case Created is emitted")
good shout, bad lack of code re use, and we only wrote it 2 weeks ago! Can also improve the other step with an IndividualCaseId check

2019-09-04 06:44 UTC, liamtoozer commented on acceptance_tests/features/steps/fulfilment_request.py
> +def create_expected_individual_response_csv(context, fulfilment_code):
Function could maybe live in `print_file_helper.py` with the other similar ones?

2019-09-04 08:48 UTC, LukeLoze1 commented on acceptance_tests/features/steps/fulfilment_request.py
> +@step('an individual print fulfilment request "{fulfilment_code}" is received by RM')
I think at the moment they're all slightly around address and contact, I've tried previously to combine 2 of them and it didn't work nicely.  I think this would be a good refactor for someone with a bit of time

2019-09-04 13:28 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment_request.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
Could use a single `given` step here instead of the two
```feature
Given sample file "sample_1_english_unit.csv" is loaded successfully
```

2019-09-04 13:29 UTC, AdamHawtin reviewed
A suggestion for the feature but it's passing against the PR branches and the rest looks good 👍

2019-09-04 13:29 UTC, AdamHawtin approved these changes

2019-09-04 14:02 UTC, liamtoozer approved these changes
LGTM 👍

2019-09-05 07:43 UTC, merged