Action rules ignore hi case
ONSdigital/census-rm-acceptance-tests-2021 pull request #121
Opened 2019-09-02 14:40 UTC by rjweeks

# Motivation and Context
Household Individual cases should not be used for Action reminders.

# What has changed
HI cases are not used when an action rule is triggered.

# How to test?
Run Action scheduler Integration tests.
Build Action Scheduler locally and run acceptance tests against Docker Dev.

# Links
https://trello.com/c/ErIhvPIp/1069-action-rules-to-ignore-hi-cases-3
https://github.com/ONSdigital/census-rm-action-scheduler/pull/34

2019-09-02 14:41 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Action Rules to ignore HI cases (3)](https://trello.com/c/ErIhvPIp/1069-action-rules-to-ignore-hi-cases-3)

2019-09-03 08:06 UTC, AdeHarrison approved these changes
LGTM

2019-09-04 06:31 UTC, AdamHawtin requested changes

2019-09-04 06:31 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment_request.feature
> +    Then the action instruction messages are emitted to FWMT where the case has a treatment code of "HH_QF2R1E"
I think the `then` should explicitly say and test that the new HI cases are not emitted in the fieldwork reminder wave. Also not sure we need to test all of the `UACIT` fulfilment codes for this since we're not actually testing the `UACIT` request outputs but just utilising it as a mechanism to create individual cases?

2019-09-04 06:36 UTC, AdamHawtin requested changes

2019-09-04 06:36 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment_request.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
There is a single step that can replace these two givens to make it read a bit easier: 
```feature
Given sample file "sample_individual_case_spec.csv" is loaded successfully
```

2019-09-05 15:04 UTC, rjweeks commented on acceptance_tests/features/fulfilment_request.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
Done

2019-09-06 14:19 UTC, AdamHawtin approved these changes
👍

2019-09-06 14:24 UTC, merged