Date utils
ONSdigital/census-rm-acceptance-tests-2021 pull request #13
Opened 2019-02-11 11:29 UTC by rjweeks

2019-02-11 13:46 UTC, hbrace requested changes

2019-02-11 13:46 UTC, hbrace commented on utilities/date_utils.py
> +def get_timestamp:
Does this need pair of brackets at the end of get_timestamp? - get_timestamp()

2019-02-11 14:51 UTC, rjweeks commented on utilities/date_utils.py
> +def get_timestamp:
Added.

2019-02-11 15:03 UTC, hbrace approved these changes

2019-02-11 16:14 UTC, LukeLoze1 approved these changes

2019-02-11 16:14 UTC, merged

2019-02-12 13:15 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automated testing](https://trello.com/c/PUT3GUaJ/438-automated-testing)