Ccs property listed
ONSdigital/census-rm-acceptance-tests-2021 pull request #134
Opened 2019-10-03 12:08 UTC by AdeHarrison

# Motivation and Context

To handle new CCS_ADDRESS_LISTED event for cases created during the address collection phase

# What has changed
Added new queue binding and queue for CCSPropertyListed Event

# How to test?
[as per](https://github.com/ONSdigital/census-rm-case-processor/pull/69)

# Links

[Trello](https://trello.com/c/Agjp8R9R/971-rmc-1661-implement-ccs-property-listed-event-no-additional-marker-present-13)
# Screenshots (if appropriate):

2019-10-03 12:12 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-166.1 Implement CCS Property Listed Event (no additional marker present) (13)](https://trello.com/c/Agjp8R9R/971-rmc-1661-implement-ccs-property-listed-event-no-additional-marker-present-13)

2019-10-03 13:06 UTC, AdamHawtin requested changes

2019-10-03 13:06 UTC, AdamHawtin commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                }
I don't think the test message should include all of these, they are mutually exclusive events and case-processor will end up with different logical routes for messages container any one of these soon with the next round of CCS stories.

2019-10-03 13:08 UTC, AdamHawtin submitted a review, later dismissed
Sample file included does not appear to be used?

2019-10-03 13:17 UTC, NickGrantONS commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                    "addressType": "NR",
I don't think we should use a non-residential case as the example for this "minimum viable product" plain vanilla test cases

2019-10-03 13:18 UTC, NickGrantONS commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                "refusal": {
Don't include a refusal - this is just a basic scenario we're testing

2019-10-03 13:18 UTC, NickGrantONS commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                "invalidAddress": {
Don't include an invalid address - this is just a basic scenario we're testing

2019-10-03 13:18 UTC, NickGrantONS commented on acceptance_tests/features/steps/ccs_property_listed.py
> +    assert context.ccs_case['caseType'] == 'NR'  # caseType is derived from addressType for CCS
we should just deal with standard households for now

2019-10-03 13:20 UTC, NickGrantX requested changes
why has a girt big sample file been added as part of this PR? There's no sample needed.

See other comments too.

2019-10-03 13:39 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                    "addressType": "NR",
done

2019-10-03 13:39 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                }
done

2019-10-03 13:39 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                "refusal": {
done

2019-10-03 13:39 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                "invalidAddress": {
done

2019-10-03 13:39 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +    assert context.ccs_case['caseType'] == 'NR'  # caseType is derived from addressType for CCS
done

2019-10-03 13:40 UTC, AdeHarrison commented
> why has a girt big sample file been added as part of this PR? There's no sample needed.
> 
> See other comments too.

no idea, looks like committed by mistake, deleted

2019-10-04 08:52 UTC, ryangrundy7 commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                    "estabType": "Non-residential",
Need to change this to Household as well to keep it consistent

2019-10-04 09:36 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +                    "estabType": "Non-residential",
done

2019-10-04 10:16 UTC, ryangrundy7 approved these changes
LGTM 👍

2019-10-04 10:20 UTC, NickGrantX approved these changes
ATs passing. LGTM 👍

2019-10-04 11:06 UTC, gavinleeedwards approved these changes
Looks good  and all passes 👍

2019-10-04 12:03 UTC, merged