Add QID lookup step to CCS property listed scenario
ONSdigital/census-rm-acceptance-tests-2021 pull request #135
Opened 2019-10-04 13:24 UTC by AdamHawtin

# Motivation and Context
Case API has a new endpoint to return the CCS QID for a CCS case created by a CCS property listed event.

# What has changed
* Add QID lookup step to CCS property listed scenario
* Replace some bare asserts with test helper method asserts for better logging

# How to test?
Build and run with the linked case-api branch

# Links
https://trello.com/c/T1k3bNPn/1121-implement-field-ccs-eq-launch-5
https://github.com/ONSdigital/census-rm-case-api/pull/33

2019-10-04 13:24 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Field CCS EQ launch (5)](https://trello.com/c/T1k3bNPn/1121-implement-field-ccs-eq-launch-5)

2019-10-07 08:36 UTC, ryangrundy7 approved these changes
Works with your other branch 👍

2019-10-07 08:37 UTC, LukeLoze1 requested changes
Just a comment on an assert failed msg

2019-10-07 08:37 UTC, LukeLoze1 commented on acceptance_tests/features/steps/case_look_up.py
> +    test_helper.assertEqual(response.status_code, 404, 'Unexpected case returned')
petty but it took me a while to understand this 'Unexpected case returned'.   Could this be changed to something like  'case returned when none expected'.   'Unexpected case' reads a bit like 'wrong case returned'

2019-10-07 10:20 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_look_up.py
> +    test_helper.assertEqual(response.status_code, 404, 'Unexpected case returned')
Fair point, I only started editing it because 'Case returned' would have confused me as a failure message so best make it as clear as possible.

2019-10-07 11:56 UTC, LukeLoze1 approved these changes

2019-10-07 14:56 UTC, merged