1099 rmc 1663 handle qid linking ccs
ONSdigital/census-rm-acceptance-tests-2021 pull request #137
Opened 2019-10-07 06:34 UTC by LukeLoze1

# Motivation and Context
https://trello.com/c/KNsTMSMf/1099-rmc-1663-handle-qid-linking-in-ccspropertylisted-event-5

# What has changed
New test to check if passing a qid with the a CCSCaseListed results in no msg being sent to fwmt

# How to test?
Install https://github.com/ONSdigital/census-rm-case-processor/tree/1099-css-with-qid then run the tests

# Links
https://trello.com/c/KNsTMSMf/1099-rmc-1663-handle-qid-linking-in-ccspropertylisted-event-5

# Screenshots (if appropriate):

2019-10-07 08:57 UTC, AdeHarrison reviewed
return of mysterious unused sample_file.csv file

2019-10-07 09:22 UTC, AdeHarrison commented on acceptance_tests/features/steps/ccs_property_listed.py
> +        }
loads of duplicate code and will only get worse, make this a common method adding the props we want for each test?

2019-10-07 09:23 UTC, AdeHarrison commented on acceptance_tests/features/ccs_property_listed.feature
> +    Then the CCS Property Listed case is created
is this an "and"?

2019-10-08 07:29 UTC, AdeHarrison approved these changes

2019-10-08 11:37 UTC, AdamHawtin requested changes
Stray 59000 line sample file included?

2019-10-08 11:39 UTC, AdamHawtin submitted a review, later dismissed

2019-10-08 11:39 UTC, AdamHawtin commented on acceptance_tests/features/ccs_property_listed.feature
> +    When an unaddressed message of questionnaire type 71 is sent
```suggestion
    Given an unaddressed message of questionnaire type 71 is sent
```

2019-10-08 11:39 UTC, AdamHawtin commented on acceptance_tests/features/ccs_property_listed.feature
> +    And the CCS Property Listed case is created
```suggestion
    Then the CCS Property Listed case is created
```

2019-10-08 13:16 UTC, LukeLoze1 commented
> Stray 59000 line sample file included?

I'm guessing this was on a previous branch somewhere, will get it out

2019-10-08 14:50 UTC, ryangrundy7 approved these changes
All tests pass 👍

2019-10-08 14:52 UTC, merged