ccs with refusal acceptance test
ONSdigital/census-rm-acceptance-tests-2021 pull request #139
Opened 2019-10-09 11:00 UTC by AdeHarrison

# Motivation and Context
Test ccsPropertyListed event received with Refusal outcome

# What has changed

# How to test?
[as per](https://github.com/ONSdigital/census-rm-case-processor/pull/72)

# Links
[Trello](https://trello.com/c/DGGOf9tf/1101-rmc-1664-handle-a-refusal-in-a-ccspropertylisted-event-5)

# Screenshots (if appropriate):

2019-10-09 11:59 UTC, LukeLoze1 requested changes

2019-10-09 11:59 UTC, LukeLoze1 commented on acceptance_tests/features/steps/ccs_property_listed.py
> +@step('a CCS Property Listed event is sent with an address invalid event and addressType "{address_type}"')
remove this for now

2019-10-09 11:59 UTC, LukeLoze1 commented on acceptance_tests/features/ccs_property_listed.feature
> +    And the CCS case listed event is logged
Can we also check that a new qid is set against the case, or could add this in the next ticket

2019-10-10 06:40 UTC, LukeLoze1 approved these changes

2019-10-10 06:40 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-166.4 Handle a refusal in a CCSPropertyListed event (5)](https://trello.com/c/DGGOf9tf/1101-rmc-1664-handle-a-refusal-in-a-ccspropertylisted-event-5)

2019-10-10 08:00 UTC, hbrace approved these changes

2019-10-10 08:13 UTC, merged