New fields on case api
ONSdigital/census-rm-acceptance-tests-2021 pull request #141
Opened 2019-10-16 14:18 UTC by hbrace

# Motivation and Context

Two extra fields need to be returned from case-api, collectionExerciseId and surveyType(inferred from ccs_case boolean).

# What has changed

Tests added to check what fields are returned depending on case survey type (CCS or CENSUS).

# How to test?

Run alongside the case-api branch of the [same name](https://github.com/ONSdigital/census-rm-case-api/pull/36).

# Links

https://trello.com/c/BGuOGSeR/1263-new-fields-on-case-api-5

# Screenshots (if appropriate):

2019-10-16 14:19 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [New fields on case api (5)](https://trello.com/c/BGuOGSeR/1263-new-fields-on-case-api-5)

2019-10-18 08:19 UTC, LukeLoze1 requested changes
Just a couple of minor changes requested

2019-10-18 08:19 UTC, LukeLoze1 commented on acceptance_tests/features/steps/case_look_up.py
> +    context.response = response.json()
context.response variable name could be better named
Also it would feel nicer to set this variable after the status_code == 200 check.

2019-10-18 08:59 UTC, LukeLoze1 approved these changes

2019-10-18 11:06 UTC, AdeHarrison approved these changes

2019-10-18 11:07 UTC, merged