Add test to check bad messages are placed on redelivery queue
ONSdigital/census-rm-acceptance-tests-2021 pull request #144
Opened 2019-11-21 15:07 UTC by hbrace

# Motivation and Context

A test has been added to check that bad messages are placed on the redelivery queue.

# What has changed

Test added for redelivery queue.

# How to test?

Check this branch out and run it.

# Links

https://trello.com/c/L8zrPipS/316-automate-testing-of-rabbit-redelivery-dead-letter-exchange-8

# Screenshots (if appropriate):

2019-11-21 15:09 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [automate testing of Rabbit redelivery dead letter exchange (8)](https://trello.com/c/L8zrPipS/316-automate-testing-of-rabbit-redelivery-dead-letter-exchange-8)

2019-11-22 14:19 UTC, liamtoozer commented on config.py
> +    RABBITMQ_QUEUES = ['Action.Field',
Don't think we consume from this queue. Should this be `Action.Printer` for the print file service instead?

2019-11-22 16:45 UTC, NickGrantONS commented on acceptance_tests/features/steps/bad_message.py
> +    purge_queues(*Config.RABBITMQ_QUEUES, 'delayedRedeliveryQueue', 'RM.Field')
this won't purge any messages which are in their 3-second retry 'window' so the test might be flakey. Could be worth doing this purge a few times over the course of a few seconds?

2019-11-22 16:47 UTC, NickGrantONS commented on acceptance_tests/features/steps/bad_message.py
> +                "randomNumber": random.randint(1, 1000)
could use a UUID to be more certain that there's no accidental flukey collisions

2019-11-22 16:49 UTC, NickGrantONS commented on config.py
> +    RABBITMQ_QUEUES = ['Action.Field',
I think we DO consumer from this queue. We turn Action.Field JSON messages into XML, which we publish on to the RM.Field queue

2019-11-22 16:50 UTC, NickGrantX requested changes
Few comments but looks like great work

2019-11-22 18:19 UTC, liamtoozer commented on config.py
> +    RABBITMQ_QUEUES = ['Action.Field',
Ahhh forgot about that. Ignore me!

2019-11-25 09:06 UTC, hbrace commented on acceptance_tests/features/steps/bad_message.py
> +    purge_queues(*Config.RABBITMQ_QUEUES, 'delayedRedeliveryQueue', 'RM.Field')
Loop to purge added

2019-11-25 09:06 UTC, hbrace commented on acceptance_tests/features/steps/bad_message.py
> +                "randomNumber": random.randint(1, 1000)
Random number replaced with a UUID 👍

2019-11-25 09:57 UTC, NickGrantX approved these changes
Looks good to me. Tested and it works nicely!

2019-11-25 09:59 UTC, AdamHawtin requested changes

2019-11-25 09:59 UTC, AdamHawtin commented on acceptance_tests/features/bad_message.feature
> +    Then the hash of the bad message is seen multiple times
Maybe phrase this to mention the exception manager explicitly e.g.
```behave
Then  each bad messages is seen multiple times by the exception manager
```

2019-11-25 09:59 UTC, AdamHawtin commented on acceptance_tests/features/bad_message.feature
> +    And queues are free of messages
This feels like something that should be in before or after hooks, it's not actually testing the queues are empty but purging them itself.

2019-11-25 15:00 UTC, AdamHawtin approved these changes

2019-11-25 15:00 UTC, AdamHawtin commented on acceptance_tests/features/environment.py
> +def __clear_queues_for_bad_messages():
We normally only use single underscore names to indicate privacy, not doubles.

2019-11-25 15:00 UTC, AdamHawtin commented on acceptance_tests/features/environment.py
> +    requests.get(f'{Config.EXCEPTION_MANAGER_URL}/reset')
Pedantic about naming, but I think the function name should mention reseting the exception manager or it should be done elsewhere (not a fan of unspecified side effects)

2019-11-25 15:05 UTC, hbrace commented on acceptance_tests/features/environment.py
> +    requests.get(f'{Config.EXCEPTION_MANAGER_URL}/reset')
Function renamed to `_clear_queues_for_bad_messages_and_reset_exception_manager()`

2019-11-25 17:02 UTC, LukeLoze1 approved these changes

2019-11-26 07:41 UTC, merged