Rmc 173 blank questionnaire returned
ONSdigital/census-rm-acceptance-tests-2021 pull request #150
Opened 2019-12-13 14:47 UTC by ryangrundy7

# Motivation and Context
Tests for handling Blank Questionnaires
# What has changed
- Added tests for blank questionnaires
# How to test?
- Run ATs with other prs on trello ticket

# Links
[Trello](https://trello.com/c/EmrziSj3)

2019-12-13 14:50 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-173 Blank Questionnaire Returned (8)](https://trello.com/c/EmrziSj3/439-rmc-173-blank-questionnaire-returned-8)

2019-12-16 11:25 UTC, AdamHawtin requested changes

2019-12-16 11:25 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And an unreceipted ActionRequest event is sent to field work management
These seem like `Thens` rather than `Whens`

2019-12-16 11:25 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +  Scenario: PQRS and QM blank questionnaire
Scenario description could be a bit more detailed given how big the test is

2019-12-16 11:25 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
Could use the all in one sample load step?

2019-12-16 11:25 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
Could use the all in one sample load step?

2019-12-16 11:25 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And a unreceipted UAC updated message is emitted
I don't think an `unreceipted` message should be emitted at this point?

2019-12-16 11:25 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And the offline receipt msg for a unreceipted case is put on the GCP pubsub
I don't agree with the wording here, I think it should specify that it's a blank questionnaire receipt and the case is not unreceipted, since we posted in a valid receipt for it above.

2019-12-16 14:35 UTC, AdamHawtin approved these changes
👍

2019-12-16 16:18 UTC, NickGrantX requested changes
We should probably test the scenario QM unreceipt the case first, followed by there being an offline receipt, due to messages being processed in the wrong order

2020-02-10 12:17 UTC, AdamHawtin commented
Should be closed? We've moved the ticket back.

2020-02-13 09:53 UTC, ryangrundy7 commented
PR out of date and gone back into analysis

2020-02-13 09:53 UTC, closed without merging