check CE fields emitted correctly
ONSdigital/census-rm-acceptance-tests-2021 pull request #153
Opened 2020-01-13 15:13 UTC by LukeLoze1

# Motivation and Context
Check ce1Complete is set, as was coming through as null sometimes

# What has changed
Now tests for ce1Complete

# How to test?
Run with master except the new fieldworkAdapter branch: https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/25

# Links
https://trello.com/c/gIGqWwlV/493-fixes-to-ce

2020-01-13 15:30 UTC, AdamHawtin requested changes
Just a grammar comment

2020-01-13 15:30 UTC, AdamHawtin commented on acceptance_tests/features/field_reminder.feature
> +    Then action instruction emitted to FWMT where case has a "caseType" of "CE" and CEComplete is "false"
Don't think you should remove the 'the', scenarios are supposed to be full sentences.

2020-01-13 17:16 UTC, LukeLoze1 commented on acceptance_tests/features/field_reminder.feature
> +    Then action instruction emitted to FWMT where case has a "caseType" of "CE" and CEComplete is "false"
Fair enough, I removed it when I was trying to shorten a longer version (>80), doesn't apply any more

2020-01-14 08:31 UTC, AdamHawtin requested changes
I'm getting a failure in an unrelated test due to the test code changes:
```python
  Scenario: Generate individual cases and check that no actions rules are triggered for them                                          # acceptance_tests/features/fulfilment_request.feature:84
    Given sample file "sample_individual_case_spec.csv" is loaded successfully                                                        # acceptance_tests/features/steps/sample.py:26 0.087s
    And an action rule of type "FIELD" is set 5 seconds in the future                                                                 # acceptance_tests/features/steps/action_rules.py:9 0.092s
    When a UAC fulfilment request "UACIT1" message for a created case is sent                                                         # acceptance_tests/features/steps/fulfilment_request.py:67 0.028s
    Then the action instruction messages for only the HH case are emitted to FWMT where the case has a "treatmentCode" of "HH_QF2R1E" # acceptance_tests/features/steps/field_reminder.py:11 0.000s
      Traceback (most recent call last):
        File "/Users/adamhawtin/.local/share/virtualenvs/census-rm-acceptance-tests-k93M4obU/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/adamhawtin/.local/share/virtualenvs/census-rm-acceptance-tests-k93M4obU/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
      TypeError: fwmt_messages_received() got an unexpected keyword argument 'treatment_code'
```

2020-01-14 09:35 UTC, LeoKHoward commented on acceptance_tests/features/field_reminder.feature
> +    Then action instruction emitted to FWMT where case has a "caseType" of "CE" and CEComplete is "false"
My only observation was grammatical too...

Including Adam's suggestion above, would it make more sense to say "Then THE action instruction IS emitted to FWMT..."

2020-01-14 13:42 UTC, LeoKHoward approved these changes

2020-01-14 13:44 UTC, AdamHawtin approved these changes

2020-01-14 13:55 UTC, merged