RMC-335 Telephone Capture HI
ONSdigital/census-rm-acceptance-tests-2021 pull request #156
Opened 2020-01-16 15:04 UTC by AdamHawtin

# Motivation and Context
Respondents should be able to request individual telephone capture which spawns a new HI case and telephone capture UAC/QID pair.

# What has changed
* Add scenarios for household individual telephone capture request 
* Factor reusable event code into event_helper utility

# How to test?
Build and run linked feature branches, run these tests

# Links
https://trello.com/c/UJpW7I1J/484-rmc-335-telephone-capture-hi-13

2020-01-16 15:08 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-335 Telephone Capture: HI (13)](https://trello.com/c/UJpW7I1J/484-rmc-335-telephone-capture-hi-13)

2020-01-17 09:32 UTC, liamtoozer approved these changes
LGTM 👍 Tested locally and passed

2020-01-17 09:59 UTC, LukeLoze1 requested changes
query around checking response 200 vs raise for status

2020-01-17 09:59 UTC, LukeLoze1 commented on acceptance_tests/features/steps/telephone_capture.py
> +    test_helper.assertEqual(response.status_code, 200)
should it use response.raise_for_status() here?  we've tended to use that in other api checks.

2020-01-17 10:34 UTC, LukeLoze1 approved these changes

2020-01-17 10:39 UTC, merged