Ensure Action Cancel is not sent to Field from continuation questionnaire receipts
ONSdigital/census-rm-acceptance-tests-2021 pull request #159
Opened 2020-01-20 07:13 UTC by liamtoozer

# Motivation and Context

When we receive a PQRS receipt for a continuation form we need ensure that fieldwork are not sent an Action Cancel instruction from this so that follow-ups can continue until the main form is receipted. 

# What has changed

* Added two new tests for continuation receipts from an unaddressed scenario and from a fulfilment request scenario

# How to test?

Checkout the fieldwork-adaptor PR from link below and run these tests to ensure no Action Instruction messages are sent to field from these tests.

# Links

https://trello.com/c/cvCv6U1R/499-do-not-send-a-cancel-message-when-a-continuation-form-is-completed-3

2020-01-20 07:44 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Do not send a cancel message when a continuation form is completed (3)](https://trello.com/c/cvCv6U1R/499-do-not-send-a-cancel-message-when-a-continuation-form-is-completed-3)

2020-01-20 08:43 UTC, AdamHawtin requested changes

2020-01-20 08:43 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
You can use a single step for this (been meaning to replace all older scenarios at some point).
`Given sample file "sample_for_receipting.csv" is loaded successfully`

2020-01-20 08:43 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    When the receipt msg for the created case is put on the GCP pubsub
👍 for specificity

2020-01-20 08:43 UTC, AdamHawtin commented on acceptance_tests/features/ccs_property_listed.feature
> +    Then no ActionInstruction is sent to FWMT
Feels like this another receipting scenario rather than CCS specific? (could live in the receipting feature)

2020-01-20 08:43 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +    check_if_event_list_is_exact_match(expected_event_list, context.emitted_case['id'])
I think this should live in event_log.py instead of receipt.py.

2020-01-20 09:30 UTC, liamtoozer commented on acceptance_tests/features/receipt.feature
> +    And messages are emitted to RH and Action Scheduler with [01] questionnaire types
Good shout, didn't know this was a thing!

2020-01-20 12:20 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And the events logged for the case are [SAMPLE_LOADED,RESPONSE_RECEIVED]
I like the step specifying it's the receipted case, you could maybe just add this step string onto the same step function to reuse the same code but keep the specific wording?

2020-01-20 12:24 UTC, liamtoozer commented on acceptance_tests/features/receipt.feature
> +    And the events logged for the case are [SAMPLE_LOADED,RESPONSE_RECEIVED]
Yeah good idea, makes it easier to follow when looking at this scenario as well 👍

2020-01-20 12:56 UTC, AdamHawtin commented on acceptance_tests/features/undelivered.feature
> +    And the events logged for the case are [SAMPLE_LOADED,UNDELIVERED_MAIL_REPORTED]
I think you can revert this now?

2020-01-20 13:49 UTC, NickGrantX approved these changes
ATs passing for me. Looks good 👍

2020-01-20 15:01 UTC, gavinleeedwards reviewed
Everything passes.  Just 1 small comment 👍

2020-01-20 15:01 UTC, gavinleeedwards commented on acceptance_tests/features/steps/unaddressed.py
> +@step("the offline receipt msg for a continuation form from the case is received")
Is this specific to unaddressed or is it more generic? This doesn't feel like the right place for it

2020-01-21 11:59 UTC, liamtoozer commented on acceptance_tests/features/steps/unaddressed.py
> +@step("the offline receipt msg for a continuation form from the case is received")
This function originally lived in `unaddressed.py` but agreed it should be moved to `receipt.py` to couple with domain concept (receipting) instead

2020-01-21 13:11 UTC, gavinleeedwards approved these changes

2020-01-21 13:30 UTC, AdamHawtin approved these changes

2020-01-21 13:39 UTC, merged