Reuse sample loaded successfully step in features
ONSdigital/census-rm-acceptance-tests-2021 pull request #161
Opened 2020-01-20 11:52 UTC by liamtoozer

# Motivation and Context

A [PR comment](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/159#discussion_r368419841) was raised to point out that a consolidated `sample load successful` step can be reused to check the necessary `CASE_CREATED` and `UAC_UPDATED` events are emitted correctly. 

This same step can be reused in a few different features where we don't need to know about the questionnaire type in the emitted messages. This should help condense some of our features to be less wordy as well.

# What has changed

Updated various features to reuse the 'sample loaded successfully' step

# How to test?

Ensure the tests pass as expected

# Links

https://trello.com/c/lRUqvoW8/516-acceptance-tests-reuse-sample-load-success-step

2020-01-20 11:53 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Acceptance Tests: Reuse sample load success step (1?)](https://trello.com/c/lRUqvoW8/516-acceptance-tests-reuse-sample-load-success-step-1)

2020-01-20 15:12 UTC, NickGrantX approved these changes
ATs pass. Nice refactoring - very neat! 👍

2020-01-21 14:56 UTC, AdamHawtin requested changes

2020-01-21 14:56 UTC, AdamHawtin commented on acceptance_tests/features/unaddressed.feature
> +    When a receipt for the unlinked UAC-QID pair is received
I think `When, Then, And, And` actually made more sense for this scenario, it doesn't need a `Given` set up, the action is `an unaddressed message of questionnaire type 01 is sent` and the following 3 steps are all expected results.

2020-01-21 15:39 UTC, AdamHawtin approved these changes
👍

2020-01-21 15:40 UTC, merged