Batch Fulfilment Print Jobs
ONSdigital/census-rm-acceptance-tests-2021 pull request #162
Opened 2020-01-20 15:16 UTC by LeoKHoward

# Motivation and Context
Sending Fulfilment Print Jobs as one batch at 4pm daily so that they can be managed more easily

# What has changed
Added test to create two print files from new sample file in repo and check that these are logged

# How to test?
Clone along with Action Worker, Action Scheduler and DDL repos in branch, make up docker and run make test

# Links
https://trello.com/c/W75HPE9U

2020-01-20 15:23 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-227 Batch Fulfilment Print Jobs (13)](https://trello.com/c/W75HPE9U/140-rmc-227-batch-fulfilment-print-jobs-13)

2020-01-21 15:17 UTC, gavinleeedwards requested changes

2020-01-21 15:17 UTC, gavinleeedwards commented on acceptance_tests/features/fulfilment_request.feature
> +    Then two UAC updated messages with "<questionnaire type>" questionnaire type are emitted
No biggie but could this step be made more clearer? The `when` mentions 'multiple' fulfilment requests but the `then` specifically mentions 2 so it's confusing to see where the 'two' comes from.

2020-01-23 15:03 UTC, NickGrantX approved these changes
ATs passing for me. Looks good 👍

2020-01-27 13:13 UTC, gavinleeedwards approved these changes

2020-01-29 10:29 UTC, merged