Sample load acceptance test
ONSdigital/census-rm-acceptance-tests-2021 pull request #17
Opened 2019-02-20 14:21 UTC by liamtoozer

# Motivation and Context

The main purpose of this change is to allow future tests to be run independently of each other. 

# What has changed

* Unique string generation for independent tests
* Remove db teardown (keep teardown SQL for local dev)
* Refactor of existing tests
* Move steps to [domain concepts](https://docs.cucumber.io/guides/anti-patterns/#how-to-decouple-steps-step-definitions)
*  Confirms sample load success by sample unit ID retrieval from casesvc

# How to test?

**Note**: Currently only able to test locally
1. Checkout the branch from [this PR](https://github.com/ONSdigital/census-rm-docker-dev/pulls) and start containers.
2. `pipenv run behave acceptance_tests/features`

# Links
[Trello](https://trello.com/c/8Hq6ZFLV/494-sample-load-acceptance-test-8)

2019-02-20 14:22 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sample load acceptance test (8)](https://trello.com/c/8Hq6ZFLV/494-sample-load-acceptance-test-8)

2019-02-22 12:50 UTC, AdamHawtin requested changes
The test runs fine against local docker images, a few comments though.

Also the README needs updating.

2019-02-22 12:50 UTC, AdamHawtin commented on acceptance_tests/features/load_samples_to_db.feature
>      Then a call to the casesvc api returns 10 cases
This 'Then' describes how its testing for the goal, not the actual goal of the test which is that the cases are created and persisted in the case service.

2019-02-22 12:50 UTC, AdamHawtin commented on utilities/date_utilities.py
> -import maya
Can the dependency for `maya` be removed now?

2019-02-22 15:49 UTC, AdamHawtin commented on README.md
> +1. Clone `census-rm-docker-dev ` and run `make up` to start the required services
Could be a link to the repo?

2019-02-25 13:08 UTC, AdamHawtin commented on resources/database/database_reset_rm.sql
> -ALTER SEQUENCE actionexporter.contactpkseq RESTART WITH 1;
Why has this been deleted?

2019-02-25 13:29 UTC, AdeHarrison commented on resources/database/database_reset_rm.sql
> -ALTER SEQUENCE actionexporter.contactpkseq RESTART WITH 1;
Reinstated statements deleted in error

2019-02-25 14:39 UTC, LukeLoze1 requested changes

2019-02-25 14:39 UTC, LukeLoze1 commented on utilities/sample_loader/sample_file_loader.py
>  def load_sample_file(context):
stick RABBITMQ_SERVICE_HOST and other env variables in the config file along with these values

2019-02-25 15:32 UTC, AdamHawtin approved these changes

2019-02-26 09:59 UTC, AdamHawtin approved these changes

2019-02-27 08:41 UTC, LukeLoze1 approved these changes

2019-02-27 08:49 UTC, merged