Test telephone caputre SPG Unit level
ONSdigital/census-rm-acceptance-tests-2021 pull request #170
Opened 2020-01-31 19:48 UTC by LukeLoze1

# Motivation and Context

# What has changed
Test that SPG Unit level individual telephone requests results in new uac qid attached to main case

# How to test?
With case-api from ticket

# Links
https://trello.com/c/G23nV6a7/506-spg-individual-tel-capture-for-unit-case-5

2020-02-03 08:42 UTC, AdamHawtin requested changes

2020-02-03 08:42 UTC, AdamHawtin commented on acceptance_tests/features/telephone_capture.feature
> +    When there is a request for telephone capture for country "<country code>"
Wording of this step sounds odd to me it's for a case not a country, should mention request for _individual_ telephone capture.

2020-02-04 07:35 UTC, AdamHawtin commented on acceptance_tests/features/telephone_capture.feature
> +    When there is a request for individual telephone capture for and estab case
Typo and should be a non HH unit case?

2020-02-04 12:21 UTC, NickGrantX approved these changes
Yarp

2020-02-04 13:04 UTC, AdamHawtin approved these changes

2020-02-04 14:06 UTC, merged