Get rid of 'test' queues which weren't needed
ONSdigital/census-rm-acceptance-tests-2021 pull request #190
Opened 2020-02-19 13:04 UTC by NickGrantONS

# Motivation and Context
We were modifying the Rabbit queue config from the 'production-like' config, therefore invalidating our testing.

# What has changed
Used the proper queues instead of the invented ones which should not and now do not exist anywhere.

# How to test?
Run the acceptance tests.

# Links
Trello: https://trello.com/c/NG6W8Vzy

2020-02-19 13:05 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Strip out test queues from CI environment - not needed - and use real queues](https://trello.com/c/NG6W8Vzy/520-strip-out-test-queues-from-ci-environment-not-needed-and-use-real-queues)

2020-02-19 15:12 UTC, ryangrundy7 approved these changes

2020-02-20 07:24 UTC, AdamHawtin commented on config.py
> +    RABBITMQ_OUTBOUND_FIELD_QUEUE_TEST = 'RM.Field'
Should remove `_TEST` from these config names, that's how we were distinguishing test queues from normal ones.

2020-02-20 07:26 UTC, AdamHawtin requested changes
Looks fine apart from I think the config vars should be renamed to keep up with the changes.

Also perhaps a line in the README somewhere saying the tests won't work in any environment that has consumers on those queues

2020-02-20 09:12 UTC, NickGrantONS commented on config.py
> +    RABBITMQ_OUTBOUND_FIELD_QUEUE_TEST = 'RM.Field'
ugh. I guess so <sigh>

2020-02-20 09:17 UTC, NickGrantONS commented
> Looks fine apart from I think the config vars should be renamed to keep up with the changes.
> 
> Also perhaps a line in the README somewhere saying the tests won't work in any environment that

The tests would never have worked anywhere except CI and local machines, because they purged normal queues anyway

2020-02-20 10:11 UTC, AdamHawtin approved these changes

2020-02-20 15:48 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-317 Make Hand Delivery flag in outbound field messages dynamic based on treatment code (8)](https://trello.com/c/esdStYzJ/514-rmc-317-make-hand-delivery-flag-in-outbound-field-messages-dynamic-based-on-treatment-code-8)

2020-02-21 09:53 UTC, merged