573 ce and spg receipting mark case as receipted
ONSdigital/census-rm-acceptance-tests-2021 pull request #193
Opened 2020-02-21 16:26 UTC by LukeLoze1

# Motivation and Context
Test receipting logic as per table.  

# What has changed
A new test has been written as a large table closely mirror the required business logic.
Some Receipting tests have been removed as they're covered by the new test.
A reasonable amount of refactoring within receipt.py to remove unused code 

# How to test?
With the case processor from the same ticket installed run the tests, they should all pass.

# Links
https://trello.com/b/yarvSxGu/census-2021-response-management
# Screenshots (if appropriate):

2020-02-24 11:07 UTC, NickGrantONS commented on acceptance_tests/features/receipt.feature
> +      | CE        | U             | Ind      | True      | AR >= E | CLOSE       | sample_1_english_CE_unit.csv  | E       | RESPONSE_RECEIVED,RM_UAC_CREATED,FULFILMENT_REQUESTED,SAMPLE_LOADED
This is the greatest test I've ever seen

2020-02-24 11:08 UTC, NickGrantX approved these changes
Brilliant to see an acceptance test mirror the business requirements table so perfectly. A really great example of how we should have end-to-end traceability of business requirements.

2020-02-24 13:26 UTC, AdamHawtin requested changes

2020-02-24 13:26 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And if "<instruction>" not NONE a msg to field is emitted where ceActualResponse is "<increment>" with action instruction
I think these two steps should match the terminology on the events e.g. 
`Then if the "<field decision>" is not null, a case updated event with actual responses is "<increment>" and receipted "<receipt>" for case type "<case type>"`

2020-02-25 09:56 UTC, AdamHawtin approved these changes

2020-02-25 10:23 UTC, merged