add real action instructions to receipting tests
ONSdigital/census-rm-acceptance-tests-2021 pull request #202
Opened 2020-02-27 14:17 UTC by LukeLoze1

# Motivation and Context
Output FieldInstructions

# What has changed
Checks for correct field instructions for receipting

# How to test?
With case-processor and fieldwork-adapter from the ticket run the tests, they should pass

# Links
https://trello.com/b/yarvSxGu/census-2021-response-management

2020-02-28 13:26 UTC, AdamHawtin requested changes

2020-02-28 13:26 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And if the case is updated by an "<increment>" or by a "<receipt>" then there should be a case updated message of "<case type>"
This reads fine in the feature file but the values are substituted in in the logs so what you see logged in a test run is 
`And if the case is updated by an "False" or by a "True" then there should be a case updated message of "SPG"` 

Maybe something like 
` And if the actual response count is incremented (<increment>) or the case is marked receipted (<receipt>) then there should be a case updated message of case type "<case type>"` 
To keep the log output readable?

2020-02-28 13:34 UTC, LukeLoze1 commented on acceptance_tests/features/receipt.feature
> +    And if the case is updated by an "<increment>" or by a "<receipt>" then there should be a case updated message of "<case type>"
yeah could do,  wasn't sure either way as was also trying to keep lines a bit shorter, but I'll change it

2020-02-28 15:39 UTC, AdamHawtin approved these changes
👍

2020-03-02 13:00 UTC, AdamHawtin requested changes

2020-03-02 13:00 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
>        | SPG       | U             | Cont     | False     | False   | NONE        | sample_1_english_SPG_unit.csv | E       | RESPONSE_RECEIVED,RM_UAC_CREATED,PRINT_CASE_SELECTED,FULFILMENT_REQUESTED,
From this scenario, I can't work out why some of the examples expect `PRINT_CASE_SELECTED` or `FULFILMENT_REQUESTED` events against the case?

2020-03-02 13:04 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
>        | SPG       | U             | Cont     | False     | False   | NONE        | sample_1_english_SPG_unit.csv | E       | RESPONSE_RECEIVED,RM_UAC_CREATED,PRINT_CASE_SELECTED,FULFILMENT_REQUESTED,
Found it, those print or fulfilment requests are to generate the QID type required by that example row, makes sense.

2020-03-02 13:04 UTC, AdamHawtin approved these changes

2020-03-02 13:37 UTC, liamtoozer approved these changes
LGTM 👍

2020-03-02 14:20 UTC, merged