addressType and caseType confusion
ONSdigital/census-rm-acceptance-tests-2021 pull request #204
Opened 2020-03-03 14:32 UTC by LeoKHoward

# Motivation and Context
Case in case-api now has both caseType and addressType but we call the addressType "caseType" in the JSON messages we return so it can be confusing

# What has changed
Reference to caseType in ATs has been changed to addressType where applicable
Have also tried to standardise the term address type in the features as they have included address_type and addressType but relate to the same thing

# How to test?
Clone and build from case-api 
Run make test

# Links
https://trello.com/c/FlnWxlG2
https://collaborate2.ons.gov.uk/confluence/display/CATD/Case+API

2020-03-03 14:32 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sort out addressType/caseType confusion in Case API (3)](https://trello.com/c/FlnWxlG2/566-sort-out-addresstype-casetype-confusion-in-case-api-3)

2020-03-04 08:05 UTC, AdamHawtin requested changes

2020-03-04 08:05 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +      | SPG          | U             | Cont     | False     | False   | NONE        | sample_1_english_SPG_unit.csv | E       | RESPONSE_RECEIVED,RM_UAC_CREATED,PRINT_CASE_SELECTED,FULFILMENT_REQUEST
It's a subtle difference but I think this scenario should still refer to case type as in the code it implies it should be `HI` for household individual cases, which actually keep their parents `HH` address type, it is the case type which gets set to `HI`.

2020-03-04 09:19 UTC, AdamHawtin approved these changes

2020-03-04 09:34 UTC, hbrace approved these changes

2020-03-04 09:41 UTC, merged