Add CE Secure Marker
ONSdigital/census-rm-acceptance-tests-2021 pull request #210
Opened 2020-03-10 15:10 UTC by LeoKHoward

# Motivation and Context
New tests to handle new CE Secure column

# What has changed
Updated resource CSV files to include CE_SECURE column
3 scenarios to test different scenarios involving CE_SECURE

# How to test?
Clone and build all other repos on card
To test changes to census-rm-sample-loader, change Pipfile ref to branch number

# Links
https://collaborate2.ons.gov.uk/confluence/display/CRM/Address+Frame+specification+2021?focusedCommentId=36183836#comment-36183836
https://trello.com/c/BAI9qOOC/619-rmc-341-add-secure-marker-case-api-and-field-8

2020-03-10 16:03 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-341 Add secure marker - case api and field (8)](https://trello.com/c/BAI9qOOC/619-rmc-341-add-secure-marker-case-api-and-field-8)

2020-03-11 08:58 UTC, AdamHawtin commented on Pipfile
> +
Unnecessary whitespace? 🎨

2020-03-12 13:19 UTC, AdamHawtin submitted a review, later dismissed

2020-03-12 13:19 UTC, AdamHawtin commented on Pipfile
> +census-rm-sample-loader = {editable = true,git = "https://github.com/ONSdigital/census-rm-sample-loader",ref = "2d5a99ec752889498b2e87a9f261e31897e44fd9"}
This needs to be reverted to a version tag

2020-03-12 15:26 UTC, LukeLoze1 requested changes
Amend existing tests where possible to test new fields that don't exercise a lot of new business logic

2020-03-12 15:26 UTC, LukeLoze1 commented on acceptance_tests/features/secure_establishment.feature
> +Feature: Handle Secure Establishments
We do not need a new Feature for this, it's massive overkill.
If we want to test for it in the ATs, change some of the existing test_sample files to have secure set.
For example in existing:
     Scenario: send community estab cases to field
    Given sample file "sample_for_ce_stories.csv" is loaded successfully
    When a FIELD action rule for address type "CE" is set when loading queues are drained
    Then the action instruction is emitted to FWMT where case has a "caseType" of "CE" and CEComplete is "false"

 In the background this checks a lot of the ActionInstruction Fields, so a small change to def _message_valid(case, action_instruction) to check for this new Field will achieve the same in not a lot

This is also not testing any business logic apart from the successful conversion of a 0/1 to False/True

I'm sure something similar can been done for the Case API lookup, or have some faith in the epic CaseEndpointITs etc

2020-03-12 15:26 UTC, LukeLoze1 commented on acceptance_tests/features/steps/secure_establishment.py
> +import functools
Not needed

2020-03-12 15:26 UTC, LukeLoze1 commented on resources/sample_files/sample_for_ce_stories.csv
> +DDR190314000000195675,DDR190314000000113701,123456789123,CE,Prison,E,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E0
Why not make some of these 'secure'= 1

2020-03-13 07:24 UTC, LeoKHoward commented on resources/sample_files/sample_for_ce_stories.csv
> +DDR190314000000195675,DDR190314000000113701,123456789123,CE,Prison,E,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E0
It doesn't ultimately matter as we created a new file that has CE_SECURE as 1 and proved that it works. We could have made this file have CE_SECURE as true but the script that NG wrote automated adding a new column to each of the sample files in the repo and defaulted the value to 0/false and then I manually created sample_1_english_CE_Secure_estab.csv 

We could have made the CE_SECURE column in this file all 1/true but it would prove the same output as the ATs currently do

2020-03-13 07:30 UTC, LeoKHoward commented on acceptance_tests/features/secure_establishment.feature
> +Feature: Handle Secure Establishments
Please fight this out with @NickGrantONS 

I see where you are coming from and it shouldn't be the standard for when we introduce new columns but as NG said, there didn't feel like an existing feature for this to naturally be put into.

Will speak to NG today and discuss changing the resource file and adding these scenarios to the field_reminder.feature

2020-03-13 09:55 UTC, LeoKHoward commented on acceptance_tests/features/steps/secure_establishment.py
> +import functools
Just removed it and ran the tests and they failed because functools wasnt imported

2020-03-13 12:36 UTC, NickGrantONS commented on acceptance_tests/features/secure_establishment.feature
> +Feature: Handle Secure Establishments
maybe reminding the `field_reminder.feature` file and moving the scenarios out of the feature file that @LukeLoze1 detests so badly will placate him. I think the extra bits of python added are perfectly defensible - they are quite unique in what they're checking.

2020-03-13 12:37 UTC, NickGrantONS commented on acceptance_tests/features/steps/secure_establishment.py
> +import functools
functools used on line 39

2020-03-13 12:39 UTC, NickGrantONS commented on resources/sample_files/sample_for_ce_stories.csv
> +DDR190314000000195675,DDR190314000000113701,123456789123,CE,Prison,E,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E0
@LukeLoze1 because as leo said, it would add no value when the feature is already well tested

2020-03-13 12:40 UTC, NickGrantX approved these changes
LGTM - just a couple of minor tweaks to do before merging

2020-03-16 08:52 UTC, LeoKHoward commented on acceptance_tests/features/secure_establishment.feature
> +Feature: Handle Secure Establishments
Spoke to Adam and will keep the features separated and not combine with the ones in field_reminder (at least for now)

2020-03-17 09:25 UTC, LukeLoze1 approved these changes
grumble mumble, yet to be convinced of need for new tests

2020-03-17 12:25 UTC, merged