new acceptance test for a new address
ONSdigital/census-rm-acceptance-tests-2021 pull request #219
Opened 2020-03-25 10:33 UTC by hbrace

# Motivation and Context

Check to see if a case is created from a NEW_ADDRESS_REPORTED event.
# What has changed

A test has been added to send a new address event and then check case is created and events are logged.
# How to test?

Run tests with other PRs on the trello ticket.
# Links

https://trello.com/c/qixf5J2X/594-am1-part-1-new-address-reported-event-13
# Screenshots (if appropriate):

2020-03-25 10:34 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [AM1 part 1 - New Address Reported event (13)](https://trello.com/c/qixf5J2X/594-am1-part-1-new-address-reported-event-13)

2020-03-25 13:36 UTC, LukeLoze1 approved these changes

2020-03-27 09:43 UTC, NickGrantX requested changes
I think we need a test for creating a _skeleton_ case too.

2020-03-30 07:56 UTC, NickGrantONS commented on acceptance_tests/features/steps/address.py
> +    context.first_case = response.json()
I don't see anywhere that the actual values of the case are checked - they could be wrong

2020-03-30 07:58 UTC, NickGrantX requested changes
The acceptance test should check _some_ (ideally all) of the case fields, to make sure that the behaviour is correct and the data has been copied correctly.

2020-03-30 10:03 UTC, NickGrantX approved these changes
LGTM 👍

2020-03-30 11:01 UTC, merged