Ic03 ic04 generate ce estab individual addressed print files
ONSdigital/census-rm-acceptance-tests-2021 pull request #240
Opened 2020-04-28 10:47 UTC by ryangrundy7

# Motivation and Context

A test has been added for CE Estab initial contact Letters. CE Estab individual initial contact letters are different as they count all the expected responses and append rows to the printfile for them.
# What has changed

- Added a test for CE Estab initial contact Letters

# How to test?

- Run with other PRs on the ticket and run the tests, all tests should pass.

# Links

[Trello](https://trello.com/c/0WUGJq8e/)

2020-04-28 11:13 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(IC03/IC04) Generate CE ESTAB Individual Addressed Print Files (21)](https://trello.com/c/0WUGJq8e/471-ic03-ic04-generate-ce-estab-individual-addressed-print-files-21)

2020-04-28 12:51 UTC, NickGrantONS commented on resources/sample_files/sample_3_english_CE_estab.csv
> +123456789124,46488965929,CE,Prison,E,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E06000023,E12000009,1,5,CE_LFNR1E,
should we make the addresses a bit different, just to make the test data a bit more realistic?

2020-04-28 12:52 UTC, NickGrantONS commented on resources/sample_files/sample_3_welsh_CE_estab.csv
> +123456789125,79483231473,CE,Prison,E,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,W00073438,W01014540,W02003043,W06000023,W12000009,1,5,CE_LFNR1W,
could we make the addresses a bit different, just to make the test data a bit more realistic?

2020-04-28 12:52 UTC, NickGrantX requested changes
Minor comment

2020-04-28 15:29 UTC, NickGrantX approved these changes
LGTM 👍

2020-04-29 06:48 UTC, AdamHawtin commented on acceptance_tests/features/print_file.feature
> +    And expected number of uac events logged against the case are [PRINT_CASE_SELECTED,SAMPLE_LOADED]
Not sure about the wording of this step, what is a `uac event` and it says expected number but provides the actual list of events.

2020-04-29 06:48 UTC, AdamHawtin requested changes
Passes against the branches 👍 
Just a comment about step wording.

2020-04-29 07:32 UTC, ryangrundy7 commented on acceptance_tests/features/print_file.feature
> +    And expected number of uac events logged against the case are [PRINT_CASE_SELECTED,SAMPLE_LOADED]
Yeah it's a bit confusing, I'll try and reword it.

2020-04-29 11:43 UTC, AdamHawtin approved these changes
👍 Passed locally against the PR branches

2020-04-29 13:51 UTC, merged