Generate SPG Unit Addressed ICL Print Files
ONSdigital/census-rm-acceptance-tests-2021 pull request #242
Opened 2020-04-30 13:57 UTC by LeoKHoward

# Motivation and Context
Want to generate individual addressed initial contact letters for SPG Units

# What has changed
New ActionTypes/PackCodes/ActionRules included
New test for SPG Units
Change of PackCodes in sample files

# How to test?
Build other repos then run tests

# Links
https://trello.com/c/1gqkpqmf/809-ic11-ic12-generate-spg-addressed-icl-print-files-5

2020-04-30 13:57 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [(IC11/IC12) Generate SPG Addressed ICL Print Files (5)](https://trello.com/c/1gqkpqmf/809-ic11-ic12-generate-spg-addressed-icl-print-files-5)

2020-05-01 08:18 UTC, AdamHawtin approved these changes
👍 LGTM

2020-05-01 08:23 UTC, NickGrantONS commented on resources/sample_files/sample_1_english_SPG_unit.csv
> +123456789123,66484463076,SPG,Household,U,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E06000023,E12000009,1,5,SPG_LP
This sample file is used in 9 pre-existing tests. I'm nervous about changing the treatment code from questionnaire to letter, because it alters the meaning of the pre-existing tests.

2020-05-01 08:23 UTC, NickGrantONS commented on resources/sample_files/sample_1_welsh_SPG_unit.csv
> +123456789123,79182492330,SPG,Household,U,RD06,,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,W00073438,W01014540,W02003043,W06000023,W12000009,1,5,SPG_LP
This sample file is used in 9 pre-existing tests. I'm nervous about changing the treatment code from questionnaire to letter, because it alters the meaning of the pre-existing tests.

2020-05-01 08:24 UTC, NickGrantX requested changes
I don't think you should make significant changes to a sample file which is being used by other tests, presumably for different purposes

2020-05-01 09:25 UTC, NickGrantX approved these changes
After discussions, it's thought that the old treatment code was a "dummy" one, so this PR looks good.

2020-05-01 09:31 UTC, merged