IC09/IC10 Generate CE Estab Addressed PQs
ONSdigital/census-rm-acceptance-tests-2021 pull request #245
Opened 2020-05-06 12:32 UTC by LeoKHoward

# Motivation and Context
Want to generate individual addressed initial contact questionnaires for CE Estabs in English and Welsh

# What has changed
New ActionTypes/PackCodes/ActionRules included
New sample files
New scenario for running welsh PQ sample
Method to ensure case output includes both English and Welsh UAC/QID pairs on same row

# How to test?
Build other repos then run tests

# Links
https://trello.com/c/0JfdnR6q/795-ic09-ic10-generate-ce-ic-addressed-pqs-we-qids-required-13

2020-05-06 13:29 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [(IC09/IC10) Generate CE IC Addressed PQs: W&E QIDs required (13)](https://trello.com/c/0JfdnR6q/795-ic09-ic10-generate-ce-ic-addressed-pqs-we-qids-required-13)

2020-05-07 08:21 UTC, NickGrantONS commented on acceptance_tests/features/print_file.feature
> +    Examples: CE Estab Initial contact questionnaire: <pack code>
I don't think having a table of examples is suitable for this scenario, which is a very specific one. I don't see this being more than a single specific scenario

2020-05-07 08:23 UTC, NickGrantONS commented on acceptance_tests/features/steps/event_log.py
> +                new_type_list.append('RM_UAC_CREATED')
I don't understand why this would add a second `RM_UAC_CREATED` depending on a hard-coded treatment code. It's a bit of a code smell. There should at least be a comment explaining why this is doing something weird.

2020-05-07 08:29 UTC, NickGrantX requested changes
Couple of minor things

2020-05-07 08:36 UTC, AdamHawtin commented on acceptance_tests/features/steps/event_log.py
> +                new_type_list.append('RM_UAC_CREATED')
Agreed, this is the kind of thing that's probably worth writing a seperate step for so the wording can explicitely say something like `2 "RM_UAC_CREATED" events are logged per case`.

2020-05-07 08:43 UTC, AdamHawtin commented on acceptance_tests/features/steps/print_file.py
> +            if row.endswith(value['line_ending']):
I think this `line_ending` stuff needs some comments explaining it, I'm struggling to make sense of it. As far as I can tell, it's there to compare the chunk of the row that is common across all the lines generated for the same case, I think it either needs comments or naming to that effect.

2020-05-07 08:46 UTC, AdamHawtin requested changes
Works alright but I think it needs more explanation or self descriptive names to avoid becoming one of those things which we're scared to touch because we can't remember how or why it's here. Not saying I disagree with how it's coded, as far as I can tell the complexity is unavoidable for these awkward features.

2020-05-11 09:57 UTC, NickGrantX approved these changes
LGTM 👍

2020-05-11 10:20 UTC, AdamHawtin approved these changes

2020-05-11 10:21 UTC, merged