861 add uprn and estab uprn on all creates and updates to field
ONSdigital/census-rm-acceptance-tests-2021 pull request #246
Opened 2020-05-06 12:51 UTC by LukeLoze1

# Motivation and Context
estabUprn must also go to field

# What has changed
tests for it

# How to test?
with other apps from this ticket

# Links
https://trello.com/c/TbZ6Gp3S/861-add-uprn-and-estab-uprn-on-all-creates-and-updates-to-field-5
# Screenshots (if appropriate):

2020-05-06 14:16 UTC, NickGrantX requested changes
Could enhance the "undelivered mail" feature (for example) to check that estab uprn is going out when the case is updated... or some other way of making sure that both scenarios where we should be sending this data to Field are covered

2020-05-07 08:49 UTC, LukeLoze1 commented
> Could enhance the "undelivered mail" feature (for example) to check that estab uprn is going out when the case is updated... or some other way of making sure that both scenarios where we should be sending this data to Field are covered

Added to check that these are being set now in those tests

2020-05-07 11:17 UTC, ryangrundy7 approved these changes

2020-05-07 12:51 UTC, NickGrantX approved these changes
LGTM 👍

2020-05-07 13:16 UTC, merged