Smoke test wip files produced
ONSdigital/census-rm-acceptance-tests-2021 pull request #25
Opened 2019-03-08 12:28 UTC by LukeLoze1

# Motivation and Context
There wasn't a test to check that a correct notification file was actually created from creating a collex and uploading a file.
This has been added now along with some alterations to the sample-stub-svc to make the system produce files

# What has changed
New @smoketest with
New  step to check that files containing the expected data are produced and on the sftp server

# How to test?
get this branch and run 'make test'

# Notes:
The settings for getting this to work with k8s sftp aren't all complete yet as, waiting for advice

# Links
https://trello.com/c/fjQusTOt/530-smoke-test-for-sample-load-print-generation

2019-03-11 07:36 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [smoke test for sample load/print generation](https://trello.com/c/fjQusTOt/530-smoke-test-for-sample-load-print-generation)

2019-03-11 08:44 UTC, hbrace submitted a review, later dismissed

2019-03-11 08:44 UTC, hbrace commented on data_setup/collection_exercise_setup.py
> +    create_eq_collection_instrument  context.collection_exercise_id = _setup_collection_exercise_to_scheduled_state(context.survey_id, context.period,
I'm getting an invalid syntax error on this line. Is create_eq_collection_instrument meant to be there?

2019-03-11 08:57 UTC, jcox-dev commented on data_setup/collection_exercise_setup.py
> +    create_eq_collection_instrument  context.collection_exercise_id = _setup_collection_exercise_to_scheduled_state(context.survey_id, context.period,
A syntax error *should* be picked up by Travis CI. Can we make sure that flake8 or similar is run with PR checks?

2019-03-11 09:39 UTC, LukeLoze1 commented on data_setup/collection_exercise_setup.py
> +    create_eq_collection_instrument  context.collection_exercise_id = _setup_collection_exercise_to_scheduled_state(context.survey_id, context.period,
Have added in flake8 and package vulnerability checks to make and travis.  Then fixed a couple of flake issues

2019-03-11 11:13 UTC, hbrace approved these changes

2019-03-11 12:59 UTC, AdamHawtin reviewed
The test passes locally, got a couple of comments and questions.

2019-03-11 12:59 UTC, AdamHawtin commented on .travis.yml
> +  - make package_vulnerability
`pipenv check` is being run twice here with different max line length settings.

2019-03-11 12:59 UTC, AdamHawtin commented on acceptance_tests/features/load_samples_to_db.feature
> +@census
Is there a reason for a census tag?

2019-03-11 12:59 UTC, AdamHawtin commented on helpers/print_file_helper.py
> +from controllers.case_controller import get_cases_by_survey_id, get_1st_iac_for_case_id
What is the distinction between `helpers` and `utilities`?

2019-03-11 12:59 UTC, AdamHawtin commented on utilities/sftp_utility.py
> +        self.__sftp_client = self.ssh_client.open_sftp()
Why the double underscore variable name?

2019-03-11 13:53 UTC, LukeLoze1 commented on .travis.yml
> +  - make package_vulnerability
good catch.  I'll just call package_vulnerability, and set flake8 to 120

2019-03-11 13:55 UTC, LukeLoze1 commented on utilities/sftp_utility.py
> +        self.__sftp_client = self.ssh_client.open_sftp()
really, really private ;)

2019-03-11 15:58 UTC, AdamHawtin requested changes
Looks good and passes locally, I got it passing against my GCP project as well. It will fail most of the time in CI at the moment though, as the action exporter runs on a 15 minute file generation schedule. We'll need to either make that more frequent or allow much longer timeouts in the SFTP connection here.

2019-03-11 16:05 UTC, LukeLoze1 commented on acceptance_tests/features/load_samples_to_db.feature
> +@census
gone

2019-03-13 08:58 UTC, jcox-dev requested changes
Tests pass consistently and are obvious and useful. Couple of comments but mostly just name considerations.

2019-03-13 08:58 UTC, jcox-dev commented on acceptance_tests/features/smoking_tests.feature
> +@smoke_test
I'm not sure about the name of this feature file 🤔 

Perhaps `sample_file_smoke.feature` makes more sense?

2019-03-13 08:58 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    if len(files) == 0:
```suggestion
    if not files:
```

2019-03-13 08:58 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +        logger.info('Unable to find all iacs', files_found=file_names, expected_csv_lines=expected_csv_lines,
Should this read "all files"? It looks like we're looking for files not access codes.

2019-03-13 13:24 UTC, AdamHawtin commented on acceptance_tests/utilities/sftp_utility.py
> +        for _file in files:
I don't think there's a need to underscore variable names within a functions namespace.

2019-03-13 13:45 UTC, jcox-dev commented on acceptance_tests/utilities/sftp_utility.py
> +        for _file in files:
@AdamHawtin `file` is reserved in Python.

2019-03-13 17:09 UTC, LukeLoze1 commented on acceptance_tests/utilities/sftp_utility.py
> +        for _file in files:
jcox said it was a keyword, unless I got the wrong end of the stick

2019-03-14 10:09 UTC, jcox-dev approved these changes

2019-03-15 10:17 UTC, AdamHawtin requested changes
An issue in the concourse task, also waiting on https://github.com/ONSdigital/census-rm-kubernetes/pull/27

2019-03-15 10:17 UTC, AdamHawtin commented on tasks/kubectl-run-acceptance-tests.yml
> +      -- /bin/bash -c "sleep 2; behave acceptance_tests/features"
The first `-- /bin/bash -c "sleep 2; behave acceptance_tests/features"` line here will break this, it will run without the config underneath and error.

2019-03-15 11:06 UTC, AdamHawtin requested changes

2019-03-15 11:06 UTC, AdamHawtin commented on tasks/kubectl-run-acceptance-tests.yml
> -      --env=REDIS_SERVICE_PORT=$(kubectl get configmap redis-config -o=jsonpath="{.data.redis-port}" --namespace=${KUBERNETES_NAMESPACE}) \
This redis config still needs to be fetched here.

2019-03-15 13:47 UTC, LukeLoze1 commented on tasks/kubectl-run-acceptance-tests.yml
> -      --env=REDIS_SERVICE_PORT=$(kubectl get configmap redis-config -o=jsonpath="{.data.redis-port}" --namespace=${KUBERNETES_NAMESPACE}) \
doh

2019-03-15 13:53 UTC, AdamHawtin commented on kubernetes.env
> +REDIS_SERVICE_PORT=6379
This redis config won't work anymore and gets overwritten in the task.

2019-03-15 15:02 UTC, liamtoozer approved these changes
Looks good and test passes locally 👍 Just a couple of minor comments

2019-03-15 15:05 UTC, liamtoozer commented on acceptance_tests/utilities/print_file_helper.py
> +            sample_unit.update({'iac': iac})
Could `return` the update here to save looping through the rest?

2019-03-15 15:06 UTC, liamtoozer commented on acceptance_tests/features/steps/case_steps.py
> +    cases = get_cases_by_survey_id(context.survey_id, len(context.sample_units))
Would it be worth putting this into the `context` to avoid having to call the same end point again [here](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/25/files#diff-29e6f3b63376df0269e0c7fb7420c601R32)?

2019-03-18 08:52 UTC, LukeLoze1 commented on acceptance_tests/features/steps/case_steps.py
> +    cases = get_cases_by_survey_id(context.survey_id, len(context.sample_units))
We did consider that, I believe we were a bit worried about potential memory issues if there was  a lot of cases being copied in.

2019-03-18 09:14 UTC, LukeLoze1 commented on acceptance_tests/features/steps/case_steps.py
> +    cases = get_cases_by_survey_id(context.survey_id, len(context.sample_units))
We were worried if the number of cases grew too much that this could cause memory issues?

2019-03-18 09:15 UTC, AdamHawtin approved these changes

2019-03-18 09:46 UTC, merged