Test to check skeleton cases are excluded from action plans
ONSdigital/census-rm-acceptance-tests-2021 pull request #250
Opened 2020-05-13 13:56 UTC by hbrace

# Motivation and Context

We don't want skeleton cases to be included in action plans
# What has changed

Test added to load a small sample and create a skeleton case from a new address event. An action plan is run and the results are checked to ensure the skeleton case is not present.
# How to test?

Run with built [action scheduler branch of the same name](https://github.com/ONSdigital/census-rm-action-scheduler/pull/84).
# Links

https://trello.com/c/ThiV27TP/741-exclude-skeleton-cases-from-action-plans-3
# Screenshots (if appropriate):

2020-05-13 14:04 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exclude skeleton cases from action plans (3)](https://trello.com/c/ThiV27TP/741-exclude-skeleton-cases-from-action-plans-3)

2020-05-13 15:21 UTC, NickGrantX approved these changes
Nice way of doing it

2020-05-14 07:21 UTC, AdamHawtin requested changes

2020-05-14 07:21 UTC, AdamHawtin commented on acceptance_tests/features/steps/print_file.py
> +    test_helper.assertNotIn(context.case_created_events[0]['payload']['collectionCase']['caseRef'], actual_content_list)
I don't think this assertion is quite right, the `actual_content_list` contains entire print rows not just caserefs so this assertion would always pass even if the case ref was contained in one of those rows.

2020-05-14 07:43 UTC, AdamHawtin approved these changes

2020-05-14 07:45 UTC, merged