912 sort print files for hand delivery
ONSdigital/census-rm-acceptance-tests-2021 pull request #256
Opened 2020-05-19 07:08 UTC by LukeLoze1

Motivation and Context
Sort print files when pack codes for hand delivery

What has changed
When checking print files we take the actual print file rows and check that they're sorted as expected

How to test?
With printfilesvc from ticket

Links
https://trello.com/c/rZ6dszTh/912-sort-print-files-for-hand-delivery-13

2020-05-19 14:06 UTC, NickGrantONS commented on acceptance_tests/features/steps/print_file.py
> +        sorted_list = sorted(split_csv_rows, key=lambda row: (row[14], row[12]))
do you think these 'magic' numbers should be constants?

2020-05-19 14:06 UTC, NickGrantONS commented on acceptance_tests/features/steps/print_file.py
> +        sorted_list = sorted(split_csv_rows, key=lambda x: (x[15], x[14]))
do you think these 'magic' numbers should be constants?

2020-05-19 14:06 UTC, NickGrantONS commented on acceptance_tests/features/steps/print_file.py
> +        sorted_list = sorted(split_csv_rows, key=lambda x: (x[15], x[14]))
also, `x` is not a brilliant variable name

2020-05-19 14:10 UTC, NickGrantX requested changes
Might be nice to see sorting by both field office & org... I feel like there aren't enough rows with the same field officer to be sure that the org sorting is working.

2020-05-20 07:23 UTC, AdamHawtin requested changes

2020-05-20 07:23 UTC, AdamHawtin commented on acceptance_tests/features/steps/print_file.py
> +QM_PACKCODES_SORTED_BY_PRODUCTION_CODE = ['D_FDCE_I1', 'D_FDCE_I2', 'D_FDCE_I4', 'D_FDCE_H1', 'D_FDCE_H2']
The names `X_PACKCODES_SORTED_BY_PRODUCTION_CODE` threw me for a second, it sounds like it's a list of packcodes which has been sorted on production code. Maybe `X_PACKCODES_WHICH_ARE_SORTED` instead?

2020-05-20 08:16 UTC, LukeLoze1 commented on acceptance_tests/features/steps/print_file.py
> +        sorted_list = sorted(split_csv_rows, key=lambda x: (x[15], x[14]))
doh missed a row, literally

2020-05-20 11:45 UTC, AdamHawtin approved these changes

2020-05-20 11:45 UTC, NickGrantX approved these changes
LGTM 👍

2020-05-20 12:31 UTC, merged