Tag tests as regression for CI
ONSdigital/census-rm-acceptance-tests-2021 pull request #257
Opened 2020-05-19 13:42 UTC by hbrace

# Motivation and Context

Moving forward we want to add a lot more examples in the acceptance tests, e.g. all the fulfilment codes. These will, however, take a long time to run and don't necessarily need to be run on every merge, just need to be run ~once a day and whenever we manually trigger this larger suite of tests.
# What has changed

A majority of the print_file tests have been marked as `@regression` tests.
The concourse task that runs acceptance tests changed to exclude regression tests, and a new concourse task added to include these tests.
run_gke.sh updated to take REGRESSION as a parameter for running in gcp environments.
Running tests from makefile excludes regression tests.
# How to test?

Build docker image and push to your gcp env as per the instructions in the readme:
`ENV=your-env ./run_gke.sh` and check tests marked as regression are skipped.
`ENV=your-env REGRESSION=true ./run_gke.sh` and check tests marked regression are run.
Run `make at_tests` and check regression tests are skipped locally.
Hope concourse tasks run when called from pipeline.
# Links

https://trello.com/c/3UCxauc3/954-tag-tests-and-add-regression-test-job-to-ci-8
# Screenshots (if appropriate):

2020-05-19 13:57 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tag tests and add regression test job to CI (8)](https://trello.com/c/3UCxauc3/954-tag-tests-and-add-regression-test-job-to-ci-8)

2020-05-19 14:36 UTC, NickGrantX requested changes
Minor point, but maybe add a `Makefile` target to make it easy to run the regression tests locally

2020-05-19 14:40 UTC, NickGrantONS commented
Also, a lot of the fulfilment codes should only be regression

2020-05-19 14:52 UTC, NickGrantONS commented
And telephone capture, and indeed quite a few other places, we can trim down the number of examples

2020-05-20 09:06 UTC, NickGrantX approved these changes
Super quick now - 5 minutes 34 seconds on my machine!

2020-05-20 09:15 UTC, AdamHawtin requested changes

2020-05-20 09:15 UTC, AdamHawtin commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN --tags="@regression"
I don't think we need to be able to run _only_ the regression tagged tests, I think the regression tests target should run everything and the normal target should exclude the `@regression` tag

2020-05-20 09:15 UTC, AdamHawtin commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN --tags="~@regression,@regression"
`--tags="~@regression,@regression"` doesn't make sense, it's equivalent to not specifying any tags

2020-05-20 09:36 UTC, hbrace commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN --tags="~@regression,@regression"
Because I set `~@regression` as default, using `--tags=@regression` would only run those tagged regression. `--tags=~@regression,@regression` was a way round that so that it would run those regression OR not tagged regression. I've removed `full_tests` and changed `regression_tests` to the pipenv way of running the tests and with no tags so that it run all test. This way doesn't print each step of scenario however 😭

2020-05-20 09:36 UTC, hbrace commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN --tags="@regression"
See below 👇

2020-05-20 09:53 UTC, hbrace commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN --tags="~@regression,@regression"
Just realised the `--format=progress2` is what stops each line being output lol, but its useful.

2020-05-20 09:57 UTC, AdamHawtin requested changes

2020-05-20 09:57 UTC, AdamHawtin commented on acceptance_tests/features/print_file.feature
> +      | P_IC_H2   | ICHHQW      | [02,03]             | sample_input_census_spec_wales_questionnaire.csv |
Probably worth keeping one welsh code in the standard test run since it's got the whole extra QID functionality

2020-05-20 11:59 UTC, ryangrundy7 approved these changes
Looks good 👍

2020-05-20 12:16 UTC, AdamHawtin approved these changes

2020-05-20 12:17 UTC, merged