8-15 and 24-26 HH Print Fulfilment Codes
ONSdigital/census-rm-acceptance-tests-2021 pull request #258
Opened 2020-05-20 11:05 UTC by LeoKHoward

# Motivation and Context
New fulfilment codes for different scenarios added to run book so repos need updating

# What has changed
New scenario for HH UAC paper requests
New actiontype
New fulfilment codes/mappings

# How to test?
Build other branches and run ATs

# Links
https://trello.com/c/3OoO0Mx9/888-fulfilment-mappings-hh-print-products-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library

2020-05-20 11:05 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fulfilment mappings - HH Print Products (5)](https://trello.com/c/3OoO0Mx9/888-fulfilment-mappings-hh-print-products-5)

2020-05-20 12:23 UTC, hbrace requested changes

2020-05-20 12:23 UTC, hbrace commented on acceptance_tests/features/fulfilment_request.feature
> +    Examples: UAC Questionnaires
Merge in the latest changes from Master and you can tag the majority of the rows in the example table as `@regression`.

2020-05-21 06:43 UTC, AdamHawtin submitted a review, later dismissed

2020-05-21 06:43 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment_request.py
> +    requests.get(f'{notify_stub_url}/reset')
This step shouldn't need to reset the notify-stub

2020-05-21 06:43 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment_request.feature
> +    When a HH UAC fulfilment request "<fulfilment code>" message for a created case is sent
Probably worth mentioning it's a _print_ UAC fulfilment to avoid confusion with SMS e.g.
```
    When a HH print UAC fulfilment request "<fulfilment code>" message for a created case is sent
```

2020-05-21 07:51 UTC, hbrace requested changes

2020-05-21 07:51 UTC, hbrace commented on acceptance_tests/features/fulfilment_request.feature
> +  Scenario Outline: Generatdse sprint files and log events for Household UAC print fulfilment letter requests
Looks to be a typo of Generate

2020-05-21 07:56 UTC, hbrace approved these changes

2020-05-21 08:13 UTC, ryangrundy7 commented on acceptance_tests/features/fulfilment_request.feature
> +  Scenario Outline: Generate sprint files and log events for Household UAC print fulfilment letter requests
Shouldn't be `sprint files`

2020-05-21 08:58 UTC, ryangrundy7 approved these changes
LGTM 👍

2020-05-21 09:00 UTC, merged