Test PPO and QM fulfilment confirmed messages
ONSdigital/census-rm-acceptance-tests-2021 pull request #262
Opened 2020-05-20 16:05 UTC by NickGrantONS

# Motivation and Context
QM and PPO will be sending fulfilment confirmations. We should test that we can handle those messages.

# What has changed
Done a couple of tests.

# How to test?
Run the ATs.

# Links
Trello: https://trello.com/c/QShkkGg6

2020-05-20 16:09 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-203 Handle Fulfilment Confirmed event (13)](https://trello.com/c/QShkkGg6/618-rmc-203-handle-fulfilment-confirmed-event-13)

2020-05-21 12:39 UTC, AdamHawtin requested changes

2020-05-21 12:39 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment.feature
> +    And the questionnaire fulfilment case has these events logged [SAMPLE_LOADED,FULFILMENT_REQUESTED,RM_UAC_CREATED,PRINT_CASE_SELECTED,FULFILMENT_CONFIRMED]
For both scenarios it doesn't really need to send the actual fulfilment request or check the print file since the confirmation doesn't depend on it at all, it feel like the `PPO sends a fulfilment confirmed message via pubsub` shoud be the `When` of these scenarios?
 It would be good to check the correct fulfilment code and channel end up in the event log though.

2020-05-21 12:39 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment.py
> +        time.sleep(1)
I don't think this should be necessary? The result fetch should wait on it being done with it's timeout.

2020-05-21 12:39 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment.py
> +        time.sleep(1)
I don't think this should be necessary? The result fetch should wait on it being done with it's timeout.

2020-05-21 13:14 UTC, NickGrantONS commented on acceptance_tests/features/fulfilment.feature
> +    And the questionnaire fulfilment case has these events logged [SAMPLE_LOADED,FULFILMENT_REQUESTED,RM_UAC_CREATED,PRINT_CASE_SELECTED,FULFILMENT_CONFIRMED]
We don't exhaustively check every single detail of the logged event for any other logged events.

I've gotten rid of the other parts and made it a given-when-then for the slightly odd and unrealistic scenario that we'd get a fulfilment confirmed on a QID that wasn't from a fulfilment.

2020-05-21 13:17 UTC, AdamHawtin approved these changes

2020-05-21 13:26 UTC, hbrace approved these changes

2020-05-22 08:43 UTC, merged