Update refusal logic
ONSdigital/census-rm-acceptance-tests-2021 pull request #267
Opened 2020-06-01 09:46 UTC by LukeLoze1

# Motivation and Context
New tests for Refusal changes

# What has changed
Tests to check Hard and extraordinary work as expected for print and field

# How to test?
With the other apps from ticket install locally

# Links
https://trello.com/c/tnVfjzpv/710-update-refusal-logic

2020-06-01 12:54 UTC, LeoKHoward approved these changes
All pass

2020-06-01 13:45 UTC, AdamHawtin requested changes

2020-06-01 13:45 UTC, AdamHawtin commented on acceptance_tests/features/refusal.feature
> +      | ICL1E       | EXTRAORDINARY_REFUSAL | [SAMPLE_LOADED,REFUSAL_RECEIVED]                     |
Seems like this should be a single scenario rather than a scenario outline with examples.

2020-06-01 13:45 UTC, AdamHawtin commented on acceptance_tests/features/refusal.feature
> +    Examples: Refusal types to print file
Examples label doesn't make sense for this scenario

2020-06-03 07:39 UTC, AdamHawtin approved these changes

2020-06-03 12:07 UTC, merged