Added Field Case Updated tests
ONSdigital/census-rm-acceptance-tests-2021 pull request #268
Opened 2020-06-02 11:57 UTC by ryangrundy7

# Motivation and Context

Field can submit an update to a case to change the expected CE capacity. If the new expected capacity is below the actual responses, it'll send a cancel message to field.

# What has changed

- Added new feature tests for Field Case Updated events

# How to test?

- Run with other branches

# Links

[Trello](https://trello.com/c/Stb2xLG5)

2020-06-02 11:59 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-339 Handle FieldCaseUpdated event (8)](https://trello.com/c/Stb2xLG5/651-rmc-339-handle-fieldcaseupdated-event-8)

2020-06-02 16:20 UTC, liamtoozer commented on acceptance_tests/features/field_case_updated.feature
> +    Then a case_updated msg is emitted where "ceExpectedCapacity" is "0"
I think `ceExpectedCapacity` needs to be a 3?

2020-06-02 16:21 UTC, liamtoozer requested changes
The last scenario fails for me but I think it's because of the `ceExpectedCapacity` value?

2020-06-03 09:24 UTC, liamtoozer approved these changes
LGTM 👍

2020-06-03 13:41 UTC, NickGrantX approved these changes
LGTM 👍

2020-06-08 09:18 UTC, merged