CE and SPG Skeleton Cases
ONSdigital/census-rm-acceptance-tests-2021 pull request #270
Opened 2020-06-05 11:05 UTC by LeoKHoward

# Motivation and Context
Telephone capture for new address cases for CE/SPG

# What has changed
New scenarios for CE and SPG cases

# How to test?
Run tests

https://trello.com/c/McRVSnRy/961-telephone-capture-for-ce-and-spg-skeleton-units-5

2020-06-05 11:08 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Telephone capture for CE and SPG skeleton units (5)](https://trello.com/c/McRVSnRy/961-telephone-capture-for-ce-and-spg-skeleton-units-5)

2020-06-08 06:52 UTC, AdamHawtin commented on acceptance_tests/features/address.feature
> +  Scenario: Individual Telephone capture for new HI skeleton case
Don't think this scenario description needs changing, it's an individual request but the parent case is not HI.

2020-06-08 06:55 UTC, AdamHawtin commented on acceptance_tests/features/address.feature
> +    Examples:
Could include HH examples as well?

2020-06-08 06:57 UTC, AdamHawtin requested changes
One scenario I don't think should have it's description changed, otherwise seems fine 👍

2020-06-08 07:55 UTC, AdamHawtin approved these changes
👍

2020-06-08 09:25 UTC, NickGrantX approved these changes
LGTM 👍

2020-06-08 09:29 UTC, merged