Check individual case id is not used when linking to CE parent case
ONSdigital/census-rm-acceptance-tests-2021 pull request #273
Opened 2020-06-11 07:47 UTC by hbrace

# Motivation and Context

Currently if a questionnaire linked event comes in with an individual case id present and the parent case is CE/SPG, it'll chuck an error. We now want to link the questionnaire to the parent case and ignore the individual case id.

# What has changed

Test added to test this
# How to test?

Run acceptance test with case-processor built on [branch of the same name](https://github.com/ONSdigital/census-rm-case-processor/pull/163).
# Links

https://trello.com/c/V7O2qqSV/1017-pq-link-ignore-individual-case-id-if-parent-case-is-not-hh-5
# Screenshots (if appropriate):

2020-06-11 07:50 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [PQ link - Ignore Individual Case ID if 'parent' case is not HH? (5)](https://trello.com/c/V7O2qqSV/1017-pq-link-ignore-individual-case-id-if-parent-case-is-not-hh-5)

2020-06-11 11:04 UTC, NickGrantX requested changes
I don't think we need this PR. We don't have ATs for all the infinite things which shouldn't happen

2020-06-12 06:54 UTC, AdamHawtin commented
@NickGrantONS @hbrace If we decide this scenario does merit a test then instead of looking for no individual case it could just check the QID is linked to the parent, better to prove what it does do rather than attempt to prove what it doesn't.

2020-06-12 07:58 UTC, hbrace commented
@NickGrantONS @AdamHawtin I've updated the test so its testing what its doing, rather than testing what its not doing as I had before. Happy to discuss.

2020-06-15 06:14 UTC, AdamHawtin requested changes

2020-06-15 06:14 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed.py
> +    response = requests.get(f'{caseapi_url}/qid/{context.expected_questionnaire_id}')
I'd prefer to leave helper functions like this accepting the value rather than the context object, it opens them up to easier reuse in other steps.

2020-06-15 06:14 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed.py
> +    context.parent_case_id = response_json['id']
This could be done outside in the step that calls it instead, it helps to try to keep interaction with the context at the highest level possible and make these helper functions less side-effect-y.

2020-06-15 08:15 UTC, AdamHawtin approved these changes

2020-06-15 08:18 UTC, NickGrantX approved these changes

2020-06-15 08:19 UTC, merged