Enable workload identity
ONSdigital/census-rm-acceptance-tests-2021 pull request #281
Opened 2020-06-16 16:13 UTC by liamtoozer

# Motivation and Context

We can start to move our RM apps to use Workload Identity in our GCP clusters. Each k8s service that interacts with GCP can now use its own service account. This PR adds service accounts to the acceptance tests manifest

# What has changed

* Added `acceptance-tests` service account to pod manifest
* Removed unused creds, along with a couple of duplicate envs

# How to test?

See Terraform PR

# Links

https://github.com/ONSdigital/census-rm-terraform/compare/enable-workload-identity?expand=1
https://github.com/ONSdigital/census-rm-performance-tests/compare/enable-workload-identity?expand=1
https://github.com/ONSdigital/census-rm-kubernetes/compare/enable-workload-identity?expand=1

[Trello](https://trello.com/c/Z5kmTtll/970-workload-identity-update-pub-sub-printfilesvc-acceptance-and-performance-tests-13)

2020-06-16 16:15 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Workload Identity - Update pub/sub, printfilesvc, Acceptance and Performance tests (13?)](https://trello.com/c/Z5kmTtll/970-workload-identity-update-pub-sub-printfilesvc-acceptance-and-performance-tests-13)

2020-06-22 06:42 UTC, NickGrantONS commented on acceptance_tests_pod.yml
> -    - name: SENT_PRINT_FILE_BUCKET
I don't understand why we can delete this

2020-06-22 06:47 UTC, NickGrantX requested changes
`SENT_PRINT_FILE_BUCKET` is used in quite a few places

2020-06-22 06:53 UTC, liamtoozer commented on acceptance_tests_pod.yml
> -    - name: SENT_PRINT_FILE_BUCKET
This was a duplicate config line, so I removed it to tidy up. It's still in here [on this line](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/281/files#diff-3ceb2c4565bde5ee265b026900f4c716R111)

2020-06-22 06:54 UTC, davidmort commented on acceptance_tests_pod.yml
> -    - name: SENT_PRINT_FILE_BUCKET
i think this is a duplicate as the config exists at line 111 also

2020-06-22 06:57 UTC, davidmort commented
> `SENT_PRINT_FILE_BUCKET` is used in quite a few places

@NickGrantONS this config is a duplicate by the looks of it

2020-06-22 06:57 UTC, davidmort approved these changes

2020-06-22 09:05 UTC, NickGrantX approved these changes

2020-06-22 15:16 UTC, merged