Add createdDateTime and lastUpdated fields
ONSdigital/census-rm-acceptance-tests-2021 pull request #284
Opened 2020-06-18 15:16 UTC by LeoKHoward

# Motivation and Context
New fields in CASE_UPDATED and CASE_CREATED events

# What has changed
Tests amended to check for new field values

# How to test?
Build other repos on card and run the acceptance tests

# Links
https://trello.com/c/n6FwePKv/1052-waiting-on-action-processor-casecreated-caseupdated-events-should-contain-the-createddatetime-field-5

https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=Response+Management+Event+Dictionary

2020-06-18 15:18 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [caseCreated/caseUpdated events should contain the createdDateTime field (5)](https://trello.com/c/n6FwePKv/1052-casecreated-caseupdated-events-should-contain-the-createddatetime-field-5)

2020-06-19 06:24 UTC, AdamHawtin approved these changes

2020-06-19 07:52 UTC, NickGrantX requested changes
You could parse the dates to make sure they are actually ISO dates

2020-06-19 11:40 UTC, AdamHawtin requested changes

2020-06-19 11:40 UTC, AdamHawtin commented on Pipfile
> +"tonyg-rfc3339" = "*"
This looks like some guys fork of an rfc3339 project, I think we just want `rfc3339`

2020-06-19 13:34 UTC, NickGrantONS commented on Pipfile
> +"tonyg-rfc3339" = "*"
My bad. I said to copy whatever pubsub was using (it was this).

2020-06-22 09:52 UTC, AdamHawtin approved these changes

2020-06-22 09:53 UTC, AdamHawtin commented on Pipfile
> +"tonyg-rfc3339" = "*"
We should really change pubsub then, don't know why we'd be using this particular guys branch instead of the much more popular/scrutinised base

2020-06-22 09:56 UTC, AdamHawtin commented on Pipfile
> +"tonyg-rfc3339" = "*"
Nevermind, remembered we've scrapped the that pubsub service already!

2020-06-22 10:00 UTC, NickGrantX approved these changes

2020-06-23 06:47 UTC, merged