Disentangle the ATs from the inner wiring of the Case API
ONSdigital/census-rm-acceptance-tests-2021 pull request #285
Opened 2020-06-18 17:35 UTC by NickGrantONS

# Motivation and Context
Acceptance tests are supposed to be black box. Instead, these brittle tests are poking around with the innards of RM in a really horrible way.

# What has changed
Got rid of the incorrect use of Case API as a hacky way of setting up test data.

# How to test?
Run the ATs.

# Links
Trello: https://trello.com/c/TeAgCVOj

2020-06-19 09:13 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove uac-qid endpoint from Case API (5?)](https://trello.com/c/TeAgCVOj/1059-remove-uac-qid-endpoint-from-case-api-5)

2020-06-22 07:49 UTC, AdamHawtin requested changes
Passing locally but I think a file needs renaming.

2020-06-22 07:49 UTC, AdamHawtin commented on acceptance_tests/features/steps/fulfilment_or_receipt_nobody_really_knows.py
>  import functools
`ad_hoc_uac_qid.py` may not be the best name but I think it needs a better name than this, maybe just something like `new_uac.py`?

2020-06-22 10:08 UTC, hbrace approved these changes

2020-06-22 10:12 UTC, AdamHawtin approved these changes

2020-06-22 12:38 UTC, merged