1054 ce and spg print fulfilments
ONSdigital/census-rm-acceptance-tests-2021 pull request #290
Opened 2020-06-22 09:02 UTC by LukeLoze1

# Motivation and Context
If we receive and individual request against a non HH case (SPG/CE), instead of throwing an exception we will link the request to the parent case

# How to test?
With Case Processor and 

# Links
https://trello.com/c/hRorbPEP/1054-ce-and-spg-print-fulfilments-8

2020-06-22 10:28 UTC, NickGrantX approved these changes

2020-07-03 09:28 UTC, AdamHawtin requested changes

2020-07-03 09:28 UTC, AdamHawtin commented on acceptance_tests/features/steps/print_file.py
> +def step_impl(context, pack_code):
function name left as placeholder/default

2020-07-03 12:55 UTC, AdamHawtin approved these changes

2020-07-03 13:10 UTC, merged