Send Reminders to SPG Estab Type Military SFA
ONSdigital/census-rm-acceptance-tests-2021 pull request #293
Opened 2020-06-30 13:23 UTC by LeoKHoward

# Motivation and Context
Need to be able to target Military SFA type SPGs with reminders

# What has changed
New scenario checking for file with Military SFA estab_type classifier
New sample file containing relevant dummy data

# How to test?
Check tests pass

# Links
https://trello.com/c/zxsbB9uO/985-reminders-send-reminders-to-spg-estabtype-military-sfa-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CRM&title=ESTAB_TYPES+2021
https://collaborate2.ons.gov.uk/confluence/display/SDC/RMC-293+-+Print+reminder+letters+and+questionnaires

2020-06-30 13:41 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reminders - Send reminders to SPG ESTAB_TYPE “MILITARY SFA” (5)](https://trello.com/c/zxsbB9uO/985-reminders-send-reminders-to-spg-estabtype-military-sfa-5)

2020-07-01 07:14 UTC, AdamHawtin commented on acceptance_tests/features/steps/action_rules.py
> +    # (by checking for all the cases in the action scheduler DB)
This TODO can be removed

2020-07-01 07:21 UTC, AdamHawtin requested changes
Passing locally 👍 just a few comments.
Also worth discussing with @LukeLoze1 how to fit this in with the refactoring in #292

2020-07-01 07:21 UTC, AdamHawtin commented on acceptance_tests/features/steps/action_rules.py
> +    }
Could just pass pass `{'estab_type': ['Military SFA']}` into `build_and_create_action_rule` since this map only ever returns the same thing.

2020-07-01 07:21 UTC, AdamHawtin commented on acceptance_tests/features/print_file.feature
> +    And messages are emitted to RH and Action Scheduler with <questionnaire types> questionnaire types
Can use `sample file "<sample file>" is loaded successfully` instead and get rid of `And messages are emitted to RH and Action Scheduler with <questionnaire types> questionnaire types`

2020-07-07 07:23 UTC, NickGrantONS commented on acceptance_tests/features/steps/action_rules.py
> +@step('set action rule of type "{action_type}" when the case loading queues are drained')
This step looks unused to me

2020-07-07 07:23 UTC, NickGrantONS commented on acceptance_tests/features/steps/action_rules.py
> +@step('set action rule of type "{action_type}" when the case loading queues are drained')
or duplicated

2020-07-07 07:24 UTC, NickGrantONS commented on acceptance_tests/features/steps/action_rules.py
> +@step('set action rule of type "{action_type}" when the case loading queues are drained')
or both

2020-07-07 07:24 UTC, NickGrantX requested changes
Duplicated/unused step

2020-07-07 10:59 UTC, NickGrantX approved these changes

2020-07-07 11:19 UTC, AdamHawtin requested changes

2020-07-07 11:19 UTC, AdamHawtin commented on acceptance_tests/features/steps/action_rules.py
> +    poll_until_sample_is_ingested_to_action(context)
This step doesn't need to poll the action DB, the sample loaded successfully step does this now.

2020-07-07 11:23 UTC, AdamHawtin requested changes

2020-07-07 11:23 UTC, AdamHawtin commented on acceptance_tests/utilities/action_helper.py
> +    build_and_create_action_rule(context, {'estab_type': ['Military SFA']}, action_type)
To match what's in confluence this should be `'MILITARY SFA'`

2020-07-08 06:23 UTC, AdamHawtin approved these changes

2020-07-08 06:26 UTC, AdamHawtin commented on acceptance_tests/features/print_file.feature
> +    When set SPG MILITARY SFA action rule of type "<pack code>" when the case loading queues are drained
Worth noting that although this says 'SPG MILITARY SFA action rule', we're just relying on MILITARY SFA cases being SPG's in the sample. We might want to enhance our sample validation to check valid estab types by case type instead of just universally to make sure we don't end up with weird non-SPG MILITARY SFA's, for example.

2020-07-08 06:58 UTC, merged