1023 address frame delta generate additional initial contact files
ONSdigital/census-rm-acceptance-tests-2021 pull request #294
Opened 2020-07-01 12:47 UTC by AdamHawtin

# Motivation and Context:

We can now create action rules using a String which should resemble the end of a WHERE clause in SQL, e.g. `AND treatment_code IN ('abc', 'def')`. 

# What has changed?

* Renamed classifier and changed type

# How to test?

See other related PRs

# Links:

https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13

2020-07-01 13:04 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Address Frame Delta - generate additional initial contact files (13)](https://trello.com/c/TnldEmYZ/1023-address-frame-delta-generate-additional-initial-contact-files-13)

2020-07-07 07:52 UTC, NickGrantX requested changes
ATs look good. This needs the change to reflect that "users" are not defining our classifiers

2020-07-07 12:22 UTC, AdamHawtin commented on acceptance_tests/features/steps/sample.py
> -        poll_until_sample_is_ingested_to_action(context)
`poll_until_sample_is_ingested_to_action` now filters by the test start time so this check can be run everywhere this step is used

2020-07-07 12:23 UTC, AdamHawtin commented on acceptance_tests/utilities/action_helper.py
> +        after_date_time = context.test_start_utc
Unless a specific date time is supplied, filter this check to only cases created after this scenarios start time. This is of importance for the scenarios that have to reuse the same 'census' action plan ID as it ignores cases loaded against that ID from previous test runs.

2020-07-07 12:24 UTC, AdamHawtin commented on acceptance_tests/utilities/action_helper.py
> +    query = "SELECT count(*) FROM actionv2.cases WHERE action_plan_id = %s AND created_date_time > %s"
Unless a specific date time is supplied, filter this check to only cases created after this scenarios start time. This is of importance for the scenarios that have to reuse the same 'census' action plan ID as it ignores cases loaded against that ID from previous test runs.

2020-07-07 13:06 UTC, NickGrantONS commented on acceptance_tests/features/steps/sample.py
> +@step('{wait:d} second later delta sample file "{sample_file_name}" is loaded successfully')
do we really need two steps for very subtly different grammatical pedantry?

2020-07-07 13:06 UTC, NickGrantX approved these changes

2020-07-08 06:30 UTC, LukeLoze1 requested changes

2020-07-08 06:30 UTC, LukeLoze1 commented on acceptance_tests/features/steps/sample.py
> +@step('{wait:d} second later delta sample file "{sample_file_name}" is loaded successfully')
The @step('{wait:d} seconds later delta sample file "{sample_file_name}" is loaded successfully') isn't used anywhere

2020-07-08 07:08 UTC, LukeLoze1 approved these changes

2020-07-08 07:39 UTC, merged