Split print file feature into initial contact and reminders
ONSdigital/census-rm-acceptance-tests-2021 pull request #296
Opened 2020-07-08 13:14 UTC by AdamHawtin

# Motivation and Context
We're sending reminder letters to any and every unreceipted HI case created via EQ

# What has changed
* A scenarios for individual reminder print files
* Split initial contact and reminder print files into separate features (print_file.feature was getting massive)

# How to test?
Build and run linked branches

# Links
https://trello.com/c/Rc8d1RmE/983-reminders-individual-response-8

2020-07-08 14:03 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reminders - Individual Response (8)](https://trello.com/c/Rc8d1RmE/983-reminders-individual-response-8)

2020-07-08 14:04 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reminders - Individual Response (8)](https://trello.com/c/Rc8d1RmE/983-reminders-individual-response-8)

2020-07-09 14:36 UTC, NickGrantX requested changes
IR reminders don't have a UAC on them

2020-07-10 07:10 UTC, AdamHawtin commented on acceptance_tests/utilities/print_file_helper.py
> +        '|||'
@NickGrantONS It's building the comparison rows with no UAC here, the first column is the position for a UAC.

2020-07-10 07:17 UTC, NickGrantONS commented on acceptance_tests/utilities/print_file_helper.py
> +        '|||'
ach! this was an assumption based on the change I missed in Action Worker

2020-07-10 07:17 UTC, NickGrantX approved these changes

2020-07-10 08:20 UTC, NickGrantX requested changes
Repeatable test failure: `Scenario: CE and SPG Print Individual Fulfilments attach to parent case`

2020-07-10 10:52 UTC, NickGrantX approved these changes
AT fixed by merging master on Action Processor PR

2020-07-13 13:18 UTC, ryangrundy7 approved these changes

2020-07-14 06:17 UTC, merged