Fulfilment Mappings - Large Print Questionnaires: HH/Ind
ONSdigital/census-rm-acceptance-tests-2021 pull request #297
Opened 2020-07-10 11:01 UTC by LeoKHoward

# Motivation and Context
User needs to be able to request questionnaire in large print format at HH/Individual level
If case is Household and Individual then a new HI case must be created but without generating a new UAC/QID pair

# What has changed
New scenario testing large print ind fulfilment codes
Mappings
ActionType

# How to test?
Build docker images of repos on card and run ATs

# Links
https://trello.com/c/Pil5FSiZ/944-fulfilment-mappings-large-print-products-hh-ind-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Print+and+Post+Specification+2021
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Operational+Notes

2020-07-10 11:04 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fulfilment mappings - Large Print Products -HH & Ind (5)](https://trello.com/c/Pil5FSiZ/944-fulfilment-mappings-large-print-products-hh-ind-5)

2020-07-10 13:22 UTC, NickGrantX requested changes
"Do not generate UAC/QID pairs for Large Print forms" - given problems in other PRs I'm wondering if these ATs are correct

2020-07-13 11:53 UTC, NickGrantX requested changes
"Do not generate UAC/QID pairs for Large Print forms" -- requirement not implemented

2020-07-13 14:26 UTC, NickGrantX approved these changes

2020-07-14 06:27 UTC, AdamHawtin commented on acceptance_tests/features/steps/sample.py
> +import time
💅 Code style point, this import is now out of order

2020-07-14 06:40 UTC, AdamHawtin approved these changes
👍 just a tiny comment on imports

2020-07-14 07:00 UTC, merged