Request UAC via SMS (HH, Ind & CE1)
ONSdigital/census-rm-acceptance-tests-2021 pull request #300
Opened 2020-07-20 10:14 UTC by LeoKHoward

# Motivation and Context
New CE UAC fulfilment codes and new treatment ID sender and receiver codes need including 

# What has changed
New CE UAC fulfilment codes included in existing test
Updated notify template IDs

# How to test?
Build repos on card and run the ATs

# Links
https://trello.com/c/0zPdVGFQ/941-request-uac-via-sms-hh-ind-ce1-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=UAC+by+SMS+Fulfilment+2021
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=RM+Product+Library

2020-07-20 10:15 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Request UAC via SMS (HH, Ind & CE1) (5)](https://trello.com/c/0zPdVGFQ/941-request-uac-via-sms-hh-ind-ce1-5)

2020-07-21 07:56 UTC, NickGrantX requested changes
We need test coverage for CE/SPG individual SMS fulfillments (i.e. without an individual case ID)

2020-07-22 08:23 UTC, NickGrantONS commented on acceptance_tests/features/steps/fulfilment.py
> +@step('an individual UAC SMS fulfilment request "{fulfilment_code}" is received by RM')
I would make this step definition and function name clear that this is for CE/SPGs. HH has an indiv case ID

2020-07-22 08:24 UTC, NickGrantONS commented on acceptance_tests/features/fulfilment.feature
> +  Scenario: Individual UAC SMS fulfilments without Individual Case ID
could say "CE/SPG" instead of "without indiv case ID"

2020-07-22 08:24 UTC, NickGrantX requested changes
Wording changes to clarify test/function/scenario purpose

2020-07-22 11:19 UTC, AdamHawtin requested changes

2020-07-22 11:19 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment.feature
> +
This scenario outline only ever loads and HH case, I think these example need to load different samples with the correct case type.

2020-07-22 12:00 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment.feature
> +    And the fulfilment request case has these events logged [SAMPLE_LOADED,FULFILMENT_REQUESTED,RM_UAC_CREATED]
I think this scenario also needs to check the UAC is linked to the parent case, it's implied by the events but best to be specific

2020-07-22 12:06 UTC, NickGrantONS commented on acceptance_tests/features/fulfilment.feature
> +    And the fulfilment request case has these events logged [SAMPLE_LOADED,FULFILMENT_REQUESTED,RM_UAC_CREATED]
I think it does that already, by implication

2020-07-22 12:14 UTC, AdamHawtin commented on acceptance_tests/features/fulfilment.feature
> +    And the fulfilment request case has these events logged [SAMPLE_LOADED,FULFILMENT_REQUESTED,RM_UAC_CREATED]
Fair enough, I suppose it's a very strong implication in that the scenario doesn't mention a HI/individual case

2020-07-22 12:37 UTC, NickGrantX approved these changes
ATs pass

2020-07-22 13:10 UTC, AdamHawtin approved these changes

2020-07-22 13:31 UTC, merged