Receipting Table of Truth Changes
ONSdigital/census-rm-acceptance-tests-2021 pull request #304
Opened 2020-07-27 10:29 UTC by LeoKHoward

# Motivation and Context
Changes to receipting table of truth (new additions/what happens to certain case types)

# What has changed
Updated existing scenario with new fields
Pulled impossible scenarios into new scenario

# How to test?
Build image and run ATs

# Links
https://trello.com/c/bJXl9sku/1044-receipt-table-of-truth-changes-8
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Receipting

2020-07-27 10:30 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Receipt table of truth changes (8)](https://trello.com/c/bJXl9sku/1044-receipt-table-of-truth-changes-8)

2020-07-27 11:36 UTC, NickGrantONS commented on acceptance_tests/features/receipt.feature
> +  Scenario Outline: Receipting scenarios which shouldn't occur
there are scenarios which _shouldn't_ occur in the table above too. These ones are just particularly awkward as heck

2020-07-27 11:38 UTC, NickGrantONS commented on acceptance_tests/features/receipt.feature
> +    And for impossible things, a new qid is created for case type "<case type>" address level "<address level>" qid type "<qid type>" and country "<country>"
I guess they're not _impossible_... just very hard to quite conceive how how things got so badly messed up that they did happen (although linking a CE1 form to a HI case must surely be impossible I guess)

2020-07-27 11:40 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +    if qid_type in ['HH', 'CE1'] or (qid_type == "Ind" and case_type == "HH"):
for HH cases, we should be creating an individual QID to receipt on. That's not what's happening here - it's using a regular household QID

2020-07-27 11:41 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +def impossible_stuff(context, case_type, address_level, qid_type, country_code):
not impossible. Just incredibly unlikely

2020-07-27 11:42 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +@step('the correct events are logged for the loaded case events "{loaded_case_events}"')
seems excessive (i.e. unnecessary) to have this variation to the wording

2020-07-27 11:43 UTC, NickGrantX requested changes
Individual forms linked to HH cases hasn't been tested properly

2020-07-27 12:09 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +    if qid_type in ['HH', 'CE1'] or (qid_type == "Ind" and case_type == "HH"):
All the CE1 form scenarios are wrong too

2020-07-27 12:32 UTC, AdamHawtin commented on acceptance_tests/features/receipt.feature
> +    And for impossible things, a new qid is created for case type "<case type>" address level "<address level>" qid type "<qid type>" and country "<country>"
I think they're all possible and likely to occur at some point, I doubt there is anything stopping these links coming from field if they have chosen the wrong case or paper form when they link.

2020-07-27 12:35 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +    if qid_type in ['HH', 'CE1'] or (qid_type == "Ind" and case_type == "HH"):
I'm confused as to how they are wrong and still passing, the table in case processor looks correct.

2020-07-28 06:21 UTC, AdamHawtin requested changes

2020-07-28 06:21 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +        get_second_qid(context, questionnaire_type=1, qid_needed='True')
It's best to avoid calling step functions like this, if you need to share code between steps it should be pulled out into another function or into the helpers if it needs to be shared between steps modules.

2020-07-28 06:40 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +@step('the correct events are logged for the loaded case events "{loaded_case_events}"')
this variation of wording is unnecessary/excessive

2020-07-28 06:41 UTC, NickGrantONS commented on acceptance_tests/features/receipt.feature
> +      | CE        | U             | HH       | True      | AR >= E | CANCEL      | sample_1_english_CE_unit.csv  | E       | RESPONSE_RECEIVED,SAMPLE_LOADED
this scenario won't work - it won't use a HH QID

2020-07-28 06:45 UTC, NickGrantONS commented on acceptance_tests/features/receipt.feature
> +  Scenario Outline: Unlikely receipting scenarios
These scenarios could probably be combined with the above scenario now - it just needs the `get_new_qid_and_case_as_required` to be refactored to handle all the different cases

2020-07-28 06:46 UTC, NickGrantX requested changes
See comments

2020-07-29 11:19 UTC, AdamHawtin approved these changes

2020-07-30 10:31 UTC, NickGrantX approved these changes
Marvellous

2020-07-30 11:16 UTC, merged