1151 send dummy uprn to aims
ONSdigital/census-rm-acceptance-tests-2021 pull request #305
Opened 2020-07-28 07:53 UTC by LukeLoze1

# Motivation and Context
Test message sent 

# What has changed
new test to check that NEW ENHANCED ADDRESSED msg is sent to aims

# How to test?
With other apps from this ticket

# Links
https://trello.com/c/wtxPNYhb/1151-send-dummy-uprn-to-aims-finish-the-job-8

2020-07-28 12:40 UTC, AdamHawtin commented on acceptance_tests/utilities/pubsub_helper.py
> +    test_helper.assertEqual(len(response.received_messages), 1)
I think this needs some explanation, at least in the assertion and maybe a code comment as well as to why it tries to pull up to 2 messages then asserts it's only got one. I'm guessing the reasoning is a sanity check that no other, unexpected messages are also published?

2020-07-28 12:47 UTC, AdamHawtin commented on acceptance_tests/utilities/pubsub_helper.py
> +        purge_aims_new_address_topic()
Do we need to call this recursively vs. just increasing the `max_messages`? If so I think it needs a comment.

2020-07-28 12:49 UTC, AdamHawtin commented on acceptance_tests/utilities/pubsub_helper.py
> +        ack_ids.append(received_message.ack_id)
```suggestion
    ack_ids = [message.ack_id for message in response.received_messages]
```
🐍  (my personal preference for list comprehensions)

2020-07-28 12:51 UTC, AdamHawtin commented on acceptance_tests/features/steps/address.py
> +            routing_key=Config.RABBITMQ_ADDRESS_ROUTING_KEY)
Not necessarily for this PR but we repeat this pattern a lot, would be nice to pull out a `publish_to_rabbit` helper function.

2020-07-28 12:53 UTC, AdamHawtin commented on acceptance_tests/features/steps/address.py
> +    test_helper.assertEqual(context.aims_new_address_message['event']['type'], 'NEW_ADDRESS_ENHANCED')
Worth checking the dummy UPRN is here too!

2020-07-28 12:54 UTC, AdamHawtin commented on acceptance_tests/utilities/pubsub_helper.py
> +    if len(ack_ids) > 0:
```suggestion
    if ack_ids:
```

2020-07-28 12:57 UTC, AdamHawtin commented on config.py
> +    PUBSUB_EMULATOR_HOST = f'{PUBSUB_EMULATOR_HOSTNAME}:{PUBSUB_EMULATOR_PORT}'
I don't think these are used? The pubsub module picks up the emulator host environment variable itself automatically.

2020-07-28 12:57 UTC, AdamHawtin requested changes
Some suggestions/questions/comments

2020-07-28 13:00 UTC, LukeLoze1 commented on acceptance_tests/utilities/pubsub_helper.py
> +    test_helper.assertEqual(len(response.received_messages), 1)
ah, yes - this was one I was undecided about - I'll put in a comment

2020-07-28 13:01 UTC, LukeLoze1 commented on acceptance_tests/utilities/pubsub_helper.py
> +        ack_ids.append(received_message.ack_id)
nice

2020-07-28 13:05 UTC, AdamHawtin commented on acceptance_tests/utilities/pubsub_helper.py
> +        ack_ids.append(received_message.ack_id)
```suggestion
    ack_ids = [message.ack_id for message in response.received_messages]
```
Same as above

2020-07-28 13:11 UTC, AdamHawtin commented on acceptance_tests/features/address.feature
> +    Then a case created event is emitted
```suggestion
    And a case created event is emitted
```

2020-07-28 13:12 UTC, AdamHawtin commented on acceptance_tests/features/address.feature
> +    Then a case created event is emitted
Actually in order to check the UPRN on the AIMs event you may want to flip the order of these.

2020-07-28 13:15 UTC, LukeLoze1 commented on acceptance_tests/utilities/pubsub_helper.py
> +    test_helper.assertEqual(len(response.received_messages), 1)
Actually I'll get rid of it, feels a bit like trying to prove a negative.  Next step will be waiting for 5 minutes to test that the system doesn't randomly generate extra msgs etc

2020-07-28 13:18 UTC, LukeLoze1 commented on acceptance_tests/utilities/pubsub_helper.py
> +        purge_aims_new_address_topic()
Well put in a comment, without a purge command it's nicer to make sure and no max_message count is 100% guaranteed to clear all of the msgs

2020-07-28 13:19 UTC, LukeLoze1 commented on acceptance_tests/features/steps/address.py
> +            routing_key=Config.RABBITMQ_ADDRESS_ROUTING_KEY)
I agree, nice little job for another day

2020-07-28 13:38 UTC, NickGrantONS commented on acceptance_tests/features/steps/address.py
> +    test_helper.assertEqual(context.aims_new_address_message['event']['type'], 'NEW_ADDRESS_ENHANCED')
Worth checking the entire contents in fact - address details in particular

2020-07-28 13:40 UTC, NickGrantONS commented on acceptance_tests/utilities/pubsub_helper.py
> +def sync_consume_of_pubsub(context):
why does the function name mean?

2020-07-28 13:55 UTC, LukeLoze1 commented on acceptance_tests/utilities/pubsub_helper.py
> +def sync_consume_of_pubsub(context):
given it more explicit name

2020-07-28 14:12 UTC, NickGrantX submitted a review, later dismissed
Might not go here, but how does the AT service account get permission to subscribe to the AIMS subscription?

2020-07-29 08:03 UTC, AdamHawtin commented on acceptance_tests/features/steps/address.py
> +    test_helper.assertEqual(actual_address["longitude"], "-1.238193")
Not keen on hardcoding the data here, I think it should be storing the data it sends in the new address event and comparing to that.

2020-07-29 08:04 UTC, AdamHawtin commented on acceptance_tests/features/steps/address.py
>      response = requests.get(f'{Config.CASE_API_CASE_URL}{context.case_id}?caseEvents=true')
It doesn't need to fetch the case events as well here.

2020-07-29 08:26 UTC, ryangrundy7 commented on acceptance_tests/utilities/pubsub_helper.py
> +def consume_aims_new_address_messages(context):
Can't see this method being used anywhere?

2020-07-29 09:41 UTC, AdamHawtin commented on acceptance_tests/features/steps/address.py
> +    test_helper.assertEqual(actual_address["longitude"], "-1.238193")
Had a little discussion, this is being done everywhere at the moment, I might make a little ticket to go through making it better rather than blocking this PR.

2020-07-29 09:41 UTC, LukeLoze1 commented on acceptance_tests/features/steps/address.py
> +    test_helper.assertEqual(actual_address["longitude"], "-1.238193")
as discussed this is quite a common pattern, rightly or wrongly

2020-07-29 10:55 UTC, AdamHawtin approved these changes

2020-07-29 12:08 UTC, ryangrundy7 approved these changes

2020-07-29 12:22 UTC, merged