Added postcode search AT
ONSdigital/census-rm-acceptance-tests-2021 pull request #325
Opened 2020-08-24 07:46 UTC by ryangrundy7

# Motivation and Context

The first feature needed for ops-ui is to be able to search for cases via a postcode. This PR adds the postcode API call needed to get cases via postcode.

# What has changed

- Added new endpoint for getting cases via postcode

# How to test?

- Run ATs with other branches.
- Run tests in GCP

# Links

[Trello](https://trello.com/c/qkkjvupd)

2020-08-24 07:49 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [R Ops - search for case and show results (13)](https://trello.com/c/qkkjvupd/1221-r-ops-search-for-case-and-show-results-13)

2020-08-24 09:24 UTC, LeoKHoward approved these changes
Works fine for me

2020-08-24 09:58 UTC, NickGrantONS approved these changes

2020-08-25 11:22 UTC, liamtoozer requested changes
acceptance_tests_pod.yml env vars need to match the ROPS ones

2020-08-25 11:22 UTC, liamtoozer commented on acceptance_tests_pod.yml
> +    - name: CASEAPI_SERVICE_HOST
Just need to change these

2020-08-25 11:55 UTC, ryangrundy7 commented on acceptance_tests_pod.yml
> +    - name: CASEAPI_SERVICE_HOST
Done

2020-08-25 12:19 UTC, liamtoozer approved these changes

2020-08-25 13:07 UTC, merged