1137 deactivate a uac
ONSdigital/census-rm-acceptance-tests-2021 pull request #327
Opened 2020-08-24 13:38 UTC by LukeLoze1

# Motivation and Context
Tests bulk deactivate uacs and the deactivate uac messages

# What has changed
2 new tests

# How to test?
With other bits off the ticket

# Links
https://trello.com/c/xDMBSaHw/1137-deactivate-a-uac-8

2020-08-26 12:17 UTC, AdamHawtin requested changes

2020-08-26 12:17 UTC, AdamHawtin commented on acceptance_tests/features/bulk_processing.feature
> +    And every created case has a DEACTIVATE_UAC event logged against it
I think this should be worded `every UAC QID pair has a DEACTIVATE_UAC event ...` since we link it to the QID not the case.

2020-08-27 06:28 UTC, NickGrantONS commented on Pipfile
> +census-rm-toolbox = {editable = true,git = "https://github.com/ONSdigital/census-rm-toolbox",ref = "uac-branch-pip-fun"}
don't forget to change this before merging!

2020-08-27 06:30 UTC, NickGrantONS approved these changes

2020-09-01 07:30 UTC, AdamHawtin commented on acceptance_tests/features/bulk_processing.feature
> +  Scenario: A DEACTIVATE_UAC msg is sent and processed
This isn't really a bulk processing scenario, for the address updates we put a similar scenario in a new `internal_messages.feature`

2020-09-01 07:44 UTC, LukeLoze1 commented on acceptance_tests/features/bulk_processing.feature
> +  Scenario: A DEACTIVATE_UAC msg is sent and processed
fair shout

2020-09-02 09:13 UTC, AdamHawtin requested changes
Needs the new bulk processor config adding to acceptance_tests_pod.yml so it'll work in GCP

2020-09-02 11:33 UTC, AdamHawtin approved these changes

2020-09-02 11:43 UTC, merged