New feature
ONSdigital/census-rm-acceptance-tests-2021 pull request #328
Opened 2020-08-25 15:37 UTC by LeoKHoward

# Motivation and Context
When this event is sent by CC or Field then it needs to be logged and a new case created/updated

# What has changed
New feature

# How to test?
Build image from case-processor then run ATs

# Links
https://trello.com/c/G9Hq3VR1/1267-address-type-change-mvp-13
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=AddressTypeChanged+event+processing
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=FWMT+Interfaces+-+Outcomes+-+RM+-+Address+Type+Change
https://collaborate2.ons.gov.uk/confluence/display/CATD/Response+Management+Event+Dictionary

2020-08-25 15:44 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Address type change - MVP (13)](https://trello.com/c/G9Hq3VR1/1267-address-type-change-mvp-13)

2020-08-26 08:37 UTC, NickGrantONS commented on acceptance_tests/features/steps/address.py
> +    source_case = context.case_created_events[0]['payload']['collectionCase']
I'm not sure if this is checking the values against the _original_ case (now invalidated) or against the _new_ case. Suspect the latter... try checking the ID lower down and then you'll know

2020-08-26 08:38 UTC, NickGrantONS requested changes
Not sure which case the data is being checked against. Should be the original one

2020-08-26 09:19 UTC, LeoKHoward commented on acceptance_tests/features/steps/address.py
> +    source_case = context.case_created_events[0]['payload']['collectionCase']
It is checking the new case values

2020-08-26 09:50 UTC, AdamHawtin commented on acceptance_tests/features/steps/address.py
> +    context.case_id = str(uuid.uuid4())
It would be helpful to name this ID something that indicates it's the new typed changed case ID, that would help clarify @NickGrantONS's comment. If `context.case_id` needs to be set as well for other steps you can set it as well.

2020-08-26 11:18 UTC, AdamHawtin commented on acceptance_tests/features/address.feature
> +#      | sample_1_english_SPG_estab.csv | CE                  | E                     |
These rows are commented out

2020-08-26 11:31 UTC, AdamHawtin approved these changes
👍 Looks good, passing locally.

2020-08-26 11:33 UTC, AdamHawtin requested changes

2020-08-26 11:33 UTC, AdamHawtin commented on acceptance_tests/utilities/event_helper.py
> +                            context.new_case_id)
You can't change this here, it's used by other steps. I'd recommend setting `context.case_id` to the new ID as well and `context.new_case_id` and leaving this step as is.

2020-08-26 12:08 UTC, AdamHawtin approved these changes
👍  LGTM

2020-08-26 12:56 UTC, NickGrantONS commented on acceptance_tests/features/steps/address.py
> +    context.first_case = response.json()
this is checking the values in the DB. I think it should check the values on the emitted event too

2020-08-26 12:57 UTC, NickGrantONS requested changes
Could improve the checking of the values on the emitted event

2020-08-27 09:00 UTC, NickGrantONS approved these changes

2020-08-27 09:28 UTC, merged