Remove so-called 'temporary' dumping to console
ONSdigital/census-rm-acceptance-tests-2021 pull request #330
Opened 2020-08-26 12:34 UTC by NickGrantONS

# Motivation and Context
Temporary change became permanent.

# What has changed
Turned a permanent change into a temporarily gone forever one.

# How to test?
Run the ATs - the rubbish that was dumped to the console will be gone.

# Links
Trello: https://trello.com/c/jyPERRJQ

2020-08-26 12:34 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove "Temporary extra debug logging" from ATs](https://trello.com/c/jyPERRJQ/1334-remove-temporary-extra-debug-logging-from-ats)

2020-08-27 07:27 UTC, davidmort requested changes

2020-08-27 07:27 UTC, davidmort commented on acceptance_tests/utilities/pubsub_helper.py
>      except MethodNotImplemented as e:
flake8 complains here as the local variable e isn't being used anymore
```suggestion
    except MethodNotImplemented:
```

2020-08-28 06:50 UTC, davidmort approved these changes

2020-08-28 08:18 UTC, ryangrundy7 approved these changes

2020-08-28 09:08 UTC, merged