1259 am bulk uninvalidate cases
ONSdigital/census-rm-acceptance-tests-2021 pull request #340
Opened 2020-09-09 10:45 UTC by hbrace

# Checklist
Reminder: If any changes have been released in the [census-rm-sample-loader](https://github.com/ONSdigital/census-rm-sample-loader) or [census-rm-toolbox](https://github.com/ONSdigital/census-rm-toolbox/) then the version pins in the Pipfile need to be updated.
* [ ] Updated census-rm-toolbox version pin (if applicable)
* [ ] Updated census-rm-sample-loader version pin (if applicable)

# Motivation and Context

We need to mark cases as `addressInvalid` false from a file of case IDs sent from Address Management.

# What has changed

Test added for bulk processor un-invalidate addresses.
# How to test?

Deploy with all the other services on ticket built and run ATs with regression tests included.

# Links

https://trello.com/c/yUW7p0OD/934-failure-mode-war-game-scenarios

# Screenshots (if appropriate):

2020-09-09 10:50 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [AM - uninvalidate cases (8)](https://trello.com/c/bbi2PO7z/1259-am-uninvalidate-cases-8)

2020-09-09 11:53 UTC, AdamHawtin commented on Pipfile
> +census-rm-toolbox = {editable = true,git = "https://github.com/ONSdigital/census-rm-toolbox",ref = "39d886012778606ec7edceb4883618515665e80c"}
This needs to be updated to a commit on master of census-rm-toolbox before this PR is merged

2020-09-09 14:02 UTC, hbrace commented on Pipfile
> +census-rm-toolbox = {editable = true,git = "https://github.com/ONSdigital/census-rm-toolbox",ref = "39d886012778606ec7edceb4883618515665e80c"}
👍

2020-09-10 09:13 UTC, LukeLoze1 requested changes
I believe there should be a test for this in internal_message.feature for this too?

2020-09-10 10:54 UTC, AdamHawtin reviewed
Passing for me but agree with @LukeLoze1, we want to test the un-invalidate messages on their own too.

2020-09-11 06:20 UTC, LukeLoze1 commented on acceptance_tests/features/steps/bulk_processing.py
> +    for i in range(0, len(case_updated_events)):
I'm not 100% convinced by this way of doing it.  We've not used the range technique elsewhere.

2020-09-11 07:49 UTC, hbrace commented on acceptance_tests/features/steps/bulk_processing.py
> +    for i in range(0, len(case_updated_events)):
Changed this to 'for blah in blah:' type of loop

2020-09-11 08:16 UTC, AdamHawtin requested changes, later dismissed

2020-09-11 08:16 UTC, AdamHawtin commented on acceptance_tests/utilities/fieldwork_helper.py
> +            f'match any expected sample units')
Not sure what the intent is here but this loop is always going to break on the first pass and never hit the `else`.

2020-09-11 08:19 UTC, AdamHawtin commented on acceptance_tests/features/steps/bulk_processing.py
> +                                        functools.partial(field_work_cancel_callback, context=context))
This is starting a separate listener for each case updated event, I don't think that's a good idea as they may conflict in trying to update the `context`.

2020-09-11 12:33 UTC, hbrace commented on acceptance_tests/features/steps/bulk_processing.py
> +                                        functools.partial(field_work_cancel_callback, context=context))
In this case this was to get rid of the cancel messages to field that resulted from setting the cases to invalidAddress so that a later step didn't ingest these messages instead of the ones we're looking for.

2020-09-14 09:14 UTC, AdamHawtin commented on acceptance_tests/features/steps/bulk_processing.py
> +                                        functools.partial(field_work_cancel_callback, context=context))
Agreed that's the right thing to do, the bit I have a problem with is spinning up multiple message listeners, you're starting one per event rather than starting one which consumes all the events.

2020-09-15 08:44 UTC, hbrace commented on acceptance_tests/utilities/fieldwork_helper.py
> +            f'match any expected sample units')
Got rid of the else, we didn't need it.

2020-09-15 13:42 UTC, AdamHawtin commented on acceptance_tests/utilities/fieldwork_helper.py
> +        break
I'm still not sure what the intent is here, but the loop isn't really functioning like this. It always breaks on the first pass.

2020-09-17 07:52 UTC, LukeLoze1 approved these changes

2020-09-18 06:58 UTC, AdamHawtin commented on acceptance_tests/utilities/rabbit_helper.py
> +        # take it, ignore it?
Don't think the comment/question is necessary any more, we know we're nacking the message.

2020-09-18 07:21 UTC, AdamHawtin approved these changes
👍

2020-09-18 11:01 UTC, merged