Address Type Change Address Modification
ONSdigital/census-rm-acceptance-tests-2021 pull request #343
Opened 2020-09-16 12:42 UTC by LeoKHoward

# Motivation and Context
We want to be able to view address modifications in the same event as we report an address type change so that we do not have to generate 2 events

# What has changed
Updated AddressTypeChanged scenario
Updated what it checks for

# How to test?
Build case-processor branch and run tests

# Links
https://trello.com/c/wMcpQM1K/1406-allow-address-modifications-on-an-address-type-changed-event-from-cc-13
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CATD&title=Response+Management+Event+Dictionary

2020-09-16 12:42 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow address modifications on an address type changed event from CC (13)](https://trello.com/c/wMcpQM1K/1406-allow-address-modifications-on-an-address-type-changed-event-from-cc-13)

2020-09-21 07:33 UTC, NickGrantONS commented on acceptance_tests/features/steps/address.py
> +                        "addressLine1": "The Grand Budapest Hotel",
it's better if test data doesn't allow for confusion - what if the org name & address line1 got swapped by accident in the code? The test would still pass

2020-09-21 07:34 UTC, NickGrantONS requested changes
Test data improvement request

2020-09-24 08:21 UTC, liamtoozer approved these changes

2020-09-24 11:14 UTC, NickGrantONS approved these changes

2020-09-24 13:28 UTC, merged