Change the CREATE field action to UPDATE as an oa value is present in…
ONSdigital/census-rm-acceptance-tests-2021 pull request #348
Opened 2020-09-29 10:04 UTC by gavinleeedwards

#88 Checklist
Reminder: If any changes have been released in the [census-rm-sample-loader](https://github.com/ONSdigital/census-rm-sample-loader) or [census-rm-toolbox](https://github.com/ONSdigital/census-rm-toolbox/) then the version pins in the Pipfile need to be updated.
* [na] Updated census-rm-toolbox version pin (if applicable)
* [na ] Updated census-rm-sample-loader version pin (if applicable)

# Motivation and Context
When dealing with address updates, if we sent a CREATE action to field for a case that they already know about then it causes them problems. If an oa value is present for the original case then we need to send an UPDATE action instead.

# What has changed
- Amended the address update test.  An UPDATE will now be sent to field as the original loaded sample in the test already has an oa value.
- The other scenario of a CREATE being sent if no oa exists is already tested in the case-processor unit tests so isn't needed here. 

# How to test?
Run against the branch of case-procesor.

# Links
- https://trello.com/c/vlpzyc7c
- https://github.com/ONSdigital/census-rm-case-processor/pull/210

# Screenshots (if appropriate):

2020-09-30 07:39 UTC, gavinleeedwards commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create or Update after loading an update file (5)](https://trello.com/c/vlpzyc7c/1455-create-or-update-after-loading-an-update-file-5)

2020-10-01 13:41 UTC, NickGrantONS requested changes
I think we need a scenario that proves a CREATE is sent too

2020-10-02 08:15 UTC, gavinleeedwards commented
> I think we need a scenario that proves a CREATE is sent too

Do we really? The logic is already tested in unit tests.  I can add one if it means this gets a tick but I don't think we do.

2020-10-02 09:17 UTC, ryangrundy7 approved these changes

2020-10-02 09:57 UTC, NickGrantONS approved these changes

2020-10-02 09:59 UTC, merged