Change acceptance test file filter for Census filenames.
ONSdigital/census-rm-acceptance-tests-2021 pull request #35
Opened 2019-04-03 15:42 UTC by rjweeks

# Motivation and Context
RMC-112 Create initial England print file.

# What has changed
Change to file name filter.

# How to test?
Checkout branch rmc-112 for Action Service and ActionExporter Service. 
Build the services with Maven 'mvn clean install'
Make sure new docker images are produced
If not run docker in the respective repository e.g 'docker build -t eu.gcr.io/census-rm-ci/rm/census-rm-actionexportersvc .'

2019-04-04 08:49 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-112 Action Exporter Service to generate initial contact letter Print File England [8]](https://trello.com/c/1l3Y23Pj/593-rmc-112-action-exporter-service-to-generate-initial-contact-letter-print-file-england-8)

2019-04-12 12:42 UTC, AdamHawtin approved these changes
Passed for me locally 👍

2019-04-16 12:51 UTC, hbrace approved these changes
Passed for me!

2019-04-17 08:32 UTC, AdamHawtin submitted a review, later dismissed
Needs updating with the `request_type` directory for the print files.

2019-04-17 10:56 UTC, jcox-dev requested changes
Wasn't sure if I was to use the (now closed) PR branch of the action service but I can't seem to get the tests passing with the changes that (only) exist in here and the exporter.

`files_found=[]`

2019-04-18 08:46 UTC, jcox-dev approved these changes

2019-04-18 11:25 UTC, AdamHawtin commented on acceptance_tests/features/steps/print_file_steps.py
>  def _validate_print_file_content(sftp_utility, survey_ref, period, start_of_test, expected_csv_lines):
This function doesn't use the `survey_ref` or `period` parameters anymore.

2019-04-23 08:29 UTC, merged