Improve test data and names to make sure sorting is fully covered
ONSdigital/census-rm-acceptance-tests-2021 pull request #350
Opened 2020-09-30 10:42 UTC by AdamHawtin

# Checklist
Reminder: If any changes have been released in the [census-rm-sample-loader](https://github.com/ONSdigital/census-rm-sample-loader) or [census-rm-toolbox](https://github.com/ONSdigital/census-rm-toolbox/) then the version pins in the Pipfile need to be updated.
* [ ] Updated census-rm-toolbox version pin (if applicable)
* [ ] Updated census-rm-sample-loader version pin (if applicable)

# Motivation and Context
We want the intent and coverage of sorting tests to be clear

# What has changed
* make sure sorting is covered properly in test data
* use more explicit sample names

# How to test?
Check the test data changes make sense

# Links
https://trello.com/c/rryOgg3L/1543-fix-print-file-sorting-tests

2020-09-30 10:48 UTC, NickGrantONS commented on resources/sample_files/sample_5_english_CE_estab_for_sorting.csv
> +123456789125,46488965939,CE,Prison,E,RD06,Org A2,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E02003043,E06000023,E12000009,1,5,CE_Q
I probably would have jumbled the organisation order up, to prove the point

2020-09-30 10:50 UTC, NickGrantONS requested changes
To really prove the point, I think we need even more cases, and them to be in a jumbled up order in the sample, to feel really certain that the sorting is doing what we expect it to

2020-09-30 10:50 UTC, NickGrantONS commented on resources/sample_files/sample_5_ni_CE_estab_for_sorting.csv
> +123456789123,65466612306,CE,Prison,E,RD06,ONS 2,570 Headset Stuck Lane,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,N00073438,N01014540,N02003043,N06000023,N12000009,1,5,CE_1QN
just two of each org doesn't feel like enough to me - we might just be fluking it!

2020-09-30 12:49 UTC, AdamHawtin commented on resources/sample_files/sample_5_ni_CE_estab_for_sorting.csv
> +123456789123,65466612306,CE,Prison,E,RD06,ONS 2,570 Headset Stuck Lane,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,N00073438,N01014540,N02003043,N06000023,N12000009,1,5,CE_1QN
Fair points, I'll add more data just to add to the confidence that it can't end up in the right order only by accident

2020-09-30 13:05 UTC, NickGrantONS approved these changes
very nice

2020-10-01 07:14 UTC, ryangrundy7 approved these changes

2020-10-05 06:34 UTC, merged