Hack the ATs to test a bunch of hacky scenarios
ONSdigital/census-rm-acceptance-tests-2021 pull request #358
Opened 2020-10-28 09:38 UTC by NickGrantONS

# Motivation and Context
For reasons too horrible to go into in this PR, we are hacking RM in a deeply regrettable way, as forced to by external teams.

# What has changed
Test scenarios for the hacks, which are too complicated for anybody to understand/maintain/support.

# How to test?
Why even bother? This is so hacky. Nobody knows why this is being done (i.e. what requirement it meets) and nobody can understand the complex scenarios. This a departure from working high-quality software which can be supported and maintained, and will work reliably, into the territory of unsupportable, unreliable, buggy rubbish which won't work.

# Links
Trello: https://trello.com/c/i6xdQWau

2020-10-28 09:54 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Field address update CREATE/UPDATE decision hack (13)](https://trello.com/c/i6xdQWau/1628-field-address-update-create-update-decision-hack-13)

2020-10-29 11:46 UTC, ryangrundy7 requested changes
Getting these failing tests
```
Failing scenarios:
  acceptance_tests/features/internal_messages.feature:9  Address Update for addresses already known to field
  acceptance_tests/features/internal_messages.feature:15  Address update for addresses previously unknown to field
  acceptance_tests/features/internal_messages.feature:21  Un-invalidate an address message is sent
```

2020-10-29 13:48 UTC, AdamHawtin commented on acceptance_tests/features/internal_messages.feature
> +    Given sample file "sample_1_english_HH_unit_this_definitely_isnt_a_split_address_but_the_requirements_are_lunacy.csv" is loaded successfully
More helpful sample file names would be nice, I know this is frustrating but names like this will only confuse us more.

2020-10-29 13:51 UTC, AdamHawtin approved these changes
Passing locally 👍

2020-10-29 14:14 UTC, ryangrundy7 approved these changes

2020-11-02 10:57 UTC, merged