984 response driven reminders
ONSdigital/census-rm-acceptance-tests-2021 pull request #366
Opened 2020-11-10 10:43 UTC by liamtoozer

# Motivation and Context

RM will be given lists of LSOAs to generate response-driven reminders for. This PR adds previously commented out tests, now that response-driven reminders are in scope. Pack codes for these have now been changed too.

# What has changed

Uncommented tests and update the pack codes for these.

# How to test?

Run ATs and ensure all tests pass

# Links

https://trello.com/c/tRiFtYj5/984-reminders-response-driven-8

2020-11-10 12:31 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reminders - response driven (8)](https://trello.com/c/tRiFtYj5/984-reminders-response-driven-8)

2020-11-11 13:10 UTC, NickGrantONS commented on acceptance_tests/features/address.feature
> +  @hardcoded_census_values_for_collection_and_action_plan_ids
I don't think it needs to use the hard-coded collex and action plan ID

2020-11-12 09:00 UTC, NickGrantONS approved these changes
great work. Very nice 👍

2020-11-13 08:50 UTC, AdamHawtin requested changes
Needs the toolbox version bumping to make sure it runs with your changes there too.

2020-11-13 09:57 UTC, AdamHawtin approved these changes
LGTM

2020-11-18 15:34 UTC, merged