isHouseholder Flag Added To Refusal Event
ONSdigital/census-rm-acceptance-tests-2021 pull request #367
Opened 2020-11-13 10:53 UTC by LeoKHoward

# Motivation and Context
Need to know if the respondent who refused is the householder along with their name and address details
isHouseholder flag is independent of Contact and Address blocks in event JSON so even if isHouseholder is false, Contact and Address may still have details in them

# What has changed
Updated event JSON in test to include the isHouseholder flag

# How to test?
Check tests pass 
Check casev2.events to ensure the new isHouseholder flag is set

# Links
https://trello.com/c/WT0EGYyU/1150-nc-update-refusal-event-5
https://collaborate2.ons.gov.uk/confluence/display/CATD/Response+Management+Event+Dictionary?focusedCommentId=20210501#comment-20210501

2020-11-13 11:02 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [NC - update refusal event (5)](https://trello.com/c/WT0EGYyU/1150-nc-update-refusal-event-5)

2020-11-13 12:49 UTC, AdamHawtin commented on acceptance_tests/features/steps/refusal.py
> +                        "surname": "Testing"
I would be worth using test data which looks more like the encrypted contact info we're actually expecting, before this change this block would be completely ignored, it's now being persisted in RM and seeing that in our tests it'll look like we're saving unencrypted names. Won't effect the test itself, purely for readers benefit.

2020-11-17 12:34 UTC, NickGrantONS commented on acceptance_tests/features/steps/refusal.py
>                      "report": "Test refusal",
There's no report anymore

2020-11-17 12:36 UTC, NickGrantONS requested changes
Pls remove `report` now that it's been removed from the event

2020-11-17 15:31 UTC, NickGrantONS approved these changes
looks good

2020-11-19 10:02 UTC, LukeLoze1 approved these changes

2020-11-19 11:46 UTC, merged