1404 nc import letter file 1 case processor work
ONSdigital/census-rm-acceptance-tests-2021 pull request #368
Opened 2020-11-16 10:05 UTC by LukeLoze1

# Motivation and Context
Non compliance end point test

# What has changed
New Test

# How to test?
With case-processor and case-api from this ticket

# Links
https://trello.com/c/bEEgKqZY/1404-nc-import-letter-file-1-case-processor-work-8

2020-11-17 08:12 UTC, AdamHawtin commented on acceptance_tests/features/internal_messages.feature
> +    Then CASE_UPDATED events are emitted Case with nonCompliance set
Wording implies multiple events when it should only be one?

2020-11-17 08:17 UTC, AdamHawtin commented on acceptance_tests/features/steps/internal_messages.py
> +    collection_case = get_case_updated_events(context, 1)[0]['payload']['collectionCase']
This is only looking at the first event it picks out?

2020-11-17 08:18 UTC, AdamHawtin commented on acceptance_tests/features/internal_messages.feature
> +    When a NONCOMPLIANCE message is sent
I think this should either be plain english "When a non compliance message is sent" or use the exact event name "When a SELECTED_FOR_NON_COMPLIANCE message is sent" to avoid confusion.
(splitting hairs 💅 )

2020-11-17 09:00 UTC, gavinleeedwards requested changes

2020-11-17 09:00 UTC, gavinleeedwards commented on acceptance_tests/features/internal_messages.feature
> +  Scenario: NonCompliance an address message is sent
Ay?

2020-11-17 09:00 UTC, gavinleeedwards commented on config.py
> +    RABBITMQ_NONCOMPLIANCE_QUEUE = os.getenv('RABBITMQ_UNINVALIDATE_ADDRESS_QUEUE', 'case.rm.nonCompliance')
Env should be `RABBITMQ_NONCOMPLIANCE_QUEUE`

2020-11-17 09:12 UTC, LukeLoze1 commented on acceptance_tests/features/steps/internal_messages.py
> +    collection_case = get_case_updated_events(context, 1)[0]['payload']['collectionCase']
renamed function and step to something more correctful

2020-11-17 14:16 UTC, gavinleeedwards approved these changes

2020-11-20 10:07 UTC, NickGrantONS approved these changes

2020-11-23 07:30 UTC, NickGrantONS requested changes
You forgot to check `SELECTED_FOR_NON_COMPLIANCE` to the logged events via Case API. That test would have shown that Case API is broken because you added a new event type to Case Processor, but not to Case API

2020-11-23 15:23 UTC, NickGrantONS approved these changes

2020-11-24 12:04 UTC, merged