Nc import letter file 1 print file work
ONSdigital/census-rm-acceptance-tests-2021 pull request #371
Opened 2020-11-20 13:44 UTC by hbrace

# Checklist
Reminder: If any changes have been released in the [census-rm-sample-loader](https://github.com/ONSdigital/census-rm-sample-loader) or [census-rm-toolbox](https://github.com/ONSdigital/census-rm-toolbox/) then the version pins in the Pipfile need to be updated.
* [ ] Updated census-rm-toolbox version pin (if applicable)
* [ ] Updated census-rm-sample-loader version pin (if applicable)

# Blocked until after Lukes ATs PR has gone in

# Motivation and Context

There is a new action rule for non compliance print files.
# What has changed

Test added to create print files for non compliance for both England and Wales types.
# How to test?

Run ATs with PRs off attached ticket.
# Links

https://trello.com/c/r6x95aJS/1405-nc-import-letter-file-1-print-file-work-8
# Screenshots (if appropriate):

2020-11-20 13:44 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [NC - Import letter file 1 - print file work (8)](https://trello.com/c/r6x95aJS/1405-nc-import-letter-file-1-print-file-work-8)

2020-11-23 07:34 UTC, NickGrantONS requested changes
Needs an AT to check that a FIELD action plan will send FWMT-G CREATE messages for NCF cases

2020-11-23 08:10 UTC, liamtoozer commented on acceptance_tests/features/steps/action_rules.py
> +                                 DEFAULT_CLASSIFIERS + f"metadata->>'nonCompliance' = 'NCL' AND SUBSTRING(region, 1, 1) \
The spec says this is only for `HH` case types, but the `DEFAULT_CLASSIFIERS` will include: `SPG`, `CE`, and `HH`. I know the sample loaded was for `HH` cases but it's probably a good idea to be explicit in what the action rule classifiers should be.

https://github.com/ONSdigital/census-rm-acceptance-tests/blob/6e73b78ee2d1bf6365d12d46b4ec843502a9ff06/acceptance_tests/utilities/mappings.py#L13

2020-11-23 11:17 UTC, liamtoozer approved these changes

2020-11-23 15:24 UTC, NickGrantONS approved these changes
Looking good

2020-11-24 13:20 UTC, merged