Verify new case service emits case created events to RH
ONSdigital/census-rm-acceptance-tests-2021 pull request #39
Opened 2019-04-12 14:45 UTC by liamtoozer

# Motivation and Context

We created a new case service which handles the emitting of the case created events to RH and we need to verify that this is working end-to-end.

# What has changed

* We put the samples onto a new queue as JSON messages
* We check that the RH queue has the expected number of case created messages on receiving end

# How to test?

Run the tests against the updated docker-dev (see link below)

# Links

https://trello.com/c/jRjqBbgh/576-emit-casecreated-event-8

2019-04-12 15:15 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Emit CaseCreated event (8)](https://trello.com/c/jRjqBbgh/576-emit-casecreated-event-8)

2019-04-15 06:18 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_steps.py
> +        assert False, 'Message body is invalid'
```
assert _is_valid_message(parsed_body), 'Message body is invalid'
```

2019-04-15 06:34 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_steps.py
> +        assert False, 'Could not find sample unit'
```python
assert matched_sample_unit_index is not None, 'Could not find sample unit' 
```

2019-04-15 07:37 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_steps.py
> +        ch.stop_consuming()
```python
if not expected_sample_units:
    ch.stop_consuming()
```

2019-04-15 07:39 UTC, AdamHawtin commented on config.py
> +    RABBITMQ_NEW_QUEUE = os.getenv('RABBITMQ_NEW_QUEUE', 'exampleInboundQueue')
Worth naming this more descriptively, e.g. `RABBITMQ_CASE_INBOUND_JSON_QUEUE` or similar?

2019-04-15 08:08 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_steps.py
> +        assert False, 'Some messages are missing'
```python
assert not expected_sample_units, 'Some messages are missing'
```

2019-04-15 08:35 UTC, AdamHawtin requested changes
The test looks good and passes for me against docker dev, just some small code suggestions.

2019-04-15 08:37 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_steps.py
> +           and sample_unit['attributes']['RGN'][:1] == rh_message['payload']['collectionCase']['address']['region']
```suggestion
           and sample_unit['attributes']['RGN'][0] == rh_message['payload']['collectionCase']['address']['region']
```

2019-04-16 12:57 UTC, AdamHawtin requested changes

2019-04-16 12:57 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_steps.py
> +    tc.assertEqual(8, len(parsed_body['payload']['collectionCase']['caseRef']))
Not sure why we're using a TestCase for these asserts, given we use `assert` everywhere else?

2019-04-17 07:51 UTC, NickGrantONS commented on acceptance_tests/features/steps/case_steps.py
> +    tc.assertEqual(8, len(parsed_body['payload']['collectionCase']['caseRef']))
I think it's because it tells us more detail about what didn't match, making it easier to see what the wrong value was

2019-04-17 10:19 UTC, AdamHawtin approved these changes

2019-04-23 13:10 UTC, NickGrantX approved these changes
LGTM 👍

2019-04-23 13:18 UTC, merged