Rmc 111 manifest file
ONSdigital/census-rm-acceptance-tests-2021 pull request #44
Opened 2019-04-25 13:25 UTC by LukeLoze1

# Motivation and Context
Now expects a valid Manifest to be created by the actionexporter

# What has changed
New step added to check for ... manifest files

# How to test?
You'll need the correct version of action exporter image running locally or in k8s
https://github.com/ONSdigital/census-rm-actionexporter-service/tree/RMC-111-Manifest-File

Acceptance Tests should pass and show manifest file is created

# Links
https://trello.com/c/vfgiKsXp/590-rmc-111-manifest-file-for-pnp-print-file-13
PR to actionexporter to follow

# Screenshots (if appropriate):

2019-04-29 07:48 UTC, NickGrantONS commented
Code looks good but I will test this when the Action Service PR comments are addressed

2019-04-29 08:40 UTC, jcox-dev submitted a review, later dismissed
Just some general code comments

2019-04-29 08:40 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    file = dict(
Used `_file` above but now `file`? (Which replaces the builtin Python `file` object).
```suggestion
    _file = dict(
```

2019-04-29 08:40 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +        files=[file],
```suggestion
        files=[_file],
```

NB: an alternative to underscoring to avoid the reserved word `file` could be something like `fyle`, for example.

2019-04-29 08:40 UTC, jcox-dev commented on acceptance_tests/utilities/sftp_utility.py
> +        f = list(filter(lambda f: f'P_IC_ICL1_{period}' in f.filename
It would be nice not to use `filter`. It's generally considered a little harmful now that list comprehensions are more widely accepted:

```suggestion
        return [f for f in files if f'P_IC_ICL1_{period}' in f.filename
                                 and f.filename.endswith(suffix)
                                 and period_start_time <= datetime.fromtimestamp(f.st_mtime)]
```

2019-04-29 08:40 UTC, jcox-dev commented on acceptance_tests/utilities/sftp_utility.py
> +            content = sftp_file.read().decode('utf-8')
No real need to store in a variable if it's just going to be immediately returned.

```suggestion
            return sftp_file.read().decode('utf-8')
```

2019-04-29 12:36 UTC, rjweeks requested changes

2019-04-29 12:36 UTC, rjweeks commented on acceptance_tests/utilities/sftp_utility.py
> +        return f
This looks like an error. Code is duplicated and multiple return statements.

2019-04-29 12:36 UTC, rjweeks commented on acceptance_tests/utilities/sftp_utility.py
> +
Multiple return statements.

2019-04-29 12:45 UTC, jcox-dev commented on acceptance_tests/utilities/sftp_utility.py
> +        return f
@rjweeks  I half-expected this to happen with GitHub's "suggestion" functionality...

@LukeLoze1 line 33-36 can be removed to fix this.

2019-04-29 12:46 UTC, jcox-dev commented on acceptance_tests/utilities/sftp_utility.py
> +            return content
```suggestion
```

2019-04-29 14:12 UTC, rjweeks approved these changes

2019-04-30 08:03 UTC, NickGrantX approved these changes
Tested and all working great. Looks good to me 👍

2019-04-30 08:30 UTC, merged