Add test for unaddressed
ONSdigital/census-rm-acceptance-tests-2021 pull request #50
Opened 2019-05-13 13:54 UTC by NickGrantONS

# Motivation and Context
We need to print a certain amount of letters, questionnaires, continuation pages etc. without an address. These will have an associated UAC/QID but no case - the case association will happen later. This PR covers the part where we generate the UAC/QID pair and emit the event to RH and Action Scheduler.

# What has changed
Added test scenario for unaddressed.

# How to test?
Run the acceptance tests against the Case Processor branch `rmc-176-uac-qid-pairs-for-unaddressed`.

# Links
Trello: https://trello.com/c/Hv7z7OqL/684-rmc-176-create-uac-qid-pairs-for-unaddressed-ccs-questionnaires-8

# Screenshots (if appropriate):

2019-05-13 14:07 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-176 Create UAC/QID pairs for unaddressed/CCS questionnaires (8)](https://trello.com/c/Hv7z7OqL/684-rmc-176-create-uac-qid-pairs-for-unaddressed-ccs-questionnaires-8)

2019-05-15 10:01 UTC, AdamHawtin requested changes
Passing locally and in k8s against the case processor branch for me, I just think the empty step should be deleted.

2019-05-15 10:01 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    return
Could just delete this step from the scenario?

2019-05-15 10:02 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed_steps.py
> +tc = TestCase('__init__')
We do this in a couple of places now, worth factoring it out into a helper?

2019-05-15 10:12 UTC, NickGrantONS commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    return
Is it even legal to have a "Given... Then" without a "When"?

2019-05-15 10:19 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    return
It makes sense as a "When... Then" doesn't it? We've done it in a few other places where there isn't any data/state setup required

2019-05-15 13:46 UTC, NickGrantONS commented on acceptance_tests/features/steps/unaddressed_steps.py
> +tc = TestCase('__init__')
it's a one-liner... as would the helper be?

2019-05-15 14:25 UTC, rjweeks approved these changes

2019-05-15 14:25 UTC, NickGrantONS commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    return
ok will change then

2019-05-15 14:26 UTC, NickGrantONS commented on acceptance_tests/features/steps/unaddressed_steps.py
> +tc = TestCase('__init__')
well if Monsier Jamie agrees I'm outnumbered - will refactor

2019-05-16 07:47 UTC, AdamHawtin approved these changes

2019-05-16 07:50 UTC, merged