Test caseapi lookup for contact centre querying
ONSdigital/census-rm-acceptance-tests-2021 pull request #53
Opened 2019-05-16 08:22 UTC by hbrace

# Motivation and Context

These tests are to ensure the caseapi endpoints supply the correct response when queried.
# What has changed

Case lookup feature has been added, with a number of scenarios. Most of the tests that query data use existing case steps to load the sample and get the details from rabbit.
The England sample file has had some UPRNs added to ensure all endpoints are covered.
# How to test?

mvn clean install off this branch https://github.com/ONSdigital/census-rm-case-api/tree/contact-centre-case-lookup and do a make up in docker.
Run the acceptance tests.
# Links

https://trello.com/c/Tg697scy/633-rmc-139-provide-case-look-up-for-cc-13
# Screenshots (if appropriate):

2019-05-16 08:23 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-139 Provide case look up for CC (13)](https://trello.com/c/Tg697scy/633-rmc-139-provide-case-look-up-for-cc-13)

2019-05-20 11:31 UTC, liamtoozer requested changes
Think the `kubernetes.env` file will also updating with case-api env variables to correctly run in k8s.

2019-05-22 09:10 UTC, AdeHarrison commented on acceptance_tests/features/case_look_up.feature
> +  Scenario: Check non-existent caseId returns an empty list
"returns an empty list" not correct

2019-05-22 10:01 UTC, AdeHarrison approved these changes
LGTM

2019-05-22 11:41 UTC, NickGrantX approved these changes
LGTM 👍 

Acceptance tests passing

2019-05-22 12:28 UTC, liamtoozer approved these changes

2019-05-22 12:32 UTC, merged