Rehearsal sample spec
ONSdigital/census-rm-acceptance-tests-2021 pull request #59
Opened 2019-05-23 10:56 UTC by LukeLoze1

# Motivation and Context
To add 3 fields for rehearsal-sample-spec and correct rgn to region

# What has changed
Changed sample files and loader to reflect new fields and rgn to region

# How to test?
Get new images installed and make test

# Links
Also with the other branches in the PR images created run the related acceptance-tests

https://trello.com/c/CzpZXxpZ/741-update-case-data-model-to-reflect-final-rehearsal-sample-8
CASE API:
https://github.com/ONSdigital/census-rm-case-api/tree/rehearsal-sample-spec
ACTION SCH:
https://github.com/ONSdigital/census-rm-action-scheduler/pull/6/files
CASE-PROCERSSOR:
ONSdigital/census-rm-case-processor#11
& new tests:
https://github.com/ONSdigital/census-rm-acceptance-tests/tree/rehearsal-sample-spec

# Screenshots (if appropriate):

2019-05-29 12:28 UTC, hbrace approved these changes

2019-05-30 10:47 UTC, NickGrantX approved these changes
LGTM 👍

2019-05-30 11:49 UTC, AdamHawtin requested changes
It's failing for me locally on scenario 'eQ receipt results in UAC updated event sent to RH' with `KeyError: 'REGION'`. Looks like the sample file from another recent feature needs `RGN` updating to `REGION` still.

2019-05-30 14:08 UTC, AdamHawtin approved these changes

2019-05-30 14:12 UTC, merged