Test for fieldwork management tool messages
ONSdigital/census-rm-acceptance-tests-2021 pull request #63
Opened 2019-05-30 11:03 UTC by hbrace

# Motivation and Context

FWMT need to receive messages so they can follow up on certain cases.

# What has changed

Test added to read in sample and check messages to Action.Field queue

# How to test?

Run the tests using an action scheduler image built off a branch of the same name RMC-133-Distribute-cases-to-field

# Links

https://trello.com/c/vhOInkPz/683-rmc-133-distribute-tranche-2-hh-cases-to-fwmtg-13

# Screenshots (if appropriate):

2019-05-30 11:03 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-133 Distribute Tranche 2 HH cases to FWMTG (13)](https://trello.com/c/vhOInkPz/683-rmc-133-distribute-tranche-2-hh-cases-to-fwmtg-13)

2019-05-30 12:11 UTC, AdamHawtin commented on acceptance_tests/features/steps/action_steps.py
> +
This set of ifs and functions just serves to map strings to dictionaries so could be done simpler like this:
```python
classifiers_for_action_type = {
        'ICL1E': {'treatmentCode': ['HH_LF3R2E', 'HH_LF3R3AE', 'HH_LF3R3BE', 'HH_LFNR1E', 'HH_LF2R3BE']},
        'ICL2W': {'treatmentCode': ['HH_LFNR1W', 'HH_LFNR2W', 'HH_LFNR3AW', 'HH_LF2R1W', 'HH_LF2R2W', 'HH_LF2R3AW',
                                    'HH_LF2R3BW', 'HH_LF3R1W', 'HH_LF3R2W', 'HH_LF3R3AW', 'HH_LF3R3BW']},
        'ICHHQW': {'treatmentCode': ['HH_QF2R1W', 'HH_QF2R2W', 'HH_QF2R3AW', 'HH_QF3R1W', 'HH_QF3R2W', 'HH_QF3R3AW']}
    }

    create_action_rule(str(uuid.uuid4()), trigger_date_time,
                       classifiers_for_action_type.get(action_type), action_plan_url, action_type)
```

2019-05-30 12:36 UTC, AdamHawtin commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    context.case_created_events = []
I don't think this variable is ever used elsewhere in this test.

2019-05-30 12:41 UTC, AdamHawtin commented on acceptance_tests/features/steps/fieldwork_steps.py
> +        assert False, 'Could not find sample unit'
The assertion fail message is slightly misleading, something like `Found message on Action.Field case queue with no matching expected sample unit` would clarify.

2019-05-30 13:07 UTC, AdamHawtin requested changes
Passing locally against the action-scheduler branch, just a couple of minor comments

2019-05-31 06:40 UTC, jcox-dev commented on acceptance_tests/features/steps/action_steps.py
> +
I agree with @AdamHawtin though we might want to fail hard if the key isn't found:

```python
classifiers_for_action_type[action_type]
```

instead of the `.get`

2019-05-31 06:44 UTC, jcox-dev commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    context.case_created_events = []
Is the context cleared before each scenario? If not, might be worth adding this to all in `environment.py` if it's causing issues.

2019-05-31 07:16 UTC, AdamHawtin commented on acceptance_tests/features/steps/action_steps.py
> +
@jcox-dev Agreed, that would prevent unexpectedly running it with no classifiers by erroring out instead. That would just require added a `None` entry to the dictionary for any action type we don't want classifiers for, .e.g
```python
classifier_for_action_type = {
        'ICL1E': {'treatmentCode': ['HH_LF3R2E', 'HH_LF3R3AE', 'HH_LF3R3BE', 'HH_LFNR1E', 'HH_LF2R3BE']},
        'ICL2W': {'treatmentCode': ['HH_LFNR1W', 'HH_LFNR2W', 'HH_LFNR3AW', 'HH_LF2R1W', 'HH_LF2R2W', 'HH_LF2R3AW',
                                    'HH_LF2R3BW', 'HH_LF3R1W', 'HH_LF3R2W', 'HH_LF3R3AW', 'HH_LF3R3BW']},
        'ICHHQW': {'treatmentCode': ['HH_QF2R1W', 'HH_QF2R2W', 'HH_QF2R3AW', 'HH_QF3R1W', 'HH_QF3R2W', 'HH_QF3R3AW']},
        'FF2QE': None
    }
```

2019-05-31 07:19 UTC, AdamHawtin commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    context.case_created_events = []
@jcox-dev User context attributes assigned within the step are cleared after the scenario so no worries there https://behave.readthedocs.io/en/latest/context_attributes.html#user-attributes

2019-05-31 07:37 UTC, jcox-dev requested changes
Tests pass. Mostly waiting on changes from @AdamHawtin's comments.

2019-05-31 07:37 UTC, jcox-dev commented on acceptance_tests/features/steps/fieldwork_steps.py
> +        return
This return will never be reached with `assert False...` above it.

2019-05-31 08:31 UTC, AdamHawtin requested changes
We should be testing as close to the AC on the card as possible.

2019-05-31 08:31 UTC, AdamHawtin commented on acceptance_tests/features/steps/action_steps.py
> +        'FF2QE': None
The AC on the ticket specify only treatment codes `HH_QF2R1E` should be included, I think we should include this in the acceptance test.

Side note, if you're intending to use `.get` access there's no real need to add `None` values to this dict.

2019-05-31 08:37 UTC, hbrace commented on acceptance_tests/features/steps/action_steps.py
> +        'FF2QE': None
I should start reading the cards a bit closer!

2019-05-31 10:27 UTC, AdamHawtin commented on resources/sample_files/sample_for_print_stories.csv
> +DDR190314000000195675,DDR190314000000113701,123456789123,HH,Household,U,RD06, ,Flat 56 Francombe House,Commercial Road,Tree area,Windleybury,XX1 0XX,51.4463421,-2.5924477,E00073438,E01014540,E0200304
There is whitespace in some of these columns where I expect it is supposed to be empty (probably an artefact of converting from xlsx).

2019-05-31 10:28 UTC, AdamHawtin commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    all_sample_units = context.sample_units.copy()
There's no need to copy this here since you're only using it to construct another new list.

2019-05-31 13:27 UTC, AdamHawtin approved these changes

2019-05-31 15:07 UTC, jcox-dev approved these changes

2019-06-04 12:13 UTC, merged