Set pubsub emulator variable for make target
ONSdigital/census-rm-acceptance-tests-2021 pull request #64
Opened 2019-05-31 07:46 UTC by jcox-dev

# Motivation and Context

Remembering to set the pubsub emulator environment variable when running the acceptance tests locally is a pain point for local workflow.

# What has changed

- Added a helper script for writing required environment variable to `.env` for running tests locally

# How to test?

- `make up` -docker-dev
- `make test` -acceptance-tests

2019-05-31 13:19 UTC, AdamHawtin requested changes

2019-05-31 13:19 UTC, AdamHawtin commented on set_pubsub_emulator.sh
> +emulator=`gcloud beta emulators pubsub env-init`
This command doesn't seem to work for me with docker dev since it's using a dockerised pubsub emulator, not one locally started by the gcloud sdk.

2019-05-31 15:08 UTC, jcox-dev commented on set_pubsub_emulator.sh
> +emulator=`gcloud beta emulators pubsub env-init`
Hmm... maybe it should just add the predictable, hardcoded variable to the .env rather than doing something clever.

2019-06-13 08:57 UTC, liamtoozer approved these changes

2019-06-16 09:48 UTC, closed without merging