Rmc 141 unaddressed print files
ONSdigital/census-rm-acceptance-tests-2021 pull request #67
Opened 2019-06-05 08:06 UTC by liamtoozer

**NOTE**: Currently trying to mount volumes for DB certs needed for test to run in k8s

# Motivation and Context

A repo has been created which allows ad-hoc creation of unaddressed print files. We should test to ensure this feature works as expected.

# What has changed

* Copied scripts from `census-rm-qid-batch-runner` repo for tests
* Added new feature and steps to test output
* Startup/teardown tmp directory to store unaddressed files. This will allow the acceptance tests to be run locally and in GCP

# How to test?

### Locally
`make test`

### In Kubernetes
Currently being worked on...

# Links

https://trello.com/c/tT4XZ09B/784-acceptance-tests-for-unaddressed-print-files-13#

2019-06-05 09:01 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Acceptance tests for unaddressed print files (13)](https://trello.com/c/tT4XZ09B/784-acceptance-tests-for-unaddressed-print-files-13)

2019-06-06 07:14 UTC, jcox-dev commented on acceptance_tests/features/environment.py
> +def before_all(_context):
If a param is not used, the convention is to use a single `_` in its place (although I do appreciate the retention of the parameter's name):

```suggestion
def before_all(_):
```

If this is just to fix some IDE warnings then I'd suggest we stick to the full name (`context`) instead of coding to the tool.

2019-06-06 07:14 UTC, jcox-dev commented on acceptance_tests/features/environment.py
> +    context.test_file_path = Path(__file__).parent.parent.resolve().joinpath('tmp_test_files')
Perhaps:

```suggestion
    context.test_file_path = Path(__file__).parents[2].resolve().joinpath('tmp_test_files')
```

2019-06-06 07:14 UTC, jcox-dev commented on acceptance_tests/features/steps/unaddressed_steps.py
> +            for row in print_file_reader:
Could `enumerate` be used here as well?

```suggestion
            for count, row in enumerate(print_file_reader):
```

2019-06-06 07:14 UTC, jcox-dev commented on config.py
> +    USE_LOCAL_DOCKER = os.getenv('USE_LOCAL_DOCKER', False)
I expect this could be set if using any of the `Makefile` targets.

2019-06-06 14:48 UTC, liamtoozer commented on acceptance_tests/features/steps/unaddressed_steps.py
> +            for row in print_file_reader:
Good shout. This file has now been moved to [here](https://github.com/ONSdigital/census-rm-qid-batch-runner/pull/5/files#diff-0b4c33d154623b732d19eea287755318), so I'll make the changes there 👍

2019-06-06 15:40 UTC, liamtoozer commented on acceptance_tests/features/environment.py
> +    context.test_file_path = Path(__file__).parent.parent.resolve().joinpath('tmp_test_files')
This has now been removed as we'll be testing in a container and wouldn't need to teardown paths

2019-06-06 19:33 UTC, liamtoozer commented on acceptance_tests/features/steps/unaddressed_steps.py
> +            for row in print_file_reader:
Thinking about it, I think we wanted to use the `row_counter` outside of the loop for checking the total row count against the expected batch count. I wonder if there's a nice way of getting the row count from DictReader instead

2019-06-07 08:42 UTC, jcox-dev requested changes

2019-06-07 08:42 UTC, jcox-dev commented on tasks/kubectl-run-acceptance-tests.yml
> +      kubectl apply -f acceptance-tests-repo/tasks/qid-batch-runner.yml
It looks like this yaml is duplicated from the `census-rm-qid-batch-runner` repo. Is it possible to have that as a `get` resource for this task so we don't have to maintain the pod config in two places?

```suggestion
      kubectl apply -f batch-runner-repo/qid-batch-runner.yml
```

2019-06-07 09:03 UTC, jcox-dev commented on tasks/kubectl-run-acceptance-tests.yml
> +      kubectl apply -f acceptance-tests-repo/tasks/qid-batch-runner.yml
@liamtoozer I expect batch-runner-repo will need plugging in one of the pipelines in: https://github.com/ONSdigital/census-rm-deploy

2019-06-07 14:02 UTC, hbrace submitted a review, later dismissed

2019-06-07 16:02 UTC, NickGrantX submitted a review, later dismissed
You should remove the code which puts the messages on the unaddressed queue, because it's now unused, along with the config setting for the queue.

2019-06-10 08:44 UTC, AdamHawtin commented on tasks/kubectl-run-acceptance-tests.yml
> +      sleep 20
If we change the kind of the qid-batch-runner k8s manifest to a deployment, we could use a `kubectl rollout` command here to wait on the container actually becoming ready

2019-06-10 12:10 UTC, AdamHawtin submitted a review, later dismissed

2019-06-10 12:10 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    if Config.USE_LOCAL_DOCKER:
Conditioning like this means this test will always go green when `USE_LOCAL_DOCKER` is `False`. That will be misleading on the test output. Instead we could tag the scenario so it can be skipped.

2019-06-11 12:29 UTC, jcox-dev requested changes
To get the tests running locally (the `validate_unaddressed_print_file` step was failing when the new batch runner container was trying to connect to rabbitmq) I had to change a couple of things.

Is there a better way around this?

2019-06-11 12:29 UTC, jcox-dev commented on acceptance_tests/features/steps/unaddressed_steps.py
> +             '--env', f'RABBITMQ_SERVICE_HOST={Config.RABBITMQ_HOST}',
I had to change this to:
```suggestion
             '--env', f'RABBITMQ_SERVICE_HOST=rabbitmq',
```

2019-06-11 12:29 UTC, jcox-dev commented on acceptance_tests/features/steps/unaddressed_steps.py
> +             '--env', f'RABBITMQ_SERVICE_PORT={Config.RABBITMQ_PORT}',
and:

```suggestion
             '--env', f'RABBITMQ_SERVICE_PORT=5672',
```

2019-06-11 12:46 UTC, liamtoozer commented on acceptance_tests/features/steps/unaddressed_steps.py
> +             '--env', f'RABBITMQ_SERVICE_PORT={Config.RABBITMQ_PORT}',
Ah good point, it'll be using the internal Docker host/ports. I'll revert it back now.

2019-06-11 12:46 UTC, liamtoozer commented on acceptance_tests/features/steps/unaddressed_steps.py
> +             '--env', f'RABBITMQ_SERVICE_HOST={Config.RABBITMQ_HOST}',
Ah good point, it'll be using the internal Docker host/ports. I'll revert it back now.

2019-06-11 15:16 UTC, jcox-dev reviewed
To run in k8s, I pushed up a new docker image of both the acceptance tests and the batch runner and then had to edit the config to point at the new batch runner image.

2019-06-13 07:11 UTC, jcox-dev approved these changes

2019-06-13 07:13 UTC, jcox-dev commented on run_gke.sh
> +BATCH_RUNNER_CONFIG=https://raw.githubusercontent.com/ONSdigital/census-rm-qid-batch-runner/temp-image-location/qid-batch-runner.yml
This needs switching back to point at master once https://github.com/ONSdigital/census-rm-qid-batch-runner/pull/5 (?) has been merged.

2019-06-13 07:59 UTC, liamtoozer commented on run_gke.sh
> +BATCH_RUNNER_CONFIG=https://raw.githubusercontent.com/ONSdigital/census-rm-qid-batch-runner/temp-image-location/qid-batch-runner.yml
Good spot! I think I must have pushed this up by mistake when I was working out how to PR stuff.

2019-06-13 10:59 UTC, hbrace approved these changes

2019-06-13 11:19 UTC, merged