763 rmc 115 generate initial
ONSdigital/census-rm-acceptance-tests-2021 pull request #68
Opened 2019-06-05 08:18 UTC by LukeLoze1

# Motivation and Context
Single print file formats for England Wales and NI

# What has changed
Tests to check for this

# How to test?
Download related actionscheduler & actionexporter.
mvn clean install them both locally, make up docker dev and fire off the tests

# Links
https://trello.com/c/ZmGZEf9A/763-rmc-115-action-exporter-to-generate-initial-contact-print-files-13
# Screenshots (if appropriate):

2019-06-05 08:39 UTC, NickGrantONS commented on acceptance_tests/features/sample_file_smoke.feature
> +    Given an action rule of type ICL4E is set 10 seconds in the future
This should be type `ICL4N`.

E = England
W = Wales
N = Northern [Ireland]

2019-06-05 08:40 UTC, NickGrantONS commented on acceptance_tests/features/steps/action_steps.py
> +        'ICL4E': {'treatmentCode': ['HH_1LSFN', 'HH_2LEFN']},
change to `ICL4N`

2019-06-05 08:43 UTC, NickGrantONS commented on acceptance_tests/utilities/print_file_helper.py
> +            if message['payload']['uac']['questionnaireId'][:2] in ('01', '02', '04'):
we are potentially allowing a regression bug here, where multiple UAC/QID pairs get issued for anything other than a Welsh initial contact questionnaire

2019-06-05 08:44 UTC, NickGrantONS commented on resources/sample_files/sample_input_england_census_spec.csv
> +
why all these blank lines

2019-06-05 08:45 UTC, NickGrantX requested changes
Action type should be `ICL4N` not `ICL4E` for Northern Ireland

2019-06-05 09:38 UTC, LukeLoze1 commented on resources/sample_files/sample_input_england_census_spec.csv
> +
The space is symbolic of

2019-06-05 09:39 UTC, jcox-dev requested changes
Tests pass (is this a false-positive, following Nick's comment?) locally just some utility function comments.

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +        purpose = 'Initial contact letter households'
Unless these variables are supposed to change with further checks to the prefix, we can probably return the tuple early and skip assignment altogether.

```suggestion
        return 'Initial contact letter households', 'England'
```

Also, is `in` the right thing to use for the check here?

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    if "P_IC_ICL2" in prefix:
```suggestion
    elif "P_IC_ICL2" in prefix:
```

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    if "P_IC_ICL4" in prefix:
```suggestion
    elif "P_IC_ICL4" in prefix:
```

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    if "P_IC_H1" in prefix:
```suggestion
    elif "P_IC_H1" in prefix:
```

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    if "P_IC_H2" in prefix:
```suggestion
    elif "P_IC_H2" in prefix:
```

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    if "P_IC_H4" in prefix:
```suggestion
    elif "P_IC_H4" in prefix:
```

2019-06-05 09:39 UTC, jcox-dev commented on acceptance_tests/features/steps/print_file_steps.py
> +    return purpose, country
Do we need a default (e.g.: `None, None`)?

2019-06-05 09:39 UTC, jcox-dev commented on resources/sample_files/sample_input_census_spec_england_questionnaire.csv
> +
Empty lines?

2019-06-05 10:55 UTC, LukeLoze1 commented on acceptance_tests/features/steps/print_file_steps.py
> +    return purpose, country
I've decided to assertFalse instead to catch this early

2019-06-05 13:26 UTC, jcox-dev approved these changes

2019-06-06 09:18 UTC, NickGrantX approved these changes
LTGM 👍

2019-06-06 12:08 UTC, hbrace approved these changes

2019-06-06 13:11 UTC, merged