Test for unreceipted cases
ONSdigital/census-rm-acceptance-tests-2021 pull request #70
Opened 2019-06-12 08:22 UTC by AdeHarrison

# Motivation and Context

# What has changed

# How to test?

# Links

# Screenshots (if appropriate):

2019-06-12 09:42 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-152(A) Receipting should update case and UAC active flag (8)](https://trello.com/c/GdA7flOq/788-rmc-152a-receipting-should-update-case-and-uac-active-flag-8)

2019-06-17 14:17 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +@step("all correct case and uac messages are emitted")
This entire step is unused

2019-06-17 14:17 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +def all_correct_cases_and_uacs_emitted(context):
This function is unused

2019-06-17 14:19 UTC, NickGrantONS commented on acceptance_tests/utilities/print_file_helper.py
> +def create_expected_unreceipted_csv_lines(context, prefix, ignore_case_id):
I think you could add an optional `ignore_case_id ` argument to the function `create_expected_csv_lines` instead of having this whole method

2019-06-17 14:20 UTC, NickGrantX requested changes
Unused step/function. Copy-paste code not needed: easy refactor.

2019-06-18 08:01 UTC, AdeHarrison commented on acceptance_tests/features/steps/receipt.py
> +@step("all correct case and uac messages are emitted")
removed as part of merge

2019-06-18 08:01 UTC, AdeHarrison commented on acceptance_tests/features/steps/receipt.py
> +def all_correct_cases_and_uacs_emitted(context):
removed as part of merge

2019-06-18 08:41 UTC, NickGrantONS commented on acceptance_tests/utilities/print_file_helper.py
> +def create_expected_csv_lines(context, prefix, ignore_case_id=None):
👍

2019-06-18 08:42 UTC, NickGrantONS commented on acceptance_tests/utilities/print_file_helper.py
> +        if ignore_case_id is None or case['payload']['collectionCase']['id'] != ignore_case_id:
👍

2019-06-18 08:42 UTC, NickGrantONS commented on run_gke.sh
> -PROJECT_NAME_CONFIG=$(kubectl get configmap project-config -o=jsonpath="{.data.project-name}")
I think this has been taken out by accident

2019-06-18 08:43 UTC, NickGrantONS commented on run_gke.sh
> +    --env=SFTP_DIR=${GCP_PROJECT}/upload/print_service/ \
This shouldn't be changed: GCP_PROJECT is not always set (i.e. when this script is run without any parameters)

2019-06-18 08:46 UTC, NickGrantONS commented on acceptance_tests/features/steps/receipt.py
> +def get_first_case_by_event_type(messages, event_type):
This function seems to be unusused

2019-06-18 08:46 UTC, NickGrantX requested changes
See comments - minor stuff.

2019-06-18 08:50 UTC, AdeHarrison commented on run_gke.sh
> -PROJECT_NAME_CONFIG=$(kubectl get configmap project-config -o=jsonpath="{.data.project-name}")
done

2019-06-18 08:50 UTC, AdeHarrison commented on run_gke.sh
> +    --env=SFTP_DIR=${GCP_PROJECT}/upload/print_service/ \
done

2019-06-18 08:50 UTC, AdeHarrison commented on acceptance_tests/features/steps/receipt.py
> +def get_first_case_by_event_type(messages, event_type):
done

2019-06-20 09:29 UTC, AdamHawtin requested changes

2019-06-20 09:29 UTC, AdamHawtin commented on acceptance_tests/features/sample_file_smoke.feature
> +    Then messages are emitted to RH and Action Scheduler with [01] qids
```suggestion
    When messages are emitted to RH and Action Scheduler with [01] qids
```

2019-06-20 09:29 UTC, AdamHawtin commented on acceptance_tests/features/sample_file_smoke.feature
> +    And only unreceipted cases appear in "P_IC_ICL1" print files
```suggestion
    Then only unreceipted cases appear in "P_IC_ICL1" print files
```

2019-06-20 09:29 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +    create_receipt_received = {'case_id': case_id,
Should this be using QID rather than case ID?

2019-06-24 09:51 UTC, rjweeks commented on acceptance_tests/features/sample_file_smoke.feature
> +    And only unreceipted cases appear in "P_IC_ICL1" print files
Done

2019-06-24 09:51 UTC, rjweeks commented on acceptance_tests/features/sample_file_smoke.feature
> +    Then messages are emitted to RH and Action Scheduler with [01] qids
Done

2019-06-25 11:47 UTC, NickGrantX approved these changes
LGTM 👍

2019-06-25 11:59 UTC, rjweeks approved these changes

2019-06-26 08:35 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +    create_receipt_received = {'case_id': case_id,
Had a conversation, looks like case service still requires and uses case ID on the receipt (which will need to change?) so this is fine for now.

2019-06-26 08:38 UTC, AdamHawtin commented on acceptance_tests/features/steps/print_file_steps.py
> +    if actual_content_list != expected_csv_lines:
👍 Nice, more robust way of comparing these

2019-06-26 08:47 UTC, AdamHawtin approved these changes

2019-06-26 08:54 UTC, merged