Store private key for SFTP SSH as file
ONSdigital/census-rm-acceptance-tests-2021 pull request #74
Opened 2019-06-13 14:45 UTC by NickGrantONS

# Motivation and Context
The acceptance tests keep failing with `binascii.Error: Incorrect padding` type errors. These don't occur when we use a file instead of a string-based key.

# What has changed
Create a temporary file from the string. Supply the file to the SFTP connection settings.

# How to test?
Run ATs in a GKE environment.

# Links
Trello: https://trello.com/c/B6lVt679/611-rmc-179-implement-new-print-file-distribution-method-goanywhere-8

2019-06-13 14:50 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-179 Implement new print file distribution method 'GoAnywhere' (8)](https://trello.com/c/B6lVt679/611-rmc-179-implement-new-print-file-distribution-method-goanywhere-8)

2019-06-14 08:28 UTC, LukeLoze1 requested changes
sftp-ssh-credentials file missing when running against gcp project.  Can't read print filed

2019-06-14 08:28 UTC, LukeLoze1 commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN
I believe that PUBSUB_EMULATOR_HOST should only be set when you want to target the EMULATOR.  In GCP we want the tests to interact with a real pubsub

2019-06-14 08:29 UTC, NickGrantONS commented on Makefile
> +	SFTP_KEY_FILENAME=dummy_sftp_private_key PUBSUB_EMULATOR_HOST=localhost:8538 pipenv run python run.py --log_level WARN
in GCP the Makefile doesn't get run

2019-06-14 09:19 UTC, davidmort approved these changes

2019-06-14 09:22 UTC, LukeLoze1 approved these changes

2019-06-14 09:23 UTC, merged