916 sample loader single source
ONSdigital/census-rm-acceptance-tests-2021 pull request #82
Opened 2019-07-05 11:30 UTC by LukeLoze1

# Motivation and Context
Imports and uses census-rm-sample-loader

# What has changed
no longer has it's own duplicated sample loader and RabbitContext code

# How to test?
This branch currently imports the correct version of census-rm-sample-loader
Run pipenv install --dev to use it then....
make test  (have a standard docker dev up and running first)

# Links
https://trello.com/c/gbDQdP2E/916-update-census-rm-sample-loader-5
https://github.com/ONSdigital/census-rm-sample-loader/tree/916-source-of-truth

# Screenshots (if appropriate):

2019-07-08 11:21 UTC, rjweeks approved these changes

2019-07-09 07:21 UTC, jcox-dev requested changes

2019-07-09 07:21 UTC, jcox-dev commented on Dockerfile
> +RUN apt-get install -y git
This should be tagged onto the end of the line above to save on layers.

2019-07-12 08:44 UTC, jcox-dev submitted a review, later dismissed

2019-07-12 08:44 UTC, jcox-dev commented on acceptance_tests/features/environment.py
> +from rabbit_context import RabbitContext
```suggestion

from rabbit_context import RabbitContext

```

2019-07-12 08:44 UTC, jcox-dev commented on acceptance_tests/features/steps/receipt.py
> +from rabbit_context import RabbitContext
Should sit in same block as the google packages, etc.

2019-07-12 10:04 UTC, ryangrundy7 reviewed
Code looks good, will test it once the merge conflicts have been addressed

2019-07-12 10:05 UTC, ryangrundy7 commented on Pipfile
> +census-rm-sample-loader = {editable = true,git = "https://github.com/ONSdigital/census-rm-sample-loader",ref = "916-source-of-truth"}
Got to remember to remove the `ref` once sample loader has been merged in

2019-07-12 13:18 UTC, AdamHawtin commented on Pipfile
> +census-rm-sample-loader = {editable = true,git = "https://github.com/ONSdigital/census-rm-sample-loader",ref = "916-source-of-truth"}
And specify a release tag

2019-07-12 13:22 UTC, LukeLoze1 commented on Pipfile
> +census-rm-sample-loader = {editable = true,git = "https://github.com/ONSdigital/census-rm-sample-loader",ref = "916-source-of-truth"}
yeap I'll do this when sample-loader is released

2019-07-12 13:30 UTC, AdamHawtin submitted a review, later dismissed

2019-07-12 13:30 UTC, AdamHawtin commented on acceptance_tests/features/environment.py
> +from rabbit_context import RabbitContext
I'm not sure about this, using the rabbit context through the sample loader feels like bad practice. If we're going to reuse the rabbit wrapper code I think it should be pulled out into a library and made properly reusable, then passed into whatever code needs to use it.

2019-07-15 08:16 UTC, AdamHawtin commented on Dockerfile
> +RUN apt-get update -y && apt-get install -y python-pip && apt-get install -y curl && apt-get install -y git
```suggestion
RUN apt-get update -y && apt-get install -y python-pip curl git
```

2019-07-15 08:55 UTC, LukeLoze1 commented on acceptance_tests/features/environment.py
> +from rabbit_context import RabbitContext
I'm not 100% convinced about any of it.  I've put back the local one for ATs for now

2019-07-15 13:05 UTC, AdamHawtin commented on acceptance_tests/features/environment.py
> +    with RabbitContext(port=Config.RABBITMQ_PORT) as rabbit:
`Config.RABBITMQ_PORT` is the default value.

2019-07-15 13:05 UTC, AdamHawtin commented on acceptance_tests/features/environment.py
> +    with RabbitContext(port=Config.RABBITMQ_PORT) as rabbit:
`Config.RABBITMQ_PORT` is the default value.

2019-07-15 13:05 UTC, AdamHawtin commented on acceptance_tests/features/steps/receipt.py
> +    with RabbitContext(queue_name=Config.RABBITMQ_INBOUND_EQ_QUEUE, port=Config.RABBITMQ_PORT) as rabbit:
`Config.RABBITMQ_PORT` is the default value.

2019-07-15 13:05 UTC, AdamHawtin commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    with RabbitContext(queue_name=Config.RABBITMQ_UNADDRESSED_REQUEST_QUEUE, port=Config.RABBITMQ_PORT) as rabbit:
`Config.RABBITMQ_PORT` is the default value.

2019-07-15 13:05 UTC, AdamHawtin commented on acceptance_tests/utilities/rabbit_helper.py
> +    rabbit = RabbitContext(queue_name=queue, port=Config.RABBITMQ_PORT)
`Config.RABBITMQ_PORT` is the default value.

2019-07-15 13:05 UTC, AdamHawtin commented on acceptance_tests/utilities/rabbit_helper.py
> +    with RabbitContext(port=Config.RABBITMQ_PORT) as rabbit:
`Config.RABBITMQ_PORT` is the default value.

2019-07-16 08:24 UTC, LukeLoze1 commented on acceptance_tests/features/steps/unaddressed_steps.py
> +    with RabbitContext(queue_name=Config.RABBITMQ_UNADDRESSED_REQUEST_QUEUE, port=Config.RABBITMQ_PORT) as rabbit:
good spot

2019-07-16 11:06 UTC, ryangrundy7 approved these changes
All tests pass locally and on GCP 👍

2019-07-17 14:03 UTC, liamtoozer approved these changes
LGTM 👍

2019-07-17 14:40 UTC, merged