Test refusal message Fieldwork Adapter cancel
ONSdigital/census-rm-acceptance-tests-2021 pull request #91
Opened 2019-07-22 14:09 UTC by NickGrantONS

# Motivation and Context
The Fieldwork Adapter needs to convert refusal messages received by RM into ActionCancel messages for the  FWMT gateway.

# What has changed
Added end-to-end acceptance test to verify that RM is emitting the correct FWMT message when a refusal is received.

# How to test?
Run the acceptance tests while running the Fieldwork Adapter built on branch `774-rmc-190b-gateway-gateway`.

# Links
Trello: https://trello.com/c/ZFtJpuaa

2019-07-22 14:11 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-190(B) Gateway Gateway - respondent refusal (13)](https://trello.com/c/ZFtJpuaa/774-rmc-190b-gateway-gateway-respondent-refusal-13)

2019-07-23 06:50 UTC, AdamHawtin requested changes
A couple of small suggestions for the code, ~~but should this test not start with the event that comes into RM? As is this could be an integration test on the fieldwork adapter.~~

2019-07-23 06:50 UTC, AdamHawtin commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    assert context.seen_expected_fwmt_message, 'Expected message not seen'
The assert could be split out into a `then` to make the scenario something like 
```
When a refusal event is received
Then an action instruction cancel message is emitted to FWMT
```

2019-07-23 06:50 UTC, AdamHawtin commented on acceptance_tests/utilities/rabbit_context.py
> +        if exchange:
Could do:
```python
       self.channel.basic_publish(
            exchange=exchange or self._exchange,
            routing_key=routing_key or self.queue_name,
            body=message,
            properties=pika.BasicProperties(content_type=content_type))
```

2019-07-23 07:42 UTC, NickGrantONS commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    assert context.seen_expected_fwmt_message, 'Expected message not seen'
I was thinking it can't be split like that because the cancel will be emitted the instant that the refusal event is received, but I suppose it will just sit on the queue waiting to be consumed

2019-07-23 07:48 UTC, NickGrantONS commented on acceptance_tests/utilities/rabbit_context.py
> +        if exchange:
done

2019-07-23 07:48 UTC, NickGrantONS commented on acceptance_tests/features/steps/fieldwork_steps.py
> +    assert context.seen_expected_fwmt_message, 'Expected message not seen'
changed

2019-07-23 08:31 UTC, AdamHawtin approved these changes

2019-07-24 08:30 UTC, LukeLoze1 approved these changes

2019-07-24 08:36 UTC, merged