Handle refusal event
ONSdigital/census-rm-acceptance-tests-2021 pull request #92
Opened 2019-07-25 08:18 UTC by AdeHarrison

## Motivation and Context
To test a Refusal message

## What has changed
Added new acceptance test

## How to test?
[as per](https://github.com/ONSdigital/census-rm-case-processor/pull/30)

## Links
[Trello](https://trello.com/c/29ZsK7ci/825-rmc-197-handle-refusal-received-event-rev13-8)

2019-07-25 08:18 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-197 Handle Refusal Received Event [REV13] (8)](https://trello.com/c/29ZsK7ci/825-rmc-197-handle-refusal-received-event-rev13-8)

2019-07-26 08:50 UTC, ryangrundy7 submitted a review, later dismissed
Got some flake 8 errors when trying to run make test

```
./acceptance_tests/features/steps/refusal.py:22:9: E122 continuation line missing indentation or outdented
./acceptance_tests/features/steps/refusal.py:29:9: E122 continuation line missing indentation or outdented
./acceptance_tests/features/steps/refusal.py:55:5: E122 continuation line missing indentation or outdented
make: *** [flake] Error 1
```

2019-07-26 09:52 UTC, ryangrundy7 commented on acceptance_tests/features/refusal.feature
> +  @wip
Don't need this wip tag

2019-07-26 13:47 UTC, AdamHawtin requested changes
There’s an existing test for the FWMT adapter in fieldwork.feature which sends a baked refusal message and checks the right xml message is to FWMT. Now case-processor is also subscribing to refusals and trying to ingest that baked refusal message but it can’t because the case isn’t set up so it spins on retrying it. I think the `then` from that scenario needs to be included in this new new one and the old scenario deleted.

2019-07-30 12:00 UTC, jcox-dev submitted a review, later dismissed
I noticed there was still a [utility function](https://github.com/ONSdigital/census-rm-acceptance-tests/blob/705158656efe9ffd6b81fff8a3e83b356b9aeeec/acceptance_tests/features/steps/receipt.py#L72) that was still using the outdated `response_datetime` JSON item (removed as part of https://github.com/ONSdigital/census-rm-pubsub/pull/29). This function can probably be removed as part of this PR.

2019-07-30 13:16 UTC, ryangrundy7 approved these changes
Works with all the PRs 👍

2019-07-30 14:01 UTC, jcox-dev approved these changes
Tests all pass in GKE against the branched services  🍰🎉

2019-07-31 07:06 UTC, AdamHawtin approved these changes

2019-07-31 12:27 UTC, merged