Rmc 134 log fulfilment requested event
ONSdigital/census-rm-acceptance-tests-2021 pull request #95
Opened 2019-08-02 13:51 UTC by hbrace

# Motivation and Context

A fulfilment request event needs to be logged.

# What has changed

Feature added to create fulfilment request event is stored in the database.

# How to test?

Build images of:
https://github.com/ONSdigital/census-rm-case-processor/pull/33
https://github.com/ONSdigital/census-rm-case-api/pull/19

And run these acceptance tests

# Links

https://trello.com/c/0cFn8BaV/990-rmc-134a-log-fulfilment-requested-event-5#

# Screenshots (if appropriate):

2019-08-02 13:52 UTC, hbrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-134(A) Log Fulfilment requested event (5)](https://trello.com/c/0cFn8BaV/990-rmc-134a-log-fulfilment-requested-event-5)

2019-08-05 08:54 UTC, liamtoozer approved these changes
LGTM 👍 Might be worth [purging the Rabbit queue](https://github.com/ONSdigital/census-rm-acceptance-tests/blob/master/acceptance_tests/features/environment.py#L33) for fulfilment too, but doesn't stop anything from working for me.

2019-08-05 10:26 UTC, ryangrundy7 requested changes

2019-08-05 10:26 UTC, ryangrundy7 commented on acceptance_tests/features/steps/fulfilment_request.py
> +    response = requests.get(f'{caseapi_url}{context.fulfilment_requested_case_id}', params={'caseEvents': True})
Needs a 2 second sleep here. When testing in Kubernetes i've seen it fail multiple times because it tries to fet the event before it's finished being published

2019-08-06 13:55 UTC, liamtoozer approved these changes

2019-08-07 14:04 UTC, liamtoozer approved these changes

2019-08-07 14:11 UTC, AdeHarrison approved these changes
LGTM

2019-08-07 14:23 UTC, ryangrundy7 approved these changes
LGTM 👍

2019-08-07 18:07 UTC, davidmort approved these changes

2019-08-08 07:06 UTC, merged