Added questionnaire linked acceptance test
ONSdigital/census-rm-acceptance-tests-2021 pull request #96
Opened 2019-08-05 12:24 UTC by AdeHarrison

# How to test?
[as part of ](https://github.com/ONSdigital/census-rm-case-processor/pull/34)

# Links
[Trello](https://trello.com/b/E9lArxTH/rm-census)

# Screenshots (if appropriate):

2019-08-05 12:28 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-142(A) Log QuestionnaireLinked event (5)](https://trello.com/c/h29h2Ty7/991-rmc-142a-log-questionnairelinked-event-5)

2019-08-05 20:38 UTC, davidmort requested changes

2019-08-05 20:38 UTC, davidmort commented on acceptance_tests/features/unaddressed.feature
> +    Then an UACUpdated message of questionnaire type 01 linking a questionnaire to a case is sent
the acceptance criteria for this story says about logging/storing the questionnaire_linked case event, not the emission of UAC Updated event

2019-08-06 13:51 UTC, AdeHarrison commented on acceptance_tests/features/unaddressed.feature
> +    Then an UACUpdated message of questionnaire type 01 linking a questionnaire to a case is sent
done

2019-08-07 18:55 UTC, davidmort submitted a review, later dismissed

2019-08-07 18:55 UTC, davidmort commented on acceptance_tests/features/steps/unaddressed.py
> +            'type': 'RESPONSE_RECEIVED',
the type here should be  QUESTIONNAIRE_LINKED

2019-08-07 18:55 UTC, davidmort commented on acceptance_tests/features/steps/unaddressed.py
> +    start_listening_to_rabbit_queue(Config.RABBITMQ_RH_OUTBOUND_UAC_QUEUE_TEST,
this isn't really checking if an event is being logged, its checking that a UAC_UPDATED event is being emitted

2019-08-08 06:25 UTC, AdeHarrison commented on acceptance_tests/features/steps/unaddressed.py
> +            'type': 'RESPONSE_RECEIVED',
done

2019-08-08 06:25 UTC, AdeHarrison commented on acceptance_tests/features/steps/unaddressed.py
> +    start_listening_to_rabbit_queue(Config.RABBITMQ_RH_OUTBOUND_UAC_QUEUE_TEST,
done

2019-08-08 08:13 UTC, LukeLoze1 approved these changes
Fine if Dave's comment is fixed

2019-08-08 09:53 UTC, hbrace submitted a review, later dismissed

2019-08-08 10:29 UTC, hbrace approved these changes
Looks good!

2019-08-08 10:39 UTC, merged