Add acceptance test for new UAC/QID endpoint in case-api.
ONSdigital/census-rm-acceptance-tests-2021 pull request #97
Opened 2019-08-05 13:49 UTC by rjweeks

# Motivation and Context
New UAC QID endpoint added to census-rm-case-api

# Links
https://github.com/ONSdigital/census-rm-case-api/pull/18?_pjax=%23js-repo-pjax-container

2019-08-05 13:52 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-134(B) synchronous UAC/QID creation via case api (part 1) (5)](https://trello.com/c/0Jmh2jK2/1003-rmc-134b-synchronous-uac-qid-creation-via-case-api-part-1-5)

2019-08-05 20:57 UTC, davidmort requested changes

2019-08-05 20:57 UTC, davidmort commented on acceptance_tests/features/steps/case_look_up.py
> +    context.uacqid_json = '{"questionnaire_id":"1"}'
is it worth testing that we have both a qid and a uac?

2019-08-06 08:17 UTC, rjweeks commented on acceptance_tests/features/steps/case_look_up.py
> +    context.uacqid_json = '{"questionnaire_id":"1"}'
Added these checks.

2019-08-06 11:10 UTC, AdamHawtin requested changes

2019-08-06 11:10 UTC, AdamHawtin commented on acceptance_tests/features/case_look_up.feature
> +  Scenario: Check a UAC QID pair can be generated
I think this should go in a new feature file rather than case_look_up

2019-08-06 11:10 UTC, AdamHawtin commented on acceptance_tests/features/case_look_up.feature
> +    Given a valid questionnaire id in json
```suggestion
    When a UAC/QID pair is requested with a valid questionnaire type
```

2019-08-06 11:10 UTC, AdamHawtin commented on acceptance_tests/features/case_look_up.feature
> +    Then caseapi should return a 201
```suggestion
    Then caseapi should return a new UAC and QID with correct questionnaire type
```

2019-08-06 11:10 UTC, AdamHawtin commented on acceptance_tests/features/steps/case_look_up.py
> +    assert 'qid' in response_data, 'qid missing in response'
I think this should also check the QID returned has the correct questionnaire type.

2019-08-06 12:36 UTC, rjweeks commented on acceptance_tests/features/case_look_up.feature
> +  Scenario: Check a UAC QID pair can be generated
Done

2019-08-06 12:36 UTC, rjweeks commented on acceptance_tests/features/case_look_up.feature
> +    Given a valid questionnaire id in json
Done

2019-08-06 12:36 UTC, rjweeks commented on acceptance_tests/features/case_look_up.feature
> +    Then caseapi should return a 201
Done.

2019-08-06 12:47 UTC, rjweeks commented on acceptance_tests/features/steps/case_look_up.py
> +    assert 'qid' in response_data, 'qid missing in response'
Added additional check.

2019-08-06 12:51 UTC, AdamHawtin commented on acceptance_tests/features/steps/adhoc_uac_qid.py
> +    context.uacqid_json = {"questionnaireType":"01"}
flake8 failure: `E231 missing whitespace after ':'`, needs formatting

2019-08-06 12:56 UTC, rjweeks commented on acceptance_tests/features/steps/adhoc_uac_qid.py
> +    context.uacqid_json = {"questionnaireType":"01"}
Fixed.

2019-08-06 13:10 UTC, davidmort approved these changes

2019-08-06 13:29 UTC, AdamHawtin approved these changes

2019-08-06 13:30 UTC, merged